# Generated by Django 5.2.17 on 2026-10-07 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0006_program_settings"),
        ("program", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "conférence"), ("session", "session")],
                        default="global",
                        max_length=8,
                        verbose_name="portée",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=150, verbose_name="titre (FR)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="titre (EN)",
                    ),
                ),
                (
                    "intro_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="introduction (FR)"
                    ),
                ),
                (
                    "intro_en",
                    models.TextField(
                        blank=True, default="", verbose_name="introduction (EN)"
                    ),
                ),
                (
                    "opens_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ouverture"
                    ),
                ),
                (
                    "closes_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="clôture"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "brouillon"), ("published", "publié")],
                        default="draft",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publié le"
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verrouillé le"
                    ),
                ),
                (
                    "invite_cursor",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="curseur des invitations"
                    ),
                ),
                (
                    "invitations_done",
                    models.BooleanField(
                        default=False, verbose_name="invitations envoyées"
                    ),
                ),
                (
                    "remind_cursor",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="curseur de la relance"
                    ),
                ),
                (
                    "reminders_done",
                    models.BooleanField(default=False, verbose_name="relance envoyée"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="surveys",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="program.session",
                        verbose_name="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "questionnaire",
                "verbose_name_plural": "questionnaires",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SurveyInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invited_on", models.DateField(verbose_name="invitée le")),
                (
                    "reminded_on",
                    models.DateField(blank=True, null=True, verbose_name="relancée le"),
                ),
                (
                    "answered_on",
                    models.DateField(blank=True, null=True, verbose_name="répondu le"),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invitations",
                        to="surveys.survey",
                        verbose_name="questionnaire",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="personne invitée",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation à un questionnaire",
                "verbose_name_plural": "invitations aux questionnaires",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="position"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rating", "note de 1 à 5"),
                            ("single", "choix unique"),
                            ("multiple", "choix multiples"),
                            ("text", "texte libre"),
                        ],
                        max_length=8,
                        verbose_name="type",
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(max_length=300, verbose_name="libellé (FR)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="libellé (EN)",
                    ),
                ),
                (
                    "choices",
                    models.JSONField(blank=True, default=list, verbose_name="choix"),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="obligatoire"),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="surveys.survey",
                        verbose_name="questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ("survey", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answers", models.JSONField(default=dict, verbose_name="réponses")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="responses",
                        to="surveys.survey",
                        verbose_name="questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "réponse à un questionnaire",
                "verbose_name_plural": "réponses aux questionnaires",
            },
        ),
        migrations.AddConstraint(
            model_name="survey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("opens_at__isnull", True),
                    ("closes_at__isnull", True),
                    ("closes_at__gt", models.F("opens_at")),
                    _connector="OR",
                ),
                name="srv_survey_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="survey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "global"), ("session__isnull", True)),
                    models.Q(("scope", "session"), ("session__isnull", False)),
                    _connector="OR",
                ),
                name="srv_survey_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyinvitation",
            constraint=models.UniqueConstraint(
                fields=("survey", "user"), name="srv_invitation_unique"
            ),
        ),
    ]
