# Generated by Django 5.2.17 on 2026-10-06 05:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0006_program_settings"),
        ("submissions", "0003_duplicates_reminders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PresentationConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "presenters",
                    models.JSONField(
                        default=list,
                        verbose_name="présentateurs (positions des auteurs)",
                    ),
                ),
                ("confirmed_at", models.DateTimeField(verbose_name="confirmée le")),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="confirmée par",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="presentation_confirmation",
                        to="submissions.submission",
                        verbose_name="communication",
                    ),
                ),
            ],
            options={
                "verbose_name": "confirmation de présentation",
                "verbose_name_plural": "confirmations de présentation",
            },
        ),
        migrations.CreateModel(
            name="ProgramState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=0, verbose_name="révision du brouillon"
                    ),
                ),
                (
                    "published_revision",
                    models.PositiveIntegerField(
                        default=0, verbose_name="révision publiée"
                    ),
                ),
                (
                    "published_version",
                    models.PositiveIntegerField(
                        default=0, verbose_name="dernière version publiée"
                    ),
                ),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="program_state",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "état du programme",
                "verbose_name_plural": "états du programme",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100000)],
                        verbose_name="capacité",
                    ),
                ),
                (
                    "equipment",
                    models.JSONField(
                        blank=True, default=list, verbose_name="équipements"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", verbose_name="note sur l'équipement"
                    ),
                ),
                (
                    "is_accessible",
                    models.BooleanField(default=False, verbose_name="accessible"),
                ),
                (
                    "access_note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="indications d'accès",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rooms",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "salle",
                "verbose_name_plural": "salles",
                "ordering": ("edition", "position", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opening", "ouverture"),
                            ("keynote", "conférence plénière"),
                            ("parallel", "session parallèle"),
                            ("poster", "session posters"),
                            ("workshop", "atelier"),
                            ("tutorial", "tutoriel"),
                            ("round_table", "table ronde"),
                            ("assembly", "assemblée ou réunion"),
                            ("break", "pause"),
                            ("meal", "repas"),
                            ("social", "activité sociale"),
                            ("closing", "clôture"),
                        ],
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=255, verbose_name="titre (FR)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="titre (EN)",
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="description (FR)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="description (EN)"
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="début")),
                ("ends_at", models.DateTimeField(verbose_name="fin")),
                (
                    "instructions",
                    models.TextField(blank=True, default="", verbose_name="consignes"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="program_sessions",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sessions",
                        to="program.room",
                        verbose_name="salle",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.track",
                        verbose_name="thématique",
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "ordering": ("edition", "starts_at", "room", "id"),
            },
        ),
        migrations.CreateModel(
            name="SessionRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chair", "président de séance"),
                            ("discussant", "discutant"),
                            ("moderator", "modérateur"),
                            ("panelist", "panéliste"),
                        ],
                        max_length=12,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="roles",
                        to="program.session",
                        verbose_name="session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="session_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="personne",
                    ),
                ),
            ],
            options={
                "verbose_name": "rôle de séance",
                "verbose_name_plural": "rôles de séance",
                "ordering": ("session", "role", "id"),
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "duration_min",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(600),
                        ],
                        verbose_name="durée (minutes)",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="début")),
                ("ends_at", models.DateTimeField(verbose_name="fin")),
                (
                    "title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="titre libre (FR)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="titre libre (EN)",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="slots",
                        to="program.session",
                        verbose_name="session",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="program_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="intervenant invité",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="program_slot",
                        to="submissions.submission",
                        verbose_name="communication",
                    ),
                ),
            ],
            options={
                "verbose_name": "créneau",
                "verbose_name_plural": "créneaux",
                "ordering": ("session", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgramPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="version")),
                (
                    "revision",
                    models.PositiveIntegerField(verbose_name="révision publiée"),
                ),
                ("published_at", models.DateTimeField(verbose_name="publiée le")),
                ("snapshot", models.JSONField(verbose_name="instantané")),
                ("summary", models.JSONField(default=dict, verbose_name="différences")),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="program_publications",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="publiée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "publication du programme",
                "verbose_name_plural": "publications du programme",
                "ordering": ("edition", "-version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "version"), name="prog_publication_once"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("edition", "name"), name="prog_room_name"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["room", "starts_at"], name="prog_session_room"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["edition", "starts_at"], name="prog_session_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="prog_session_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionrole",
            constraint=models.UniqueConstraint(
                fields=("session", "user", "role"), name="prog_role_once"
            ),
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(fields=["starts_at"], name="prog_slot_start"),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="prog_slot_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("submission__isnull", False),
                    models.Q(("title_fr", ""), _negated=True),
                    _connector="OR",
                ),
                name="prog_slot_content",
            ),
        ),
    ]
