/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentRef } from '../../models/document-ref';

export interface RegistrationsProforma$Params {
  registration_id: number;
}

export function registrationsProforma(http: HttpClient, rootUrl: string, params: RegistrationsProforma$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentRef>> {
  const rb = new RequestBuilder(rootUrl, registrationsProforma.PATH, 'post');
  if (params) {
    rb.path('registration_id', params.registration_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentRef>;
    })
  );
}

registrationsProforma.PATH = '/v1/registrations/{registration_id}/proforma';
