/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Quote } from '../../models/quote';
import { QuoteRequestRequest } from '../../models/quote-request-request';

export interface RegistrationQuote$Params {
      body: QuoteRequestRequest
}

export function registrationQuote(http: HttpClient, rootUrl: string, params: RegistrationQuote$Params, context?: HttpContext): Observable<StrictHttpResponse<Quote>> {
  const rb = new RequestBuilder(rootUrl, registrationQuote.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Quote>;
    })
  );
}

registrationQuote.PATH = '/v1/registrations/quote';
