/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LetterRequestRequest } from '../../models/letter-request-request';
import { MyLetter } from '../../models/my-letter';

export interface RegistrationsLetterRequest$Params {
  registration_id: number;
      body: LetterRequestRequest
}

export function registrationsLetterRequest(http: HttpClient, rootUrl: string, params: RegistrationsLetterRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<MyLetter>> {
  const rb = new RequestBuilder(rootUrl, registrationsLetterRequest.PATH, 'post');
  if (params) {
    rb.path('registration_id', params.registration_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MyLetter>;
    })
  );
}

registrationsLetterRequest.PATH = '/v1/registrations/{registration_id}/invitation-letter';
