/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RegistrationsDocument$Params {
  document_id: number;
  registration_id: number;
}

export function registrationsDocument(http: HttpClient, rootUrl: string, params: RegistrationsDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, registrationsDocument.PATH, 'get');
  if (params) {
    rb.path('document_id', params.document_id, {});
    rb.path('registration_id', params.registration_id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/pdf', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

registrationsDocument.PATH = '/v1/registrations/{registration_id}/documents/{document_id}';
