/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MyRegistration } from '../../models/my-registration';
import { ProofUploadRequest } from '../../models/proof-upload-request';

export interface RegistrationsProof$Params {
  registration_id: number;
      body: ProofUploadRequest
}

export function registrationsProof(http: HttpClient, rootUrl: string, params: RegistrationsProof$Params, context?: HttpContext): Observable<StrictHttpResponse<MyRegistration>> {
  const rb = new RequestBuilder(rootUrl, registrationsProof.PATH, 'post');
  if (params) {
    rb.path('registration_id', params.registration_id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MyRegistration>;
    })
  );
}

registrationsProof.PATH = '/v1/registrations/{registration_id}/proof';
