# Generated by Django 5.2.17 on 2026-10-07 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0006_program_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "à faire"),
                            ("doing", "en cours"),
                            ("done", "terminée"),
                        ],
                        default="todo",
                        max_length=8,
                        verbose_name="statut",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "basse"),
                            ("normal", "normale"),
                            ("high", "haute"),
                        ],
                        default="normal",
                        max_length=8,
                        verbose_name="priorité",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="étiquette"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="échéance"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="position dans la colonne"
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=1, verbose_name="révision"),
                ),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminée le"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archivée le"
                    ),
                ),
                (
                    "reminded_on",
                    models.DateField(blank=True, null=True, verbose_name="rappelée le"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créée par",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tasks",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "tâche",
                "verbose_name_plural": "tâches",
                "ordering": ("edition", "status", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "storage_name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="nom de stockage"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="nom du fichier"),
                ),
                ("kind", models.CharField(max_length=8, verbose_name="type")),
                ("size", models.PositiveIntegerField(verbose_name="taille (octets)")),
                ("sha256", models.CharField(max_length=64, verbose_name="empreinte")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="attachments",
                        to="logistics.task",
                        verbose_name="tâche",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="déposée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "pièce jointe de tâche",
                "verbose_name_plural": "pièces jointes de tâche",
                "ordering": ("task", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(verbose_name="texte")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="comments",
                        to="logistics.task",
                        verbose_name="tâche",
                    ),
                ),
            ],
            options={
                "verbose_name": "commentaire de tâche",
                "verbose_name_plural": "commentaires de tâche",
                "ordering": ("task", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("expense", "dépense"), ("income", "recette")],
                        max_length=8,
                        verbose_name="nature",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("venue", "lieu"),
                            ("catering", "restauration"),
                            ("travel", "voyages"),
                            ("accommodation", "hébergement"),
                            ("communication", "communication"),
                            ("printing", "impression"),
                            ("equipment", "matériel"),
                            ("staff", "personnel"),
                            ("other_expense", "divers (dépense)"),
                            ("registrations", "inscriptions"),
                            ("sponsorship", "partenariats"),
                            ("grants", "subventions"),
                            ("other_income", "divers (recette)"),
                        ],
                        max_length=16,
                        verbose_name="poste",
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="libellé")),
                (
                    "planned",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="prévu"
                    ),
                ),
                (
                    "actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="réalisé",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "saisi"),
                            ("registrations", "calculé : inscriptions"),
                            ("sponsors", "calculé : partenaires"),
                        ],
                        default="manual",
                        max_length=16,
                        verbose_name="origine du réalisé",
                    ),
                ),
                (
                    "computed_key",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="note")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="position"),
                ),
                (
                    "proof_storage_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="justificatif (nom de stockage)",
                    ),
                ),
                (
                    "proof_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="justificatif",
                    ),
                ),
                (
                    "proof_kind",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=8,
                        verbose_name="type du justificatif",
                    ),
                ),
                (
                    "proof_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="taille du justificatif"
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="budget_lines",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de budget",
                "verbose_name_plural": "lignes de budget",
                "ordering": ("edition", "kind", "position", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("planned__gte", 0)),
                        name="log_budget_planned_pos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actual__isnull", True),
                            ("actual__gte", 0),
                            _connector="OR",
                        ),
                        name="log_budget_actual_pos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source", "manual"),
                            ("actual__isnull", True),
                            _connector="OR",
                        ),
                        name="log_budget_computed_actual",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["edition", "status", "position"], name="log_task_column"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "due_date"], name="log_task_assignee"
            ),
        ),
    ]
