# Generated by Django 5.2.17 on 2026-10-07 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0006_program_settings"),
        ("logistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title_fr",
                    models.CharField(max_length=150, verbose_name="intitulé (FR)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="intitulé (EN)",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="lieu"
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="début")),
                ("ends_at", models.DateTimeField(verbose_name="fin")),
                (
                    "needed",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="bénévoles nécessaires"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, default="", verbose_name="consignes"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="volunteer_shifts",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "poste de bénévolat",
                "verbose_name_plural": "postes de bénévolat",
                "ordering": ("edition", "starts_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="affecté par",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="bénévole",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="logistics.volunteershift",
                        verbose_name="poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "affectation de bénévole",
                "verbose_name_plural": "affectations de bénévoles",
                "ordering": ("shift", "id"),
            },
        ),
        migrations.CreateModel(
            name="DietaryDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diets",
                    models.JSONField(blank=True, default=list, verbose_name="régimes"),
                ),
                (
                    "allergies",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="allergies"
                    ),
                ),
                (
                    "consented_at",
                    models.DateTimeField(verbose_name="consentement donné le"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dietary_declarations",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dietary_declarations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="personne",
                    ),
                ),
            ],
            options={
                "verbose_name": "régime alimentaire",
                "verbose_name_plural": "régimes alimentaires",
                "ordering": ("edition", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "user"), name="log_diet_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField(verbose_name="jour")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("coffee_break", "pause café"),
                            ("lunch", "déjeuner"),
                            ("dinner", "dîner"),
                            ("cocktail", "cocktail"),
                        ],
                        max_length=14,
                        verbose_name="type",
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="libellé (FR)",
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="libellé (EN)",
                    ),
                ),
                (
                    "include_registered",
                    models.BooleanField(
                        default=True, verbose_name="inscrits confirmés"
                    ),
                ),
                (
                    "option_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="option requise",
                    ),
                ),
                (
                    "include_speakers",
                    models.BooleanField(
                        default=True, verbose_name="intervenants invités"
                    ),
                ),
                (
                    "include_committees",
                    models.BooleanField(
                        default=False, verbose_name="membres des comités"
                    ),
                ),
                (
                    "include_volunteers",
                    models.BooleanField(default=False, verbose_name="bénévoles"),
                ),
                (
                    "margin_percent",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="marge (%)"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="meals",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "repas",
                "verbose_name_plural": "repas",
                "ordering": ("edition", "day", "position", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("margin_percent__lte", 50)),
                        name="log_meal_margin",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SpeakerVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "technical_needs",
                    models.JSONField(
                        blank=True, default=list, verbose_name="besoins techniques"
                    ),
                ),
                (
                    "technical_note",
                    models.TextField(
                        blank=True, default="", verbose_name="précisions techniques"
                    ),
                ),
                (
                    "arrival_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="arrivée"),
                ),
                (
                    "arrival_means",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plane", "avion"),
                            ("train", "train"),
                            ("road", "route"),
                            ("other", "autre"),
                        ],
                        default="",
                        max_length=8,
                        verbose_name="moyen d'arrivée",
                    ),
                ),
                (
                    "arrival_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="vol ou train (arrivée)",
                    ),
                ),
                (
                    "departure_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="départ"),
                ),
                (
                    "departure_means",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plane", "avion"),
                            ("train", "train"),
                            ("road", "route"),
                            ("other", "autre"),
                        ],
                        default="",
                        max_length=8,
                        verbose_name="moyen de départ",
                    ),
                ),
                (
                    "departure_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="vol ou train (départ)",
                    ),
                ),
                (
                    "accommodation_needed",
                    models.BooleanField(
                        default=False, verbose_name="hébergement demandé"
                    ),
                ),
                (
                    "transfer_needed",
                    models.BooleanField(
                        default=False, verbose_name="transfert demandé"
                    ),
                ),
                (
                    "speaker_note",
                    models.TextField(
                        blank=True, default="", verbose_name="demandes de l'intervenant"
                    ),
                ),
                (
                    "hotel",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="hôtel"
                    ),
                ),
                (
                    "check_in",
                    models.DateField(
                        blank=True, null=True, verbose_name="arrivée à l'hôtel"
                    ),
                ),
                (
                    "check_out",
                    models.DateField(
                        blank=True, null=True, verbose_name="départ de l'hôtel"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_arrange", "à organiser"),
                            ("booked", "réservée"),
                            ("confirmed", "confirmée"),
                        ],
                        default="to_arrange",
                        max_length=12,
                        verbose_name="prise en charge",
                    ),
                ),
                (
                    "internal_note",
                    models.TextField(
                        blank=True, default="", verbose_name="note interne"
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="speaker_visits",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mise à jour par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="speaker_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="intervenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "fiche de venue",
                "verbose_name_plural": "fiches de venue",
                "ordering": ("edition", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "user"), name="log_visit_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="volunteershift",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="log_shift_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteershift",
            constraint=models.CheckConstraint(
                condition=models.Q(("needed__gte", 1)), name="log_shift_needed"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftassignment",
            constraint=models.UniqueConstraint(
                fields=("shift", "volunteer"), name="log_shift_assignment"
            ),
        ),
    ]
