/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityEntry {
  action: string;
  actor: string;
  at: string;
  object_id: string;
  object_type: string;
}
