/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `user` - utilisateur
 * * `command` - commande
 * * `system` - système
 */
export type ActorKind = 'user' | 'command' | 'system';

