/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SessionKind } from '../models/session-kind';
export interface AgendaSession {
  id: number;
  kind: SessionKind;
  title_en: string;
  title_fr: string;
}
