/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `draft` - brouillon
 * * `published` - publiée
 * * `withdrawn` - retirée
 */
export type AnnouncementStatus = 'draft' | 'published' | 'withdrawn';

