/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorCode } from '../models/error-code';

/**
 * Format de toute réponse d'erreur de l'API : {code, message, fields}.
 */
export interface ApiError {
  code: ErrorCode;

  /**
   * Erreurs par champ : {nom du champ: [messages]} ; objet vide sinon.
   */
  fields: {
[key: string]: any;
};

  /**
   * Message lisible, dans la langue de la requête.
   */
  message: string;
}
