/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssignmentStatus } from '../models/assignment-status';
import { NullEnum } from '../models/null-enum';
import { Person } from '../models/person';
import { ReviewStatus } from '../models/review-status';
export interface AssignmentManage {
  assigned_at: string;
  assigned_by: Person | null;
  conflict_override_reason: string;
  due_at: string | null;
  id: number;
  pseudonym_rank: number;
  reason: string;
  reminders: any;

  /**
   * Évaluation : null (non commencée), draft ou submitted.
   */
  review_status: ((ReviewStatus | NullEnum)) | null;
  reviewer: Person;
  status: AssignmentStatus;
}
