/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `active` - actif
 * * `declined` - déclinée
 * * `cancelled` - annulée
 */
export type AssignmentStatus = 'active' | 'declined' | 'cancelled';

