/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActorKind } from '../models/actor-kind';

/**
 * Entrée du journal d'une édition, **sans IP ni navigateur** (minimisation, §7.4).
 */
export interface AuditEntry {
  action: string;
  actor_id: number | null;
  actor_kind: ActorKind;
  actor_name: string;
  after: any | null;
  at: string;
  before: any | null;
  id: number;
  object_id: string;
  object_type: string;
  reason: string;
}
