/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthorWriteRequest } from '../models/author-write-request';
export interface AuthorsWriteRequest {
  authors: Array<AuthorWriteRequest>;
}
