/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * RG-10 : commentaire d'un relecteur, sous pseudonyme ; ni nom, ni note.
 */
export interface AuthorReviewComment {
  comment: string;
  pseudonym_rank: number;
}
