/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Mentions de facturation (J8, Q8) : lecture ``finance.read``, écriture
 * ``pricing.write`` avec réauthentification récente (J1). ``is_complete`` : raison sociale
 * et adresse renseignées, sans quoi aucune facture ne s'émet.
 */
export interface BillingProfile {
  address?: string;
  bank_details?: string;
  credit_note_prefix?: string;
  footer?: string;
  invoice_prefix?: string;
  is_complete: boolean;
  legal_name?: string;
  proforma_prefix?: string;
  tax_identifiers?: string;
  vat_note?: string;
  vat_rate?: string | null;
}
