/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Currency } from '../models/currency';
import { DocumentKind } from '../models/document-kind';

/**
 * Pièce de facturation (gestion, ``finance.read``).
 */
export interface BillingDocument {
  amount: string;
  currency: Currency;
  customer: string;
  id: number;
  issued_at: string;
  kind: DocumentKind;
  number: string;
  original: string | null;
  registration_id: number;
  registration_reference: string;
}
