/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetSource } from './budget-source';

/**
 * Each possible value of `BudgetSource`
 */
export const BUDGET_SOURCE: BudgetSource[] = [
  'manual',
  'registrations',
  'sponsors'
];