/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetCategory } from '../models/budget-category';
import { BudgetKind } from '../models/budget-kind';
export interface BudgetCategoryTotals {
  actual: string;
  category: BudgetCategory;
  kind: BudgetKind;
  planned: string;
}
