/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetCategoryTotals } from '../models/budget-category-totals';
import { BudgetLine } from '../models/budget-line';
import { BudgetTotals } from '../models/budget-totals';
export interface Budget {
  balance_actual: string;
  balance_planned: string;
  by_category: Array<BudgetCategoryTotals>;
  currency: string;
  expense: BudgetTotals;
  income: BudgetTotals;
  lines: Array<BudgetLine>;
}
