/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetCategory } from '../models/budget-category';
import { BudgetKind } from '../models/budget-kind';
import { BudgetProof } from '../models/budget-proof';
import { BudgetSource } from '../models/budget-source';
export interface BudgetLine {
  actual: string | null;
  category: BudgetCategory;
  computed: boolean;
  id: number;
  kind: BudgetKind;
  label: string;
  note: string;
  planned: string;
  position: number;
  proof: BudgetProof | null;
  source: BudgetSource;
  variance: string | null;
}
