/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetCategory } from './budget-category';

/**
 * Each possible value of `BudgetCategory`
 */
export const BUDGET_CATEGORY: BudgetCategory[] = [
  'venue',
  'catering',
  'travel',
  'accommodation',
  'communication',
  'printing',
  'equipment',
  'staff',
  'other_expense',
  'registrations',
  'sponsorship',
  'grants',
  'other_income'
];