/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetKind } from './budget-kind';

/**
 * Each possible value of `BudgetKind`
 */
export const BUDGET_KIND: BudgetKind[] = [
  'expense',
  'income'
];