/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BundleCategory } from '../models/bundle-category';
import { BundleEntry } from '../models/bundle-entry';
import { BundleRetired } from '../models/bundle-retired';

/**
 * Liste de pointage hors ligne (K5) : minimale, sans jeton, à effacer après 48 h.
 */
export interface Bundle {
  categories: Array<BundleCategory>;
  edition_id: number;
  entries: Array<BundleEntry>;
  expires_at: string;
  generated_at: string;
  retired: Array<BundleRetired>;
}
