/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConflictKind } from '../models/conflict-kind';
export interface CandidateConflict {
  kind: ConflictKind;
  overridable: boolean;
  overridden: boolean;
}
