/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CandidateConflict } from '../models/candidate-conflict';

/**
 * Relecteur proposé pour une soumission (H6, H7, H8).
 */
export interface Candidate {

  /**
   * Affectation active sur cette soumission, sinon null.
   */
  assignment_id: number | null;
  conflicts: Array<CandidateConflict>;
  id: number;
  institution: string;

  /**
   * Affectations actives dans l'édition.
   */
  load: number;
  name: string;

  /**
   * Expertises.
   */
  tracks: Array<string>;
}
