/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Capability } from './capability';

/**
 * Each possible value of `Capability`
 */
export const CAPABILITY: Capability[] = [
  'edition.read',
  'edition.write',
  'edition.publish',
  'edition.archive',
  'members.read',
  'members.manage',
  'audit.read'
];