/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryTotal {
  amount: string;
  code: string;
  confirmed: number;
  label_en: string;
  label_fr: string;
}
