/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Fee } from '../models/fee';

/**
 * Catégorie et sa grille de tarifs (gestion). ``code`` : fixé à la création.
 */
export interface Category {
  code: string;
  description_en?: string;
  description_fr?: string;
  fees: Array<Fee>;
  id: number;
  in_use: boolean;
  is_active?: boolean;
  label_en?: string;
  label_fr: string;
  position?: number;
  requires_proof?: boolean;
}
