/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `participation` - attestation de participation
 * * `presentation` - attestation de communication
 * * `review` - attestation d'évaluation
 */
export type CertificateNature = 'participation' | 'presentation' | 'review';

