/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CheckinOutcome } from './checkin-outcome';

/**
 * Each possible value of `CheckinOutcome`
 */
export const CHECKIN_OUTCOME: CheckinOutcome[] = [
  'checked_in',
  'already_checked_in',
  'unknown',
  'other_edition',
  'cancelled',
  'expired',
  'replaced',
  'pending_payment',
  'not_allowed',
  'unknown_session'
];