/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RegistrationStatus } from '../models/registration-status';

/**
 * Personne pointée : référence, nom, catégorie, statut ; ni adresse ni institution.
 */
export interface CheckinPerson {
  category: string;
  category_label_en: string;
  category_label_fr: string;
  id: number;
  name: string;
  reference: string;
  status: RegistrationStatus;
}
