/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConflictSource } from './conflict-source';

/**
 * Each possible value of `ConflictSource`
 */
export const CONFLICT_SOURCE: ConflictSource[] = [
  'reviewer',
  'system',
  'chair'
];