/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `author` - auteur de la soumission
 * * `institution` - même institution
 * * `declared` - déclaré
 */
export type ConflictKind = 'author' | 'institution' | 'declared';

