/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Double aveugle et nombre de relecteurs (gestion, §6.1).
 */
export interface Confidentiality {
  double_blind?: boolean;

  /**
   * Réglages gelés depuis la première soumission (RG-19).
   */
  frozen_fields: Array<string>;
  reviewers_per_submission?: number;
}
