/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConfirmPresentationRequest {

  /**
   * Positions des auteurs qui présentent.
   */
  presenters: Array<number>;
}
