/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConflictKind } from '../models/conflict-kind';
import { ConflictSource } from '../models/conflict-source';
import { Person } from '../models/person';
export interface ConflictManage {
  created_at: string;
  declared_by: Person | null;
  id: number;
  kind: ConflictKind;
  overridden_at: string | null;
  overridden_by: Person | null;
  overridden_reason: string;
  reason: string;
  reviewer: Person;
  source: ConflictSource;
}
