/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `reviewer` - déclaré par le relecteur
 * * `system` - détecté par le système
 * * `chair` - déclaré par le président
 */
export type ConflictSource = 'reviewer' | 'system' | 'chair';

