/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `first_login` - première connexion
 * * `account` - espace compte
 */
export type ConsentRequestSource = 'first_login' | 'account';

