/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConsentKind } from '../models/consent-kind';
import { ConsentRequestSource } from '../models/consent-request-source';
export interface ConsentCreateRequest {
  granted: boolean;
  kind: ConsentKind;
  source?: ConsentRequestSource;
}
