/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConsentRequestSource } from './consent-request-source';

/**
 * Each possible value of `ConsentRequestSource`
 */
export const CONSENT_REQUEST_SOURCE: ConsentRequestSource[] = [
  'first_login',
  'account'
];