/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CounterRequestRequest {
  category: string;
  country?: string;
  email: string;
  first_name?: string;
  institution?: string;
  last_name?: string;
  options?: Array<string>;

  /**
   * Réglé au comptoir : paiement « sur place » enregistré.
   */
  paid?: boolean;
}
