/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CriterionWriteRequest {
  code: string;
  help_en?: string;
  help_fr?: string;
  is_required?: boolean;
  label_en?: string;
  label_fr: string;
  weight: string;
}
