/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Currency } from './currency';

/**
 * Each possible value of `Currency`
 */
export const CURRENCY: Currency[] = [
  'XOF',
  'XAF',
  'EUR',
  'USD',
  'GNF',
  'CDF'
];