/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DatabaseEnum } from './database-enum';

/**
 * Each possible value of `DatabaseEnum`
 */
export const DATABASE_ENUM: DatabaseEnum[] = [
  'ok',
  'error'
];