/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { SubmissionStatus } from '../models/submission-status';
export interface DaySlot {
  ends_at: string;
  id: number;
  presenters: Array<string>;
  reference: string;
  starts_at: string;

  /**
   * Statut courant de la communication (vide : élément libre).
   *
   * * `draft` - brouillon
   * * `submitted` - soumise
   * * `screening` - vérification de recevabilité
   * * `under_review` - en cours d'évaluation
   * * `reviewed` - évaluée
   * * `accepted` - acceptée
   * * `accepted_minor` - acceptée sous réserve de corrections
   * * `waitlist` - liste d'attente
   * * `rejected` - rejetée
   * * `revision_requested` - corrections demandées
   * * `camera_ready_received` - version finale reçue
   * * `confirmed` - présentation confirmée
   * * `scheduled` - programmée
   * * `presented` - présentée
   * * `published` - publiée dans les actes
   * * `withdrawn` - retirée
   */
  status: (SubmissionStatus | BlankEnum);
  submission_id: number | null;
  title: string;
}
