/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DaySlot } from '../models/day-slot';

/**
 * Session du programme publié, pour l'émargement (K7) et « présentée » (K8).
 */
export interface DaySession {

  /**
   * Présents pointés à l'entrée.
   */
  attendance: number;

  /**
   * Le compte connecté préside la session.
   */
  chaired: boolean;
  chairs: Array<string>;
  ends_at: string;
  id: number;
  room: string;
  slots: Array<DaySlot>;
  starts_at: string;
  title_en: string;
  title_fr: string;
}
