/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DecisionOutcome } from '../models/decision-outcome';
export interface DecisionBatchItemRequest {

  /**
   * Code du format attribué ; par défaut, le type de la soumission (acceptée).
   */
  assigned_type?: string | null;
  comment_to_authors?: string;
  outcome: DecisionOutcome;
  submission: number;
}
