/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `accepted` - acceptée
 * * `accepted_minor` - acceptée sous réserve de corrections
 * * `waitlist` - liste d'attente
 * * `rejected` - rejetée
 */
export type DecisionOutcome = 'accepted' | 'accepted_minor' | 'waitlist' | 'rejected';

