/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeclarationState {

  /**
   * Acceptée dans la version courante du texte.
   */
  accepted: boolean;
  code: string;
  text_version: string;
}
