/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `registration` - inscription seule
 * * `all` - inscription et options
 */
export type DiscountScope = 'registration' | 'all';

