/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DiscountScope } from './discount-scope';

/**
 * Each possible value of `DiscountScope`
 */
export const DISCOUNT_SCOPE: DiscountScope[] = [
  'registration',
  'all'
];