/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DiscountKind } from './discount-kind';

/**
 * Each possible value of `DiscountKind`
 */
export const DISCOUNT_KIND: DiscountKind[] = [
  'percent',
  'amount'
];