/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `invoice` - facture
 * * `credit_note` - avoir
 * * `proforma` - pro forma
 */
export type DocumentKind = 'invoice' | 'credit_note' | 'proforma';

