/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Currency } from '../models/currency';
import { DocumentKind } from '../models/document-kind';

/**
 * Pièce de facturation de l'inscription (le PDF se télécharge à part).
 */
export interface DocumentRef {
  amount: string;
  currency: Currency;
  id: number;
  issued_at: string;
  kind: DocumentKind;
  number: string;
}
