/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubmissionStatus } from '../models/submission-status';
export interface Duplicate {
  id: number;
  reference: string | null;
  status: SubmissionStatus;
  title: string;
}
