/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EditionStatus } from './edition-status';

/**
 * Each possible value of `EditionStatus`
 */
export const EDITION_STATUS: EditionStatus[] = [
  'draft',
  'published',
  'archived'
];