/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { OcFunction } from '../models/oc-function';
import { Role } from '../models/role';
export interface EditionRole {
  oc_function: (OcFunction | BlankEnum);
  role: Role;
}
