/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EditionStatus } from '../models/edition-status';

/**
 * RG-19 : réglages gelés (lecture) et motif d'un changement forcé par un ADMIN.
 */
export interface Edition {
  archived_at: string | null;
  city?: string;
  code: string;
  country?: string;
  end_date?: string | null;

  /**
   * Réglages gelés depuis la première soumission (RG-19).
   */
  frozen_fields: Array<string>;
  id: number;
  published_at: string | null;
  slug: string;
  start_date?: string | null;
  status: EditionStatus;
  theme_en?: string;
  theme_fr?: string;
  timezone?: string;
  title_en?: string;
  title_fr: string;
  venue?: string;
  year: number;
}
