/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EditionStatus } from '../models/edition-status';

/**
 * Sélecteur d'édition : champs non sensibles seulement (D3, §5.3).
 */
export interface EditionSummary {
  code: string;
  id: number;
  status: EditionStatus;
  title_en: string;
  title_fr: string;
  year: number;
}
