/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `projector` - vidéoprojecteur
 * * `microphone` - micro
 * * `sound_system` - sonorisation
 * * `computer` - ordinateur
 * * `whiteboard` - tableau
 * * `interpretation` - interprétation
 * * `recording` - enregistrement
 * * `wifi` - wifi
 */
export type Equipment = 'projector' | 'microphone' | 'sound_system' | 'computer' | 'whiteboard' | 'interpretation' | 'recording' | 'wifi';

