/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Equipment } from './equipment';

/**
 * Each possible value of `Equipment`
 */
export const EQUIPMENT: Equipment[] = [
  'projector',
  'microphone',
  'sound_system',
  'computer',
  'whiteboard',
  'interpretation',
  'recording',
  'wifi'
];