/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `validation_error` - Validation Error
 * * `bad_request` - Bad Request
 * * `not_authenticated` - Not Authenticated
 * * `permission_denied` - Permission Denied
 * * `not_found` - Not Found
 * * `throttled` - Throttled
 * * `server_error` - Server Error
 * * `parse_error` - Parse Error
 * * `method_not_allowed` - Method Not Allowed
 * * `not_acceptable` - Not Acceptable
 * * `unsupported_media_type` - Unsupported Media Type
 * * `csrf_failed` - Csrf Failed
 * * `in_use` - In Use
 */
export type ErrorCode = 'validation_error' | 'bad_request' | 'not_authenticated' | 'permission_denied' | 'not_found' | 'throttled' | 'server_error' | 'parse_error' | 'method_not_allowed' | 'not_acceptable' | 'unsupported_media_type' | 'csrf_failed' | 'in_use';

