/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewerTrack } from '../models/reviewer-track';

/**
 * Expertises du relecteur (H7) et thématiques proposées.
 */
export interface Expertise {
  available: Array<ReviewerTrack>;

  /**
   * Codes choisis.
   */
  tracks: Array<string>;
}
