/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dérogation (RG-02, F8) : échéance à l'heure de l'édition (D13), motif obligatoire.
 */
export interface ExtensionGrantRequest {
  reason: string;

  /**
   * Échéance dans le fuseau de l'édition, sans fuseau (2027-04-02T23:59).
   */
  until_local: string;
}
