/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Period } from '../models/period';
import { Zone } from '../models/zone';
export interface FeeRequest {
  amount: string;
  period: Period;
  zone: Zone;
}
