/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FilePolicy } from './file-policy';

/**
 * Each possible value of `FilePolicy`
 */
export const FILE_POLICY: FilePolicy[] = [
  'none',
  'optional',
  'required'
];