/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PortalFileKind } from '../models/portal-file-kind';
export interface FileUploadRequest {

  /**
   * Document : PDF, DOCX, ODT, ZIP ; image : PNG, JPEG, WebP.
   */
  file: Blob;
  kind: PortalFileKind;
  title_en?: string;
  title_fr?: string;
}
