/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryTotal } from '../models/category-total';
import { Currency } from '../models/currency';
import { MethodTotal } from '../models/method-total';
import { MoneyCount } from '../models/money-count';
import { RegistrationCounts } from '../models/registration-counts';

/**
 * Tableau de bord financier (J12) : encaissé, remboursé, net, impayés (commandes en
 * attente), remboursements restant dus, répartitions, pièces, points à traiter.
 */
export interface FinanceDashboard {
  by_category: Array<CategoryTotal>;
  by_method: Array<MethodTotal>;
  collected: string;
  credit_notes: MoneyCount;
  currency: Currency;
  invoices: MoneyCount;
  net: string;
  orphan_payments: number;
  outstanding: string;
  pending_invoices: number;
  refunded: string;
  refunds_due: string;
  registrations: RegistrationCounts;
  waivers: number;
}
