/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Criterion } from '../models/criterion';
export interface Grid {
  criteria: Array<Criterion>;
  id: number;

  /**
   * Utilisée par une évaluation (RG-05) : on la duplique pour la modifier.
   */
  is_locked: boolean;
  locked_at: string | null;
  name: string;
  scale_max: number;
  scale_min: number;
  submission_type: string | null;
  version: number;
}
