/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvitableRole } from '../models/invitable-role';
import { InvitationStatus } from '../models/invitation-status';
export interface InvitationLookup {

  /**
   * Vrai si le compte connecté porte déjà l'adresse invitée, vérifiée.
   */
  controls_address: boolean;
  edition_code: string;
  edition_title_en: string;
  edition_title_fr: string;
  email_masked: string;
  expires_at: string;
  inviter_name: string;
  message: string;
  oc_function: string;
  role: InvitableRole;
  status: InvitationStatus;
}
