/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `ADMIN` - administrateur de l'édition
 * * `CHAIR` - président de la conférence
 * * `SC_CHAIR` - président du comité scientifique
 * * `OC_MEMBER` - membre du comité d'organisation
 * * `SC_MEMBER` - membre du comité scientifique
 */
export type InvitableRole = 'ADMIN' | 'CHAIR' | 'SC_CHAIR' | 'OC_MEMBER' | 'SC_MEMBER';

