/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CertificateNature } from '../models/certificate-nature';
export interface IssueRequestRequest {
  nature: CertificateNature;
}
