/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Saisie à l'heure de l'édition (D13), convertie en UTC par le serveur.
 */
export interface KeyDateWriteRequest {

  /**
   * Date et heure dans le fuseau de l'édition, sans fuseau (2027-03-31T23:59).
   */
  at_local: string;
  code: string;
  is_public?: boolean;
  label_en?: string;
  label_fr?: string;
  position?: number;
}
