/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `requested` - demandée
 * * `issued` - émise
 * * `refused` - refusée
 * * `revoked` - révoquée
 */
export type LetterStatus = 'requested' | 'issued' | 'refused' | 'revoked';

