/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LineKind } from '../models/line-kind';
export interface Line {
  amount: string;
  code: string;
  kind: LineKind;
  label_en: string;
  label_fr: string;
}
