/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LineKind } from './line-kind';

/**
 * Each possible value of `LineKind`
 */
export const LINE_KIND: LineKind[] = [
  'registration',
  'option',
  'discount'
];