/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryRef } from '../models/category-ref';
import { Currency } from '../models/currency';
import { DocumentRef } from '../models/document-ref';
import { History } from '../models/history';
import { Line } from '../models/line';
import { ManagePayment } from '../models/manage-payment';
import { PaymentMethod } from '../models/payment-method';
import { Period } from '../models/period';
import { Proof } from '../models/proof';
import { RefundRef } from '../models/refund-ref';
import { Registrant } from '../models/registrant';
import { RegistrationEdition } from '../models/registration-edition';
import { RegistrationStatus } from '../models/registration-status';
import { Zone } from '../models/zone';

/**
 * Détail d'une inscription (gestion) : personne, historique, paiements complets,
 * remboursements.
 */
export interface ManageRegistration {
  billing_address: string;
  billing_name: string;
  billing_organization: string;
  category: CategoryRef;
  closed_at: string | null;
  confirmed_at: string | null;
  created_at: string;
  currency: Currency;
  documents: Array<DocumentRef>;
  due_at: string | null;
  edition: RegistrationEdition;
  has_qr: boolean;
  history: Array<History>;
  id: number;
  lines: Array<Line>;
  method: PaymentMethod;
  payments: Array<ManagePayment>;
  period: Period;
  person: Registrant;
  proof: Proof | null;
  reference: string;
  refund_due: string | null;
  refunds: Array<RefundRef>;
  status: RegistrationStatus;
  total: string;
  zone: Zone;
}
