/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderMethod } from '../models/order-method';

/**
 * Inscription saisie par le CO pour un compte existant (après la clôture : tarif
 * « sur place », J2).
 */
export interface ManageOrderRequest {
  billing_address?: string;
  billing_name?: string;
  billing_organization?: string;
  category: string;
  email: string;
  method: OrderMethod;
  options?: Array<string>;
  promo_code?: string;
}
