/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LetterStatus } from '../models/letter-status';
import { RegistrationStatus } from '../models/registration-status';

/**
 * Lettre instruite par le CO (``letters.manage``) : le numéro entier n'est que dans le
 * détail (``passport_number``), vide une fois effacé.
 */
export interface ManageLetterDetail {
  decided_by: string;
  embassy: string;
  id: number;
  issued_at: string | null;
  nationality: string;
  passport_name: string;
  passport_number: string;
  passport_number_masked: string;
  person: string;
  reference: string;
  refuse_reason: string;
  registration_id: number;
  registration_status: RegistrationStatus;
  requested_at: string;
  revoke_reason: string;
  revoked_at: string | null;
  signatory_name: string;
  status: LetterStatus;
  stay_from: string;
  stay_to: string;
  verification_url: string;
}
