/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ManualPaymentMethod } from '../models/manual-payment-method';

/**
 * Paiement reçu hors ligne (J7) : virement ou sur place, montant égal au total.
 */
export interface ManualPaymentRequest {
  amount: string;
  method: ManualPaymentMethod;
  note?: string;
  received_on: string;
  reference?: string;
}
