/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `transfer` - virement (bon de commande)
 * * `onsite` - sur place
 */
export type ManualPaymentMethod = 'transfer' | 'onsite';

