/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ManualPaymentMethod } from './manual-payment-method';

/**
 * Each possible value of `ManualPaymentMethod`
 */
export const MANUAL_PAYMENT_METHOD: ManualPaymentMethod[] = [
  'transfer',
  'onsite'
];