/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ManualRequestRequest {
  device?: string;

  /**
   * Clé de l'appareil (8 à 64 caractères [A-Za-z0-9_-]) ; rejouable.
   */
  idempotency_key?: string;

  /**
   * Référence « GC27-I00042 ».
   */
  reference: string;
}
