/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { InvitableRole } from '../models/invitable-role';
import { OcFunction } from '../models/oc-function';

/**
 * Invitation en attente adressée à une adresse vérifiée du compte.
 */
export interface MePendingInvitation {
  edition_code: string;
  edition_title_en: string;
  edition_title_fr: string;
  expires_at: string;
  oc_function: (OcFunction | BlankEnum);
  role: InvitableRole;
}
