/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Locale } from '../models/locale';
import { MeEdition } from '../models/me-edition';
import { MePendingInvitation } from '../models/me-pending-invitation';

/**
 * Compte connecté : identité, langue, éditions (rôles, capacités), invitations en
 * attente. L'état de la 2FA s'y ajoutera en L1.6.
 */
export interface Me {
  editions: Array<MeEdition>;
  email: string;
  id: number;
  locale: Locale;
  pending_invitations: Array<MePendingInvitation>;

  /**
   * Vrai tant que la version courante de la notice n'a pas été lue.
   */
  privacy_notice_pending: boolean;

  /**
   * Nom, prénom, institution et pays renseignés.
   */
  profile_complete: boolean;
}
