/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MealEstimate {
  allergies: number;
  by_diet: {
[key: string]: number;
};
  count: number;
  margin: number;
  total: number;
}
