/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `coffee_break` - pause café
 * * `lunch` - déjeuner
 * * `dinner` - dîner
 * * `cocktail` - cocktail
 */
export type MealKind = 'coffee_break' | 'lunch' | 'dinner' | 'cocktail';

