/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { OcFunction } from '../models/oc-function';
import { Role } from '../models/role';
import { RoleSource } from '../models/role-source';
import { UserRoleStatus } from '../models/user-role-status';

/**
 * Membre d'une édition, sans adresse (``members.read`` seul).
 */
export interface MemberWithEmail {
  email: string;
  granted_at: string;
  id: number;
  name: string;
  oc_function: (OcFunction | BlankEnum);
  revoked_at: string | null;
  role: Role;
  source: RoleSource;
  status: UserRoleStatus;
  user_id: number;
}
