/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MenuLocation } from './menu-location';

/**
 * Each possible value of `MenuLocation`
 */
export const MENU_LOCATION: MenuLocation[] = [
  'header',
  'footer'
];