/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Diet } from '../models/diet';
export interface MyDietaryWriteRequest {
  allergies?: string;
  consent: boolean;
  diets: Array<Diet>;
}
