/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Question } from '../models/question';
export interface MySurveyDetail {
  answered: boolean;
  closes_at: string;
  edition_code: string;
  edition_id: number;
  id: number;
  intro_en: string;
  intro_fr: string;
  is_open: boolean;
  questions: Array<Question>;
  session_title: string;
  title_en: string;
  title_fr: string;
}
