/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MySurvey {
  answered: boolean;
  closes_at: string;
  edition_code: string;
  edition_id: number;
  id: number;
  is_open: boolean;
  session_title: string;
  title_en: string;
  title_fr: string;
}
