/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { Equipment } from '../models/equipment';
import { TravelMeans } from '../models/travel-means';
import { VisitStatus } from '../models/visit-status';

/**
 * « Ma venue » : la note interne du CO n'y figure jamais (sérialiseur par rôle).
 */
export interface MyVisit {
  accommodation_needed: boolean;
  arrival_local: string | null;
  arrival_means: (TravelMeans | BlankEnum);
  arrival_reference: string;
  check_in: string | null;
  check_out: string | null;
  departure_local: string | null;
  departure_means: (TravelMeans | BlankEnum);
  departure_reference: string;
  edition_code: string;
  edition_id: number;
  hotel: string;
  speaker_note: string;
  status: VisitStatus;
  technical_needs: Array<Equipment>;
  technical_note: string;
  timezone: string;
  transfer_needed: boolean;
}
