/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationKind } from './notification-kind';

/**
 * Each possible value of `NotificationKind`
 */
export const NOTIFICATION_KIND: NotificationKind[] = [
  'submission_received',
  'submission_withdrawn',
  'coauthor_added',
  'extension_granted',
  'draft_reminder',
  'screening_rejected',
  'decision_published',
  'final_version_received',
  'task_assigned'
];