/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Auteurs d'une édition **sans** double aveugle (H9, Q3) : noms et affiliations, jamais
 * les adresses. Volontairement hors des sérialiseurs relecteur (RG-04 ne s'applique pas) ;
 * servi par la seule route « reviewer-assignments-authors », qui répond 404 en double
 * aveugle.
 */
export interface OpenReviewAuthor {
  country: string;
  first_name: string;
  institution: string;
  last_name: string;
  position: number;
}
