/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `online` - paiement en ligne
 * * `transfer` - virement (bon de commande)
 * * `onsite` - sur place
 */
export type OrderMethod = 'online' | 'transfer' | 'onsite';

