/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderMethod } from './order-method';

/**
 * Each possible value of `OrderMethod`
 */
export const ORDER_METHOD: OrderMethod[] = [
  'online',
  'transfer',
  'onsite'
];