/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubmissionManage } from '../models/submission-manage';
export interface PaginatedSubmissionManageList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<SubmissionManage>;
}
