/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CertificateOverview } from '../models/certificate-overview';
export interface PaginatedCertificateOverviewList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<CertificateOverview>;
}
