/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentTemplate } from '../models/document-template';
export interface PaginatedDocumentTemplateList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<DocumentTemplate>;
}
