/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Signatory } from '../models/signatory';
export interface PaginatedSignatoryList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Signatory>;
}
