/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BillingDocument } from '../models/billing-document';
export interface PaginatedBillingDocumentList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<BillingDocument>;
}
