/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Certificate } from '../models/certificate';
export interface PaginatedCertificateList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Certificate>;
}
