/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PassageRole } from './passage-role';

/**
 * Each possible value of `PassageRole`
 */
export const PASSAGE_ROLE: PassageRole[] = [
  'presenter',
  'speaker',
  'chair',
  'discussant',
  'moderator',
  'panelist'
];