/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MealKind } from '../models/meal-kind';
export interface PatchedMealWriteRequest {
  day?: string;
  include_committees?: boolean;
  include_registered?: boolean;
  include_speakers?: boolean;
  include_volunteers?: boolean;
  kind?: MealKind;
  label_en?: string;
  label_fr?: string;
  margin_percent?: number;
  option_code?: string;
  position?: number;
}
