/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Écriture partielle (sauvegarde automatique) : valeurs incomplètes admises.
 */
export interface PatchedSubmissionWriteRequest {
  abstract?: string;

  /**
   * Code → accepté ; la version courante du texte est enregistrée.
   */
  declarations?: {
[key: string]: boolean;
};
  keywords?: Array<string>;
  language?: string;

  /**
   * Code du type de communication (édition de la soumission).
   */
  submission_type?: string | null;
  title?: string;

  /**
   * Code de la thématique (édition de la soumission).
   */
  track?: string | null;
}
