/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PatchedAssignmentUpdateRequest {

  /**
   * Nouvelle échéance, à l'heure de l'édition.
   */
  due_local?: string;
}
