/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * RG-19 : réglages gelés (lecture) et motif d'un changement forcé par un ADMIN.
 */
export interface PatchedEditionRequest {
  city?: string;
  code?: string;
  country?: string;
  end_date?: string | null;

  /**
   * Motif, obligatoire pour qu'un ADMIN change un réglage gelé (RG-19).
   */
  reason?: string;
  slug?: string;
  start_date?: string | null;
  theme_en?: string;
  theme_fr?: string;
  timezone?: string;
  title_en?: string;
  title_fr?: string;
  venue?: string;
  year?: number;
}
