/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * RG-19 : réglages gelés (lecture) et motif d'un changement forcé par un ADMIN.
 */
export interface PatchedConfidentialityRequest {
  double_blind?: boolean;

  /**
   * Motif, obligatoire pour qu'un ADMIN change un réglage gelé (RG-19).
   */
  reason?: string;
  reviewers_per_submission?: number;
}
