/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Double aveugle et nombre de relecteurs (gestion, §6.1).
 */
export interface PatchedConfidentialityRequest {
  double_blind?: boolean;

  /**
   * Motif, obligatoire pour qu'un ADMIN change un réglage gelé (RG-19).
   */
  reason?: string;
  reviewers_per_submission?: number;
}
