/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Durée ; déplacement (``session``, ``position``) ; titres et intervenant d'un élément
 * libre.
 */
export interface PatchedSlotUpdateRequest {
  duration_min?: number;
  position?: number;
  session?: number;
  speaker?: number | null;
  title_en?: string;
  title_fr?: string;
}
