/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Currency } from '../models/currency';

/**
 * Paramètres des inscriptions (J2, J5, J9) : lecture ``registrations.read``, écriture
 * ``pricing.write``. Date limite d'annulation saisie à l'heure de l'édition
 * (``cancellation_deadline_local``, D13), convertie en UTC par le serveur.
 */
export interface PatchedRegistrationSettingsRequest {

  /**
   * Date limite d'annulation, à l'heure de l'édition, sans fuseau.
   */
  cancellation_deadline_local?: string | null;
  currency?: Currency;
  local_countries?: Array<string>;
  online_deadline_hours?: number;
  online_enabled?: boolean;
  onsite_enabled?: boolean;
  refund_percent_after?: number;
  refund_percent_before?: number;
  transfer_deadline_days?: number;
  transfer_enabled?: boolean;
}
