/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CriterionWriteRequest } from '../models/criterion-write-request';
export interface PatchedGridUpdateRequest {

  /**
   * Liste complète et ordonnée (RG-05 : somme 100).
   */
  criteria?: Array<CriterionWriteRequest>;
  name?: string;
  scale_max?: number;
  scale_min?: number;
}
