/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentStatus } from './payment-status';

/**
 * Each possible value of `PaymentStatus`
 */
export const PAYMENT_STATUS: PaymentStatus[] = [
  'initiated',
  'pending',
  'succeeded',
  'failed',
  'cancelled'
];