/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentProvider } from './payment-provider';

/**
 * Each possible value of `PaymentProvider`
 */
export const PAYMENT_PROVIDER: PaymentProvider[] = [
  'manual',
  'fake',
  'cinetpay'
];