/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `online` - paiement en ligne
 * * `transfer` - virement (bon de commande)
 * * `onsite` - sur place
 * * `free` - aucun paiement (montant nul)
 * * `waiver` - gratuité accordée
 */
export type PaymentMethod = 'online' | 'transfer' | 'onsite' | 'free' | 'waiver';

