/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlacedSection } from '../models/placed-section';
export interface Placement {
  position: number;
  section: PlacedSection;
}
