/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PortalFileKind } from './portal-file-kind';

/**
 * Each possible value of `PortalFileKind`
 */
export const PORTAL_FILE_KIND: PortalFileKind[] = [
  'document',
  'image'
];