/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * I5 (plan L5) : présentateurs désignés (positions des auteurs) et date de confirmation.
 */
export interface Presentation {
  confirmed_at: string;
  presenters: Array<number>;
}
