/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `` - aucun
 * * `dr` - Dr
 * * `pr` - Pr
 * * `mr` - M.
 * * `ms` - Mme
 */
export type ProfileTitle = 'dr' | 'pr' | 'mr' | 'ms';

