/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { ProfileTitle } from '../models/profile-title';
export interface Profile {

  /**
   * Texte brut.
   */
  bio?: string;

  /**
   * Code ISO 3166-1 alpha-2 (« CI », « FR »...), majuscules ou minuscules.
   */
  country?: string;
  department?: string;
  first_name?: string;
  institution?: string;
  is_complete: boolean;
  last_name?: string;
  linkedin_url?: string;

  /**
   * Forme 0000-0000-0000-000X, clé de contrôle vérifiée.
   */
  orcid?: string;

  /**
   * Adresse de la photo (publique seulement avec le consentement « photo »).
   */
  photo_url: string | null;
  scholar_url?: string;
  title?: (ProfileTitle | BlankEnum);
  website?: string;
}
