/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProgramConflictKind } from '../models/program-conflict-kind';
export interface ProgramConflict {
  kind: ProgramConflictKind;

  /**
   * Dépassement en minutes (RG-13).
   */
  minutes: number;

  /**
   * Nom de la personne (conflit de personne) ou des présentateurs (RG-11).
   */
  person: string;
  sessions: Array<number>;
  slots: Array<number>;
}
