/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `room` - room
 * * `person` - person
 * * `overflow` - overflow
 */
export type ProgramConflictKind = 'room' | 'person' | 'overflow';

