/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProgramConflictKind } from './program-conflict-kind';

/**
 * Each possible value of `ProgramConflictKind`
 */
export const PROGRAM_CONFLICT_KIND: ProgramConflictKind[] = [
  'room',
  'person',
  'overflow',
  'registration'
];