/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DiscountKind } from '../models/discount-kind';
import { DiscountScope } from '../models/discount-scope';

/**
 * Code promo (gestion) : utilisations réservées (commandes en attente) et consommées
 * (inscriptions confirmées).
 */
export interface PromoCode {
  categories?: Array<string>;
  code: string;
  consumed_uses: number;
  id: number;
  is_active?: boolean;
  kind: DiscountKind;
  max_uses?: number | null;
  reserved_uses: number;
  scope?: DiscountScope;
  valid_until?: string | null;
  value: string;
}
