/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicProgramDaySummary } from '../models/public-program-day-summary';
export interface PublicProgram {
  days: Array<PublicProgramDaySummary>;
  edition: string;
  published_at: string;
  timezone: string;
  version: number;
}
