/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicMenuItem {
  href_en: string;
  href_fr: string;
  label_en: string;
  label_fr: string;
  new_tab: boolean;

  /**
   * Slug de la page visée, sinon null.
   */
  page: string | null;
}
