/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicFileKind } from '../models/public-file-kind';

/**
 * Gestion des fichiers de l'édition (documents et images).
 */
export interface PublicFile {
  content_type: string;
  created_at: string;
  extension: string;
  height: number | null;
  id: number;
  kind: PublicFileKind;
  original_name: string;
  position?: number;

  /**
   * Aperçu dans la gestion (authentifié), publié ou non.
   */
  preview_url: string;
  published?: boolean;
  size: number;
  title_en?: string;
  title_fr?: string;
  url: string;
  uses: Array<string>;
  uuid: string;
  width: number | null;
}
