/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicPage } from '../models/public-page';
import { PublicSection } from '../models/public-section';
export interface PublicComposition {
  page: PublicPage;
  sections: Array<PublicSection>;
}
