/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicCommittee } from '../models/public-committee';
export interface PublicCommittees {
  organizing: PublicCommittee;
  scientific: PublicCommittee;
}
