/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicSponsorCard } from '../models/public-sponsor-card';
import { PublicSponsorLevel } from '../models/public-sponsor-level';
export interface PublicSponsors {
  levels: Array<PublicSponsorLevel>;
  others: Array<PublicSponsorCard>;
}
