/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicProgramChair } from '../models/public-program-chair';
import { PublicProgramRoom } from '../models/public-program-room';
import { PublicProgramSlot } from '../models/public-program-slot';
import { PublicProgramTrack } from '../models/public-program-track';
import { SessionKind } from '../models/session-kind';
export interface PublicSession {
  chairs: Array<PublicProgramChair>;
  description_en: string;
  description_fr: string;
  ends_at: string;
  id: number;
  kind: SessionKind;
  room: PublicProgramRoom | null;
  slots: Array<PublicProgramSlot>;
  starts_at: string;
  title_en: string;
  title_fr: string;
  track: PublicProgramTrack | null;
}
