/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicSponsorCard {
  description_en: string;
  description_fr: string;
  logo_height: number | null;
  logo_url: string;
  logo_width: number | null;
  name: string;
  website: string;
}
