/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Currency } from '../models/currency';
import { PaymentMethod } from '../models/payment-method';
import { PublicCategory } from '../models/public-category';
import { PublicOption } from '../models/public-option';

/**
 * Page publique « Inscription » (J13), lue au build du portail : catégories et tarifs,
 * options, dates clés (UTC), moyens de paiement proposés, pays « locaux ». Ni quota
 * restant ni donnée personnelle.
 */
export interface PublicRegistration {
  categories: Array<PublicCategory>;
  closes_at: string | null;
  currency: Currency;
  early_bird_end: string | null;
  local_countries: Array<string>;
  methods: Array<PaymentMethod>;
  opens_at: string | null;
  options: Array<PublicOption>;
  timezone: string;
}
