/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicKeyDate } from '../models/public-key-date';
import { PublicSubmissionType } from '../models/public-submission-type';
import { PublicTrack } from '../models/public-track';

/**
 * Édition courante publiée (§9.3) : tracks et types actifs, dates publiques seulement.
 */
export interface PublicEdition {
  city: string;
  code: string;
  country: string;
  end_date: string | null;
  key_dates: Array<PublicKeyDate>;
  slug: string;
  start_date: string | null;
  submission_types: Array<PublicSubmissionType>;
  theme_en: string;
  theme_fr: string;
  timezone: string;
  title_en: string;
  title_fr: string;
  tracks: Array<PublicTrack>;
  venue: string;
  year: number;
}
