/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicProgramSessionSummary } from '../models/public-program-session-summary';
export interface PublicProgramDaySummary {
  date: string;
  sessions: Array<PublicProgramSessionSummary>;
}
