/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicFileKind } from './public-file-kind';

/**
 * Each possible value of `PublicFileKind`
 */
export const PUBLIC_FILE_KIND: PublicFileKind[] = [
  'document',
  'image',
  'photo',
  'logo'
];