/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicSubmissionType {
  abstract_max_words: number;
  code: string;
  default_duration_min: number | null;
  description_en: string;
  description_fr: string;
  label_en: string;
  label_fr: string;
}
