/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicProgramAuthor } from '../models/public-program-author';
import { PublicProgramSpeaker } from '../models/public-program-speaker';
import { PublicProgramType } from '../models/public-program-type';
export interface PublicProgramSlot {
  authors: Array<PublicProgramAuthor>;
  duration_min: number;
  ends_at: string;
  id: number;
  reference: string | null;
  speaker: PublicProgramSpeaker | null;
  starts_at: string;
  title: string;
  title_en: string;
  type: PublicProgramType | null;
}
