/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicTrack {
  code: string;
  description_en: string;
  description_fr: string;
  name_en: string;
  name_fr: string;
}
