/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicEdition } from '../models/public-edition';
export interface PublicSite {
  committees: {
[key: string]: Array<{
[key: string]: any;
}>;
};
  documents: Array<{
[key: string]: any;
}>;
  edition: PublicEdition;
}
