/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicSpeakerTalk } from '../models/public-speaker-talk';
export interface PublicSpeakerProfile {
  bio: string;
  institution: string;
  name: string;
  photo_url: string | null;
  talks: Array<PublicSpeakerTalk>;
}
