/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Fichier public tel que le voient les pages : adresse, dimensions, titre.
 */
export interface PublicFileRef {
  content_type: string;
  extension: string;
  height: number | null;
  size: number;
  title_en: string;
  title_fr: string;
  url: string;
  uuid: string;
  width: number | null;
}
