/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicOption {
  categories: Array<string>;
  code: string;
  description_en: string;
  description_fr: string;
  label_en: string;
  label_fr: string;

  /**
   * Places limitées (quota).
   */
  limited: boolean;
  price_international: string;
  price_local: string;
}
