/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Lecture : ``at`` (UTC) et ``at_local`` (heure de l'édition, sans fuseau).
 */
export interface PublicKeyDate {
  at: string;
  at_local: string;
  code: string;
  label_en: string;
  label_fr: string;
}
