/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicSpeakerTalk {
  ends_at: string;
  room: string | null;
  session_id: number;
  session_title_en: string;
  session_title_fr: string;
  starts_at: string;
  title_en: string;
  title_fr: string;
}
