/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicationStatus {
  last_published_at: string | null;
  pending_changes: number;
  pending_since: string | null;
  release: string;
}
