/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicCommitteeMember } from '../models/public-committee-member';
export interface PublicCommittee {
  members: Array<PublicCommitteeMember>;

  /**
   * Membres sans consentement à l'annuaire.
   */
  others: number;
}
