/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuestionKind } from './question-kind';

/**
 * Each possible value of `QuestionKind`
 */
export const QUESTION_KIND: QuestionKind[] = [
  'rating',
  'single',
  'multiple',
  'text'
];