/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Choice } from '../models/choice';
import { QuestionKind } from '../models/question-kind';
export interface Question {
  choices: Array<Choice>;
  id: number;
  kind: QuestionKind;
  label_en: string;
  label_fr: string;
  position: number;
  required: boolean;
}
