/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `rating` - note de 1 à 5
 * * `single` - choix unique
 * * `multiple` - choix multiples
 * * `text` - texte libre
 */
export type QuestionKind = 'rating' | 'single' | 'multiple' | 'text';

