/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RankingRow } from '../models/ranking-row';
import { Simulation } from '../models/simulation';
export interface Ranking {
  rows: Array<RankingRow>;
  simulation: Simulation | null;
}
