/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `accept` - accepter
 * * `accept_minor` - accepter avec corrections
 * * `reject` - rejeter
 * * `discuss` - discuter
 */
export type Recommendation = 'accept' | 'accept_minor' | 'reject' | 'discuss';

