/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Remboursement fait hors plateforme (J9) ; l'avoir est émis sur la facture.
 */
export interface RefundRequest {
  amount: string;
  method: string;
  reference?: string;
  refunded_on: string;
}
