/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RefundRef {
  amount: string;
  credit_note: string | null;
  id: number;
  method: string;
  reference: string;
  refunded_on: string;
}
