/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationEdition {
  code: string;
  id: number;
  timezone: string;
  title_en: string;
  title_fr: string;
}
