/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DivergentSubmission } from '../models/divergent-submission';
import { ReviewerProgress } from '../models/reviewer-progress';
import { TrackProgress } from '../models/track-progress';

/**
 * Suivi de l'évaluation (plan L4 §4) : par relecteur, par thématique, divergences.
 */
export interface ReviewProgress {
  divergent: Array<DivergentSubmission>;
  reviewers: Array<ReviewerProgress>;
  threshold: string;
  tracks: Array<TrackProgress>;
}
