/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubmissionStatus } from '../models/submission-status';

/**
 * Ligne du suivi de l'évaluation : compteurs annotés par la vue.
 */
export interface ReviewSubmission {

  /**
   * Affectations actives.
   */
  assignment_count: number;
  id: number;
  language: string;

  /**
   * Affectations actives en retard.
   */
  late_count: number;
  reference: string | null;

  /**
   * Relecteurs requis (édition).
   */
  required: number;

  /**
   * Évaluations envoyées (actives).
   */
  review_count: number;
  status: SubmissionStatus;
  submission_type: string | null;
  submitted_at: string | null;
  title: string;
  track: string | null;
}
