/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Person } from '../models/person';
import { Recommendation } from '../models/recommendation';

/**
 * Évaluation envoyée, avec le nom du relecteur (H11 : visible du président et du Chair).
 */
export interface ReviewManage {
  assignment_id: number;
  comment_to_authors: string;
  comment_to_committee: string;
  confidence: number | null;
  ethics_flag: boolean;
  id: number;
  plagiarism_flag: boolean;
  pseudonym_rank: number;
  recommendation: Recommendation;
  reviewer: Person;
  scores: {
[key: string]: string;
};
  submitted_at: string | null;
  suggested_type: string | null;
  version: number;
  weighted_score: string | null;
}
