/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { Recommendation } from '../models/recommendation';

/**
 * Copie de travail envoyée par le relecteur ; la note pondérée est calculée par le
 * serveur (H4), jamais lue ici.
 */
export interface ReviewWriteRequest {
  comment_to_authors?: string;
  comment_to_committee?: string;
  confidence?: number | null;
  ethics_flag?: boolean;
  plagiarism_flag?: boolean;
  recommendation?: (Recommendation | BlankEnum);
  scores?: {
[key: string]: string | null;
};
  suggested_type?: string | null;
}
