/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewerCriterion } from '../models/reviewer-criterion';

/**
 * Marque un sérialiseur servi à un relecteur (liste blanche, contrôlée par le méta-test).
 *
 * ``reviewer_computed`` : champs calculés autorisés, nom → justification. Un
 * ``SerializerMethodField`` absent de ce dictionnaire est refusé : ce qu'il renvoie
 * échappe au contrôle des champs, seul le test de fuite le verrait.
 */
export interface ReviewerGrid {
  criteria: Array<ReviewerCriterion>;
  id: number;
  name: string;
  scale_max?: number;
  scale_min?: number;
  version?: number;
}
