/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewerTrack } from '../models/reviewer-track';
import { ReviewerType } from '../models/reviewer-type';
import { SubmissionStatus } from '../models/submission-status';

/**
 * Marque un sérialiseur servi à un relecteur (liste blanche, contrôlée par le méta-test).
 *
 * ``reviewer_computed`` : champs calculés autorisés, nom → justification. Un
 * ``SerializerMethodField`` absent de ce dictionnaire est refusé : ce qu'il renvoie
 * échappe au contrôle des champs, seul le test de fuite le verrait.
 */
export interface ReviewerSubmission {
  abstract?: string;
  has_file: boolean;
  id: number;
  keywords?: any;
  language?: string;
  reference?: string | null;
  status?: SubmissionStatus;
  submission_type: ReviewerType | null;
  title?: string;
  track: ReviewerTrack | null;
}
