/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DiscussionMessageReviewer } from '../models/discussion-message-reviewer';
import { PeerReview } from '../models/peer-review';

/**
 * RG-08 : évaluations envoyées (pseudonymes) et messages de la discussion.
 */
export interface ReviewerDiscussion {
  final_score: string | null;
  messages: Array<DiscussionMessageReviewer>;
  opened_at: string;
  reviews: Array<PeerReview>;
  spread: string;
}
