/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from './role';

/**
 * Each possible value of `Role`
 */
export const ROLE: Role[] = [
  'ADMIN',
  'CHAIR',
  'OC_MEMBER',
  'SC_CHAIR',
  'SC_MEMBER',
  'AUTHOR',
  'SPEAKER',
  'SESSION_CHAIR',
  'ATTENDEE',
  'SPONSOR',
  'VOLUNTEER'
];