/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `ADMIN` - administrateur de l'édition
 * * `CHAIR` - président de la conférence
 * * `OC_MEMBER` - membre du comité d'organisation
 * * `SC_CHAIR` - président du comité scientifique
 * * `SC_MEMBER` - membre du comité scientifique
 * * `AUTHOR` - auteur
 * * `SPEAKER` - intervenant
 * * `SESSION_CHAIR` - président de session
 * * `ATTENDEE` - participant
 * * `SPONSOR` - partenaire
 * * `VOLUNTEER` - bénévole
 * * `SIGNATORY` - signataire
 */
export type Role = 'ADMIN' | 'CHAIR' | 'OC_MEMBER' | 'SC_CHAIR' | 'SC_MEMBER' | 'AUTHOR' | 'SPEAKER' | 'SESSION_CHAIR' | 'ATTENDEE' | 'SPONSOR' | 'VOLUNTEER' | 'SIGNATORY';

