/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScanRequestRequest {
  device?: string;

  /**
   * Clé de l'appareil (8 à 64 caractères [A-Za-z0-9_-]) ; rejouable.
   */
  idempotency_key?: string;

  /**
   * Texte lu dans le QR du badge.
   */
  token: string;
}
