/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Communication placée ou à programmer : présentateurs **nommés**, sans adresse.
 */
export interface ScheduledSubmission {

  /**
   * Présentateurs désignés par l'auteur (I5).
   */
  confirmed: boolean;
  default_duration_min: number;
  id: number;

  /**
   * Un présentateur au moins est inscrit (RG-11) ; nul sans les inscriptions.
   */
  presenter_registered: boolean | null;
  presenters: Array<string>;
  reference: string | null;
  status: string;
  submission_type: string | null;
  title: string;
  track: string | null;
}
