/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageRef } from '../models/page-ref';
import { SectionType } from '../models/section-type';

/**
 * Section avec les pages qui la portent (« posée sur »).
 */
export interface Section {
  body_en?: string;
  body_fr?: string;
  code: string;
  config?: any;
  cta2_label_en?: string;
  cta2_label_fr?: string;
  cta2_url?: string;
  cta_label_en?: string;
  cta_label_fr?: string;
  cta_url?: string;
  id: number;
  is_data: boolean;
  pages: Array<PageRef>;
  published?: boolean;
  section_type: SectionType;
  subtitle_en?: string;
  subtitle_fr?: string;
  title_en?: string;
  title_fr?: string;
  updated_at: string;
}
