/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `rich_text` - texte riche
 * * `cta_banner` - bandeau d'appel à l'action
 * * `image_text` - image et texte
 * * `edition_hero` - en-tête de l'édition
 * * `key_dates` - dates clés
 * * `tracks` - thématiques
 * * `submission_types` - types de communication
 * * `documents` - documents
 * * `committee` - comité
 */
export type SectionType = 'rich_text' | 'cta_banner' | 'image_text' | 'edition_hero' | 'key_dates' | 'tracks' | 'submission_types' | 'documents' | 'committee';

