/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendingStats {
  cancelled: number;
  delivered: number;
  emails: number;
  failed: number;
  queued: number;
  recipients: number;
  remaining_hours: number;
  sent: number;
}
