/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SessionRoleKind } from './session-role-kind';

/**
 * Each possible value of `SessionRoleKind`
 */
export const SESSION_ROLE_KIND: SessionRoleKind[] = [
  'chair',
  'discussant',
  'moderator',
  'panelist'
];