/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SessionKind } from './session-kind';

/**
 * Each possible value of `SessionKind`
 */
export const SESSION_KIND: SessionKind[] = [
  'opening',
  'keynote',
  'parallel',
  'poster',
  'workshop',
  'tutorial',
  'round_table',
  'assembly',
  'break',
  'meal',
  'social',
  'closing'
];