/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SessionKind } from '../models/session-kind';
import { SessionRole } from '../models/session-role';
import { Slot } from '../models/slot';
export interface Session {
  description_en: string;
  description_fr: string;
  ends_at: string;

  /**
   * Fin à l'heure de l'édition, sans fuseau.
   */
  ends_local: string;
  id: number;
  instructions: string;
  kind: SessionKind;
  roles: Array<SessionRole>;
  room: number | null;
  slots: Array<Slot>;
  starts_at: string;

  /**
   * Début à l'heure de l'édition, sans fuseau.
   */
  starts_local: string;
  title_en: string;
  title_fr: string;

  /**
   * Code de la thématique.
   */
  track: string | null;
}
