/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SessionRoleKind } from '../models/session-role-kind';
export interface SessionRoleWriteRequest {
  role: SessionRoleKind;
  user: number;
}
