/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShiftWriteRequest {
  ends_local?: string;
  instructions?: string;
  needed?: number;
  place?: string;
  starts_local?: string;
  title_en?: string;
  title_fr?: string;
}
