/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskPerson } from '../models/task-person';
export interface Shift {
  ends_at: string;
  ends_local: string;
  id: number;
  instructions: string;
  missing: number;
  needed: number;
  place: string;
  starts_at: string;
  starts_local: string;
  title_en: string;
  title_fr: string;
  volunteers: Array<TaskPerson>;
}
