/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SkippedReason } from '../models/skipped-reason';
export interface SkippedInvitation {

  /**
   * Adresse masquée.
   */
  email: string;
  reason: SkippedReason;
}
