/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SkippedReason } from './skipped-reason';

/**
 * Each possible value of `SkippedReason`
 */
export const SKIPPED_REASON: SkippedReason[] = [
  'already_pending',
  'already_member'
];