/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Une communication (``submission``) **ou** un élément libre (``title_fr``).
 */
export interface SlotCreateRequest {
  duration_min?: number;
  position?: number;
  speaker?: number | null;
  submission?: number;
  title_en?: string;
  title_fr?: string;
}
