/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SponsorLogo } from '../models/sponsor-logo';
import { SponsorStatus } from '../models/sponsor-status';
export interface Sponsor {
  agreed_amount: string | null;
  benefits_delivered: number;
  benefits_due: number;
  id: number;
  level: number | null;
  logo: SponsorLogo | null;
  name: string;
  position: number;
  published: boolean;
  received_amount: string | null;
  received_on: string | null;
  status: SponsorStatus;
}
