/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SponsorStatus } from './sponsor-status';

/**
 * Each possible value of `SponsorStatus`
 */
export const SPONSOR_STATUS: SponsorStatus[] = [
  'prospect',
  'agreed',
  'received',
  'declined'
];