/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SponsorLogo {
  height: number | null;

  /**
   * Aperçu dans la gestion (authentifié), partenaire publié ou non.
   */
  preview_url: string;
  url: string;
  width: number | null;
}
