/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SponsorStatus } from '../models/sponsor-status';
export interface SponsorWriteRequest {
  agreed_amount?: string | null;
  contact_email?: string;
  contact_name?: string;
  contact_phone?: string;
  description_en?: string;
  description_fr?: string;
  level?: number | null;
  name?: string;
  note?: string;
  position?: number;
  published?: boolean;
  received_amount?: string | null;
  received_on?: string | null;
  status?: SponsorStatus;
  website?: string;
}
