/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Sponsor } from '../models/sponsor';
import { SponsorTotals } from '../models/sponsor-totals';
export interface Sponsors {
  sponsors: Array<Sponsor>;
  totals: SponsorTotals;
}
