/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatusEnum } from './status-enum';

/**
 * Each possible value of `StatusEnum`
 */
export const STATUS_ENUM: StatusEnum[] = [
  'ok',
  'degraded'
];