/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Duplicate } from '../models/duplicate';
export interface SubmissionCheck {
  complete: boolean;

  /**
   * F15 : ses autres soumissions au même titre (avertissement, non bloquant).
   */
  duplicates: Array<Duplicate>;
  missing: {
[key: string]: Array<string>;
};
}
