/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `submit` - submit
 * * `withdraw` - withdraw
 * * `final_version` - final_version
 */
export type SubmissionAction = 'submit' | 'withdraw' | 'final_version';

