/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthorDecision } from '../models/author-decision';
import { DeclarationState } from '../models/declaration-state';
import { FinalVersion } from '../models/final-version';
import { Presentation } from '../models/presentation';
import { PublishedSlot } from '../models/published-slot';
import { SubmissionAction } from '../models/submission-action';
import { SubmissionAuthor } from '../models/submission-author';
import { SubmissionFile } from '../models/submission-file';
import { SubmissionStatus } from '../models/submission-status';

/**
 * Vue de l'auteur sur **sa** soumission.
 */
export interface Submission {
  abstract: string;
  allowed_actions: Array<SubmissionAction>;
  authors: Array<SubmissionAuthor>;

  /**
   * Modifiable maintenant (état, RG-02 : appel ouvert ou dérogation).
   */
  can_edit: boolean;
  created_at: string;

  /**
   * Fin de la période de modification : dérogation en cours, sinon clôture.
   */
  deadline: string | null;

  /**
   * RG-09 : décision publiée seulement ; RG-10 : commentaires sous pseudonyme.
   */
  decision: AuthorDecision | null;
  declarations: Array<DeclarationState>;

  /**
   * Double aveugle : le PDF doit être anonyme ; ses métadonnées sont retirées.
   */
  double_blind: boolean;
  edition: number;
  edition_code: string;
  file: SubmissionFile | null;

  /**
   * Date limite de la version finale (date clé camera_ready).
   */
  final_deadline: string | null;

  /**
   * Version finale déposée (H18).
   */
  final_version: FinalVersion | null;
  id: number;
  keywords: Array<string>;
  language: string;

  /**
   * Confirmation de présentation (I5, plan L5).
   */
  presentation: Presentation | null;
  reference: string | null;
  revision: number;

  /**
   * Créneau au programme publié (plan L5 §4), pour une communication programmée.
   */
  schedule: PublishedSlot | null;
  status: SubmissionStatus;
  submission_type: string | null;
  submitted_at: string | null;
  title: string;
  track: string | null;
  updated_at: string;
  withdraw_reason: string;
  withdrawn_at: string | null;
}
