/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FilePolicy } from '../models/file-policy';
export interface SubmissionTypeRequest {
  abstract_max_words?: number;
  code: string;
  default_duration_min?: number | null;
  description_en?: string;
  description_fr?: string;
  file_policy?: FilePolicy;
  is_active?: boolean;
  label_en?: string;
  label_fr: string;
  max_file_mb?: number;
  position?: number;
}
