/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubmissionLanguage } from './submission-language';

/**
 * Each possible value of `SubmissionLanguage`
 */
export const SUBMISSION_LANGUAGE: SubmissionLanguage[] = [
  'fr',
  'en'
];