/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubmissionAuthor {
  country?: string;
  email: string;
  first_name: string;

  /**
   * Rattaché à un compte dont l'adresse vérifiée correspond (F5).
   */
  has_account: boolean;
  institution?: string;
  is_corresponding?: boolean;
  is_presenter?: boolean;
  last_name: string;
  position: number;
}
