/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubmissionStats {

  /**
   * Statut → nombre (tous les statuts).
   */
  by_status: {
[key: string]: number;
};
  drafts: number;

  /**
   * Soumissions hors brouillons.
   */
  total: number;
}
