/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubmissionStatus } from '../models/submission-status';

/**
 * Ligne de la liste de gestion : identité des auteurs (noms), sans adresse e-mail.
 */
export interface SubmissionManage {
  authors_count: number;

  /**
   * Auteurs dans l'ordre : « Prénom Nom ; Prénom Nom ».
   */
  authors_label: string;

  /**
   * Échéance de la dérogation en cours (RG-02), sinon null.
   */
  extension_until: string | null;
  id: number;
  language: string;

  /**
   * Pages du PDF courant (null : aucun).
   */
  pages: number | null;
  reference: string | null;
  status: SubmissionStatus;
  submission_type: string | null;
  submitted_at: string | null;
  title: string;
  track: string | null;
  updated_at: string;
}
