/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SurveyScope } from '../models/survey-scope';
import { SurveyStats } from '../models/survey-stats';
import { SurveyStatus } from '../models/survey-status';
export interface Survey {
  closes_local: string | null;
  id: number;
  intro_en: string;
  intro_fr: string;
  is_open: boolean;
  locked: boolean;
  opens_local: string | null;
  scope: SurveyScope;
  session: number | null;
  session_title: string;
  stats: SurveyStats;
  status: SurveyStatus;
  title_en: string;
  title_fr: string;
}
