/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SurveyScope } from './survey-scope';

/**
 * Each possible value of `SurveyScope`
 */
export const SURVEY_SCOPE: SurveyScope[] = [
  'global',
  'session'
];