/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskPriority } from './task-priority';

/**
 * Each possible value of `TaskPriority`
 */
export const TASK_PRIORITY: TaskPriority[] = [
  'low',
  'normal',
  'high'
];