/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskPerson } from '../models/task-person';
export interface TaskComment {
  author: TaskPerson | null;
  body: string;
  created_at: string;
  id: number;
}
