/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskAttachment } from '../models/task-attachment';
import { TaskComment } from '../models/task-comment';
import { TaskPerson } from '../models/task-person';
import { TaskPriority } from '../models/task-priority';
import { TaskStatus } from '../models/task-status';
export interface TaskDetail {
  archived_at: string | null;
  assignee: TaskPerson | null;
  attachment_count: number;
  attachments: Array<TaskAttachment>;
  comment_count: number;
  comments: Array<TaskComment>;
  created_at: string;
  created_by: TaskPerson | null;
  description: string;
  done_at: string | null;
  due_date: string | null;
  id: number;
  label: string;
  overdue: boolean;
  position: number;
  priority: TaskPriority;
  revision: number;
  status: TaskStatus;
  title: string;
  updated_at: string;
}
