/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskPerson } from '../models/task-person';
export interface TaskAttachment {
  created_at: string;
  id: number;
  kind: string;
  name: string;
  size: number;
  uploaded_by: TaskPerson | null;
}
