/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TemplateCustomized {
  body_en: boolean;
  body_fr: boolean;
  footer_en: boolean;
  footer_fr: boolean;
  title_en: boolean;
  title_fr: boolean;
}
