/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RevisionSummary } from '../models/revision-summary';
import { TimelineEntry } from '../models/timeline-entry';
export interface Timeline {
  history: Array<TimelineEntry>;
  revisions: Array<RevisionSummary>;
}
