/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TrackProgress {
  code: string | null;

  /**
   * Soumissions en évaluation ou évaluées.
   */
  in_review: number;

  /**
   * Soumissions évaluées (RG-07).
   */
  reviewed: number;
}
