/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `plane` - avion
 * * `train` - train
 * * `road` - route
 * * `other` - autre
 */
export type TravelMeans = 'plane' | 'train' | 'road' | 'other';

