/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRoleStatus } from './user-role-status';

/**
 * Each possible value of `UserRoleStatus`
 */
export const USER_ROLE_STATUS: UserRoleStatus[] = [
  'active',
  'revoked'
];