/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { Equipment } from '../models/equipment';
import { TravelMeans } from '../models/travel-means';
export interface VisitSpeakerWriteRequest {
  accommodation_needed?: boolean;
  arrival_local?: string | null;
  arrival_means?: (TravelMeans | BlankEnum);
  arrival_reference?: string;
  departure_local?: string | null;
  departure_means?: (TravelMeans | BlankEnum);
  departure_reference?: string;
  speaker_note?: string;
  technical_needs?: Array<Equipment>;
  technical_note?: string;
  transfer_needed?: boolean;
}
