/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `to_arrange` - à organiser
 * * `booked` - réservée
 * * `confirmed` - confirmée
 */
export type VisitStatus = 'to_arrange' | 'booked' | 'confirmed';

