/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Edition } from '../../models/edition';

export interface ManageEditionRetrieve$Params {
  edition_id: number;
}

export function manageEditionRetrieve(http: HttpClient, rootUrl: string, params: ManageEditionRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Edition>> {
  const rb = new RequestBuilder(rootUrl, manageEditionRetrieve.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Edition>;
    })
  );
}

manageEditionRetrieve.PATH = '/v1/manage/editions/{edition_id}';
