/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AnnouncementDetail } from '../../models/announcement-detail';

export interface ManageAnnouncementsRetrieve$Params {
  announcement_id: number;
  edition_id: number;
}

export function manageAnnouncementsRetrieve(http: HttpClient, rootUrl: string, params: ManageAnnouncementsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<AnnouncementDetail>> {
  const rb = new RequestBuilder(rootUrl, manageAnnouncementsRetrieve.PATH, 'get');
  if (params) {
    rb.path('announcement_id', params.announcement_id, {});
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AnnouncementDetail>;
    })
  );
}

manageAnnouncementsRetrieve.PATH = '/v1/manage/editions/{edition_id}/announcements/{announcement_id}';
