/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubmissionManageDetail } from '../../models/submission-manage-detail';

export interface ManageSubmissionExtensionRevoke$Params {
  edition_id: number;
  extension_id: number;
  submission_id: number;
}

export function manageSubmissionExtensionRevoke(http: HttpClient, rootUrl: string, params: ManageSubmissionExtensionRevoke$Params, context?: HttpContext): Observable<StrictHttpResponse<SubmissionManageDetail>> {
  const rb = new RequestBuilder(rootUrl, manageSubmissionExtensionRevoke.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('extension_id', params.extension_id, {});
    rb.path('submission_id', params.submission_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubmissionManageDetail>;
    })
  );
}

manageSubmissionExtensionRevoke.PATH = '/v1/manage/editions/{edition_id}/submissions/{submission_id}/extensions/{extension_id}/revoke';
