/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ManageRegistrationsExport$Params {

/**
 * Code de catégorie.
 */
  category?: string;
  edition_id: number;

/**
 * Moyen de paiement.
 */
  method?: string;

/**
 * Nom, adresse ou référence.
 */
  q?: string;

/**
 * Statut (en attente, confirmée…).
 */
  status?: string;
}

export function manageRegistrationsExport(http: HttpClient, rootUrl: string, params: ManageRegistrationsExport$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, manageRegistrationsExport.PATH, 'get');
  if (params) {
    rb.query('category', params.category, {});
    rb.path('edition_id', params.edition_id, {});
    rb.query('method', params.method, {});
    rb.query('q', params.q, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'text/csv', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

manageRegistrationsExport.PATH = '/v1/manage/editions/{edition_id}/registrations/export';
