/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedRoomWriteRequest } from '../../models/patched-room-write-request';
import { ProgramBoard } from '../../models/program-board';

export interface ManageProgramRoomsUpdate$Params {

/**
 * Révision du programme lue ; 412 « stale_revision » si elle a changé (I14).
 */
  'If-Match'?: number;
  edition_id: number;
  item_id: number;
      body?: PatchedRoomWriteRequest
}

export function manageProgramRoomsUpdate(http: HttpClient, rootUrl: string, params: ManageProgramRoomsUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ProgramBoard>> {
  const rb = new RequestBuilder(rootUrl, manageProgramRoomsUpdate.PATH, 'patch');
  if (params) {
    rb.header('If-Match', params['If-Match'], {});
    rb.path('edition_id', params.edition_id, {});
    rb.path('item_id', params.item_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProgramBoard>;
    })
  );
}

manageProgramRoomsUpdate.PATH = '/v1/manage/editions/{edition_id}/program/rooms/{item_id}';
