/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CheckinResult } from '../../models/checkin-result';
import { ScanRequestRequest } from '../../models/scan-request-request';

export interface ManageCheckinScan$Params {
  edition_id: number;
      body: ScanRequestRequest
}

export function manageCheckinScan(http: HttpClient, rootUrl: string, params: ManageCheckinScan$Params, context?: HttpContext): Observable<StrictHttpResponse<CheckinResult>> {
  const rb = new RequestBuilder(rootUrl, manageCheckinScan.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CheckinResult>;
    })
  );
}

manageCheckinScan.PATH = '/v1/manage/editions/{edition_id}/checkin/scan';
