/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BadgeBatches } from '../../models/badge-batches';

export interface ManageBadgesBatches$Params {

/**
 * Code de catégorie.
 */
  category?: string;
  edition_id: number;
}

export function manageBadgesBatches(http: HttpClient, rootUrl: string, params: ManageBadgesBatches$Params, context?: HttpContext): Observable<StrictHttpResponse<BadgeBatches>> {
  const rb = new RequestBuilder(rootUrl, manageBadgesBatches.PATH, 'get');
  if (params) {
    rb.query('category', params.category, {});
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BadgeBatches>;
    })
  );
}

manageBadgesBatches.PATH = '/v1/manage/editions/{edition_id}/registrations/badges/batches';
