/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedCheckinListItemList } from '../../models/paginated-checkin-list-item-list';

export interface ManageCheckinList$Params {

/**
 * Inclure les pointages annulés.
 */
  cancelled?: boolean;
  edition_id: number;

/**
 * Quel champ utiliser pour classer les résultats.
 */
  ordering?: string;

/**
 * Un numéro de page de l'ensemble des résultats.
 */
  page?: number;

/**
 * Nombre de résultats à retourner par page.
 */
  page_size?: number;

/**
 * Nom ou référence.
 */
  q?: string;
}

export function manageCheckinList(http: HttpClient, rootUrl: string, params: ManageCheckinList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedCheckinListItemList>> {
  const rb = new RequestBuilder(rootUrl, manageCheckinList.PATH, 'get');
  if (params) {
    rb.query('cancelled', params.cancelled, {});
    rb.path('edition_id', params.edition_id, {});
    rb.query('ordering', params.ordering, {});
    rb.query('page', params.page, {});
    rb.query('page_size', params.page_size, {});
    rb.query('q', params.q, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedCheckinListItemList>;
    })
  );
}

manageCheckinList.PATH = '/v1/manage/editions/{edition_id}/checkin';
