/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ManageDayAttendanceExport$Params {
  edition_id: number;
  session_id: number;
}

export function manageDayAttendanceExport(http: HttpClient, rootUrl: string, params: ManageDayAttendanceExport$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, manageDayAttendanceExport.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('session_id', params.session_id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'text/csv', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

manageDayAttendanceExport.PATH = '/v1/manage/editions/{edition_id}/day/sessions/{session_id}/attendance/export';
