/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Option } from '../../models/option';

export interface ManageRegistrationOptionsList$Params {
  edition_id: number;
}

export function manageRegistrationOptionsList(http: HttpClient, rootUrl: string, params: ManageRegistrationOptionsList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Option>>> {
  const rb = new RequestBuilder(rootUrl, manageRegistrationOptionsList.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Option>>;
    })
  );
}

manageRegistrationOptionsList.PATH = '/v1/manage/editions/{edition_id}/registrations/options';
