/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubmissionType } from '../../models/submission-type';
import { SubmissionTypeRequest } from '../../models/submission-type-request';

export interface ManageEditionsSubmissionTypesCreate$Params {
  edition_id: number;
      body: SubmissionTypeRequest
}

export function manageEditionsSubmissionTypesCreate(http: HttpClient, rootUrl: string, params: ManageEditionsSubmissionTypesCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<SubmissionType>> {
  const rb = new RequestBuilder(rootUrl, manageEditionsSubmissionTypesCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubmissionType>;
    })
  );
}

manageEditionsSubmissionTypesCreate.PATH = '/v1/manage/editions/{edition_id}/submission-types';
