/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ManageSurveysExport$Params {
  edition_id: number;
  file_format?: 'csv' | 'xlsx';
  survey_id: number;
}

export function manageSurveysExport(http: HttpClient, rootUrl: string, params: ManageSurveysExport$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, manageSurveysExport.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.query('file_format', params.file_format, {});
    rb.path('survey_id', params.survey_id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

manageSurveysExport.PATH = '/v1/manage/editions/{edition_id}/surveys/{survey_id}/export';
