/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedSectionWriteRequest } from '../../models/patched-section-write-request';
import { Section } from '../../models/section';

export interface ManageEditionsPortalSectionsPartialUpdate$Params {
  edition_id: number;
  item_id: number;
      body?: PatchedSectionWriteRequest
}

export function manageEditionsPortalSectionsPartialUpdate(http: HttpClient, rootUrl: string, params: ManageEditionsPortalSectionsPartialUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Section>> {
  const rb = new RequestBuilder(rootUrl, manageEditionsPortalSectionsPartialUpdate.PATH, 'patch');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('item_id', params.item_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Section>;
    })
  );
}

manageEditionsPortalSectionsPartialUpdate.PATH = '/v1/manage/editions/{edition_id}/portal/sections/{item_id}';
