/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuItem } from '../../models/menu-item';
import { MenuOrderRequest } from '../../models/menu-order-request';

export interface ManagePortalMenuReorder$Params {
  edition_id: number;

/**
 * Quel champ utiliser pour classer les résultats.
 */
  ordering?: string;
      body: MenuOrderRequest
}

export function managePortalMenuReorder(http: HttpClient, rootUrl: string, params: ManagePortalMenuReorder$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MenuItem>>> {
  const rb = new RequestBuilder(rootUrl, managePortalMenuReorder.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.query('ordering', params.ordering, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MenuItem>>;
    })
  );
}

managePortalMenuReorder.PATH = '/v1/manage/editions/{edition_id}/portal/menu/reorder';
