/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CertificateSettings } from '../../models/certificate-settings';
import { SigningKeyUploadRequest } from '../../models/signing-key-upload-request';

export interface ManageCertificateSigningKeyUpload$Params {
  edition_id: number;
      body: SigningKeyUploadRequest
}

export function manageCertificateSigningKeyUpload(http: HttpClient, rootUrl: string, params: ManageCertificateSigningKeyUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<CertificateSettings>> {
  const rb = new RequestBuilder(rootUrl, manageCertificateSigningKeyUpload.PATH, 'put');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CertificateSettings>;
    })
  );
}

manageCertificateSigningKeyUpload.PATH = '/v1/manage/editions/{edition_id}/certificates/settings/signing-key';
