/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SponsorLevel } from '../../models/sponsor-level';
import { SponsorLevelWriteRequest } from '../../models/sponsor-level-write-request';

export interface ManageSponsorLevelsCreate$Params {
  edition_id: number;
      body?: SponsorLevelWriteRequest
}

export function manageSponsorLevelsCreate(http: HttpClient, rootUrl: string, params: ManageSponsorLevelsCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SponsorLevel>>> {
  const rb = new RequestBuilder(rootUrl, manageSponsorLevelsCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SponsorLevel>>;
    })
  );
}

manageSponsorLevelsCreate.PATH = '/v1/manage/editions/{edition_id}/sponsor-levels';
