/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EditionSummary } from '../../models/edition-summary';

export interface ManageEditionsList$Params {

/**
 * Quel champ utiliser pour classer les résultats.
 */
  ordering?: string;
}

export function manageEditionsList(http: HttpClient, rootUrl: string, params?: ManageEditionsList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EditionSummary>>> {
  const rb = new RequestBuilder(rootUrl, manageEditionsList.PATH, 'get');
  if (params) {
    rb.query('ordering', params.ordering, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EditionSummary>>;
    })
  );
}

manageEditionsList.PATH = '/v1/manage/editions';
