/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuItem } from '../../models/menu-item';

export interface ManageEditionsPortalMenuList$Params {
  edition_id: number;
  location?: 'footer' | 'header';

/**
 * Quel champ utiliser pour classer les résultats.
 */
  ordering?: string;
}

export function manageEditionsPortalMenuList(http: HttpClient, rootUrl: string, params: ManageEditionsPortalMenuList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MenuItem>>> {
  const rb = new RequestBuilder(rootUrl, manageEditionsPortalMenuList.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.query('location', params.location, {});
    rb.query('ordering', params.ordering, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MenuItem>>;
    })
  );
}

manageEditionsPortalMenuList.PATH = '/v1/manage/editions/{edition_id}/portal/menu';
