/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LogoUploadRequest } from '../../models/logo-upload-request';
import { SponsorDetail } from '../../models/sponsor-detail';

export interface ManageSponsorsLogoUpload$Params {
  edition_id: number;
  sponsor_id: number;
      body: LogoUploadRequest
}

export function manageSponsorsLogoUpload(http: HttpClient, rootUrl: string, params: ManageSponsorsLogoUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<SponsorDetail>> {
  const rb = new RequestBuilder(rootUrl, manageSponsorsLogoUpload.PATH, 'put');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('sponsor_id', params.sponsor_id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SponsorDetail>;
    })
  );
}

manageSponsorsLogoUpload.PATH = '/v1/manage/editions/{edition_id}/sponsors/{sponsor_id}/logo';
