/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageCreateRequest } from '../../models/message-create-request';
import { SubmissionReviews } from '../../models/submission-reviews';

export interface ManageReviewSubmissionDiscussionMessage$Params {
  edition_id: number;
  submission_id: number;
      body: MessageCreateRequest
}

export function manageReviewSubmissionDiscussionMessage(http: HttpClient, rootUrl: string, params: ManageReviewSubmissionDiscussionMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<SubmissionReviews>> {
  const rb = new RequestBuilder(rootUrl, manageReviewSubmissionDiscussionMessage.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('submission_id', params.submission_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubmissionReviews>;
    })
  );
}

manageReviewSubmissionDiscussionMessage.PATH = '/v1/manage/editions/{edition_id}/review-submissions/{submission_id}/discussion/messages';
