/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportSection } from '../../models/report-section';

export interface ManageReportsRetrieve$Params {
  edition_id: number;
  section: string;
}

export function manageReportsRetrieve(http: HttpClient, rootUrl: string, params: ManageReportsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportSection>> {
  const rb = new RequestBuilder(rootUrl, manageReportsRetrieve.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('section', params.section, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReportSection>;
    })
  );
}

manageReportsRetrieve.PATH = '/v1/manage/editions/{edition_id}/reports/{section}';
