/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SponsorDetail } from '../../models/sponsor-detail';

export interface ManageSponsorsBenefitsRemove$Params {
  benefit_id: number;
  edition_id: number;
  sponsor_id: number;
}

export function manageSponsorsBenefitsRemove(http: HttpClient, rootUrl: string, params: ManageSponsorsBenefitsRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<SponsorDetail>> {
  const rb = new RequestBuilder(rootUrl, manageSponsorsBenefitsRemove.PATH, 'delete');
  if (params) {
    rb.path('benefit_id', params.benefit_id, {});
    rb.path('edition_id', params.edition_id, {});
    rb.path('sponsor_id', params.sponsor_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SponsorDetail>;
    })
  );
}

manageSponsorsBenefitsRemove.PATH = '/v1/manage/editions/{edition_id}/sponsors/{sponsor_id}/benefits/{benefit_id}';
