/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProgramBoard } from '../../models/program-board';

export interface ManageProgramBoard$Params {
  edition_id: number;
}

export function manageProgramBoard(http: HttpClient, rootUrl: string, params: ManageProgramBoard$Params, context?: HttpContext): Observable<StrictHttpResponse<ProgramBoard>> {
  const rb = new RequestBuilder(rootUrl, manageProgramBoard.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProgramBoard>;
    })
  );
}

manageProgramBoard.PATH = '/v1/manage/editions/{edition_id}/program';
