/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Poster } from '../../models/poster';
import { PosterRequest } from '../../models/poster-request';

export interface ManagePortalPosterUpdate$Params {
  edition_id: number;
      body: PosterRequest
}

export function managePortalPosterUpdate(http: HttpClient, rootUrl: string, params: ManagePortalPosterUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Poster>> {
  const rb = new RequestBuilder(rootUrl, managePortalPosterUpdate.PATH, 'put');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Poster>;
    })
  );
}

managePortalPosterUpdate.PATH = '/v1/manage/editions/{edition_id}/portal/poster';
