/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Budget } from '../../models/budget';
import { BudgetLineWriteRequest } from '../../models/budget-line-write-request';

export interface ManageBudgetLinesCreate$Params {
  edition_id: number;
      body?: BudgetLineWriteRequest
}

export function manageBudgetLinesCreate(http: HttpClient, rootUrl: string, params: ManageBudgetLinesCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Budget>> {
  const rb = new RequestBuilder(rootUrl, manageBudgetLinesCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Budget>;
    })
  );
}

manageBudgetLinesCreate.PATH = '/v1/manage/editions/{edition_id}/budget/lines';
