/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedSubmissionManageList } from '../../models/paginated-submission-manage-list';

export interface ManageSubmissionsList$Params {
  edition_id: number;
  language?: string;

/**
 * * `reference` - reference
 * * `-submitted_at` - -submitted_at
 * * `-updated_at` - -updated_at
 * * `title` - title
 */
  ordering?: '-submitted_at' | '-updated_at' | 'reference' | 'title';

/**
 * Un numéro de page de l'ensemble des résultats.
 */
  page?: number;

/**
 * Nombre de résultats à retourner par page.
 */
  page_size?: number;
  q?: string;

/**
 * * `draft` - brouillon
 * * `submitted` - soumise
 * * `screening` - vérification de recevabilité
 * * `under_review` - en cours d'évaluation
 * * `reviewed` - évaluée
 * * `accepted` - acceptée
 * * `accepted_minor` - acceptée sous réserve de corrections
 * * `waitlist` - liste d'attente
 * * `rejected` - rejetée
 * * `revision_requested` - corrections demandées
 * * `camera_ready_received` - version finale reçue
 * * `confirmed` - présentation confirmée
 * * `scheduled` - programmée
 * * `presented` - présentée
 * * `published` - publiée dans les actes
 * * `withdrawn` - retirée
 */
  status?: Array<'accepted' | 'accepted_minor' | 'camera_ready_received' | 'confirmed' | 'draft' | 'presented' | 'published' | 'rejected' | 'reviewed' | 'revision_requested' | 'scheduled' | 'screening' | 'submitted' | 'under_review' | 'waitlist' | 'withdrawn'>;
  submission_type?: string;
  track?: string;
}

export function manageSubmissionsList(http: HttpClient, rootUrl: string, params: ManageSubmissionsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedSubmissionManageList>> {
  const rb = new RequestBuilder(rootUrl, manageSubmissionsList.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.query('language', params.language, {});
    rb.query('ordering', params.ordering, {});
    rb.query('page', params.page, {});
    rb.query('page_size', params.page_size, {});
    rb.query('q', params.q, {});
    rb.query('status', params.status, {"style":"form","explode":true});
    rb.query('submission_type', params.submission_type, {});
    rb.query('track', params.track, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedSubmissionManageList>;
    })
  );
}

manageSubmissionsList.PATH = '/v1/manage/editions/{edition_id}/submissions';
