/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskDetail } from '../../models/task-detail';

export interface ManageTasksAttachmentsRemove$Params {
  attachment_id: number;
  edition_id: number;
  task_id: number;
}

export function manageTasksAttachmentsRemove(http: HttpClient, rootUrl: string, params: ManageTasksAttachmentsRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskDetail>> {
  const rb = new RequestBuilder(rootUrl, manageTasksAttachmentsRemove.PATH, 'delete');
  if (params) {
    rb.path('attachment_id', params.attachment_id, {});
    rb.path('edition_id', params.edition_id, {});
    rb.path('task_id', params.task_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskDetail>;
    })
  );
}

manageTasksAttachmentsRemove.PATH = '/v1/manage/editions/{edition_id}/tasks/{task_id}/attachments/{attachment_id}';
