/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Grid } from '../../models/grid';
import { PatchedGridUpdateRequest } from '../../models/patched-grid-update-request';

export interface ManageGridUpdate$Params {
  edition_id: number;
  grid_id: number;
      body?: PatchedGridUpdateRequest
}

export function manageGridUpdate(http: HttpClient, rootUrl: string, params: ManageGridUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Grid>> {
  const rb = new RequestBuilder(rootUrl, manageGridUpdate.PATH, 'patch');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('grid_id', params.grid_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Grid>;
    })
  );
}

manageGridUpdate.PATH = '/v1/manage/editions/{edition_id}/grids/{grid_id}';
