/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Option } from '../../models/option';
import { PatchedOptionRequest } from '../../models/patched-option-request';

export interface ManageRegistrationOptionsUpdate$Params {
  edition_id: number;
  item_id: number;
      body?: PatchedOptionRequest
}

export function manageRegistrationOptionsUpdate(http: HttpClient, rootUrl: string, params: ManageRegistrationOptionsUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Option>> {
  const rb = new RequestBuilder(rootUrl, manageRegistrationOptionsUpdate.PATH, 'patch');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('item_id', params.item_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Option>;
    })
  );
}

manageRegistrationOptionsUpdate.PATH = '/v1/manage/editions/{edition_id}/registrations/options/{item_id}';
