/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BillingProfile } from '../../models/billing-profile';

export interface ManageBillingProfileRetrieve$Params {
  edition_id: number;
}

export function manageBillingProfileRetrieve(http: HttpClient, rootUrl: string, params: ManageBillingProfileRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<BillingProfile>> {
  const rb = new RequestBuilder(rootUrl, manageBillingProfileRetrieve.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BillingProfile>;
    })
  );
}

manageBillingProfileRetrieve.PATH = '/v1/manage/editions/{edition_id}/billing/profile';
