/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Section } from '../../models/section';
import { SectionWriteRequest } from '../../models/section-write-request';

export interface ManageEditionsPortalSectionsCreate$Params {
  edition_id: number;
      body: SectionWriteRequest
}

export function manageEditionsPortalSectionsCreate(http: HttpClient, rootUrl: string, params: ManageEditionsPortalSectionsCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Section>> {
  const rb = new RequestBuilder(rootUrl, manageEditionsPortalSectionsCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Section>;
    })
  );
}

manageEditionsPortalSectionsCreate.PATH = '/v1/manage/editions/{edition_id}/portal/sections';
