/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvitationWithEmail } from '../../models/invitation-with-email';

export interface ManageInvitationResend$Params {
  edition_id: number;
  invitation_id: number;
}

export function manageInvitationResend(http: HttpClient, rootUrl: string, params: ManageInvitationResend$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationWithEmail>> {
  const rb = new RequestBuilder(rootUrl, manageInvitationResend.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('invitation_id', params.invitation_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvitationWithEmail>;
    })
  );
}

manageInvitationResend.PATH = '/v1/manage/editions/{edition_id}/invitations/{invitation_id}/resend';
