/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Meal } from '../../models/meal';
import { MealWriteRequest } from '../../models/meal-write-request';

export interface ManageMealsCreate$Params {
  edition_id: number;
      body?: MealWriteRequest
}

export function manageMealsCreate(http: HttpClient, rootUrl: string, params: ManageMealsCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Meal>>> {
  const rb = new RequestBuilder(rootUrl, manageMealsCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Meal>>;
    })
  );
}

manageMealsCreate.PATH = '/v1/manage/editions/{edition_id}/logistics/meals';
