/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Signature } from '../../models/signature';
import { SignatureImageUploadRequest } from '../../models/signature-image-upload-request';

export interface ManageSignatureImageUpload$Params {
  edition_id: number;
      body: SignatureImageUploadRequest
}

export function manageSignatureImageUpload(http: HttpClient, rootUrl: string, params: ManageSignatureImageUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<Signature>> {
  const rb = new RequestBuilder(rootUrl, manageSignatureImageUpload.PATH, 'put');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Signature>;
    })
  );
}

manageSignatureImageUpload.PATH = '/v1/manage/editions/{edition_id}/signature/image';
