/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskDetail } from '../../models/task-detail';
import { TaskWriteRequest } from '../../models/task-write-request';

export interface ManageTasksCreate$Params {
  edition_id: number;
      body?: TaskWriteRequest
}

export function manageTasksCreate(http: HttpClient, rootUrl: string, params: ManageTasksCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskDetail>> {
  const rb = new RequestBuilder(rootUrl, manageTasksCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskDetail>;
    })
  );
}

manageTasksCreate.PATH = '/v1/manage/editions/{edition_id}/tasks';
