/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AnnouncementDetail } from '../../models/announcement-detail';
import { AnnouncementWriteRequest } from '../../models/announcement-write-request';

export interface ManageAnnouncementsCreate$Params {
  edition_id: number;
      body?: AnnouncementWriteRequest
}

export function manageAnnouncementsCreate(http: HttpClient, rootUrl: string, params: ManageAnnouncementsCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<AnnouncementDetail>> {
  const rb = new RequestBuilder(rootUrl, manageAnnouncementsCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AnnouncementDetail>;
    })
  );
}

manageAnnouncementsCreate.PATH = '/v1/manage/editions/{edition_id}/announcements';
