/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignmentCreateRequest } from '../../models/assignment-create-request';
import { AssignmentManage } from '../../models/assignment-manage';

export interface ManageAssignmentCreate$Params {
  edition_id: number;
      body: AssignmentCreateRequest
}

export function manageAssignmentCreate(http: HttpClient, rootUrl: string, params: ManageAssignmentCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<AssignmentManage>> {
  const rb = new RequestBuilder(rootUrl, manageAssignmentCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AssignmentManage>;
    })
  );
}

manageAssignmentCreate.PATH = '/v1/manage/editions/{edition_id}/assignments';
