/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedPromoCodeRequest } from '../../models/patched-promo-code-request';
import { PromoCode } from '../../models/promo-code';

export interface ManageRegistrationPromoCodesUpdate$Params {
  edition_id: number;
  item_id: number;
      body?: PatchedPromoCodeRequest
}

export function manageRegistrationPromoCodesUpdate(http: HttpClient, rootUrl: string, params: ManageRegistrationPromoCodesUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<PromoCode>> {
  const rb = new RequestBuilder(rootUrl, manageRegistrationPromoCodesUpdate.PATH, 'patch');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('item_id', params.item_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PromoCode>;
    })
  );
}

manageRegistrationPromoCodesUpdate.PATH = '/v1/manage/editions/{edition_id}/registrations/promo-codes/{item_id}';
