/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuItem } from '../../models/menu-item';
import { MenuItemRequest } from '../../models/menu-item-request';

export interface ManageEditionsPortalMenuCreate$Params {
  edition_id: number;
      body: MenuItemRequest
}

export function manageEditionsPortalMenuCreate(http: HttpClient, rootUrl: string, params: ManageEditionsPortalMenuCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuItem>> {
  const rb = new RequestBuilder(rootUrl, manageEditionsPortalMenuCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MenuItem>;
    })
  );
}

manageEditionsPortalMenuCreate.PATH = '/v1/manage/editions/{edition_id}/portal/menu';
