/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CertificateSettings } from '../../models/certificate-settings';

export interface ManageCertificateSigningKeyDelete$Params {
  edition_id: number;
}

export function manageCertificateSigningKeyDelete(http: HttpClient, rootUrl: string, params: ManageCertificateSigningKeyDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<CertificateSettings>> {
  const rb = new RequestBuilder(rootUrl, manageCertificateSigningKeyDelete.PATH, 'delete');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CertificateSettings>;
    })
  );
}

manageCertificateSigningKeyDelete.PATH = '/v1/manage/editions/{edition_id}/certificates/settings/signing-key';
