/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskCommentWriteRequest } from '../../models/task-comment-write-request';
import { TaskDetail } from '../../models/task-detail';

export interface ManageTasksComment$Params {
  edition_id: number;
  task_id: number;
      body: TaskCommentWriteRequest
}

export function manageTasksComment(http: HttpClient, rootUrl: string, params: ManageTasksComment$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskDetail>> {
  const rb = new RequestBuilder(rootUrl, manageTasksComment.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('task_id', params.task_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskDetail>;
    })
  );
}

manageTasksComment.PATH = '/v1/manage/editions/{edition_id}/tasks/{task_id}/comments';
