/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedCertificateList } from '../../models/paginated-certificate-list';

export interface ManageCertificatesList$Params {
  edition_id: number;

/**
 * Nature.
 */
  nature?: string;

/**
 * Quel champ utiliser pour classer les résultats.
 */
  ordering?: string;

/**
 * Un numéro de page de l'ensemble des résultats.
 */
  page?: number;

/**
 * Nombre de résultats à retourner par page.
 */
  page_size?: number;

/**
 * Nom ou référence.
 */
  q?: string;

/**
 * Révoquées seulement.
 */
  revoked?: boolean;
}

export function manageCertificatesList(http: HttpClient, rootUrl: string, params: ManageCertificatesList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedCertificateList>> {
  const rb = new RequestBuilder(rootUrl, manageCertificatesList.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.query('nature', params.nature, {});
    rb.query('ordering', params.ordering, {});
    rb.query('page', params.page, {});
    rb.query('page_size', params.page_size, {});
    rb.query('q', params.q, {});
    rb.query('revoked', params.revoked, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedCertificateList>;
    })
  );
}

manageCertificatesList.PATH = '/v1/manage/editions/{edition_id}/certificates';
