/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ManageLetterDetail } from '../../models/manage-letter-detail';

export interface ManageLetterRetrieve$Params {
  edition_id: number;
  letter_id: number;
}

export function manageLetterRetrieve(http: HttpClient, rootUrl: string, params: ManageLetterRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<ManageLetterDetail>> {
  const rb = new RequestBuilder(rootUrl, manageLetterRetrieve.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('letter_id', params.letter_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ManageLetterDetail>;
    })
  );
}

manageLetterRetrieve.PATH = '/v1/manage/editions/{edition_id}/invitation-letters/{letter_id}';
