/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SurveyCreateRequest } from '../../models/survey-create-request';
import { SurveyDetail } from '../../models/survey-detail';

export interface ManageSurveysCreate$Params {
  edition_id: number;
      body?: SurveyCreateRequest
}

export function manageSurveysCreate(http: HttpClient, rootUrl: string, params: ManageSurveysCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<SurveyDetail>> {
  const rb = new RequestBuilder(rootUrl, manageSurveysCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SurveyDetail>;
    })
  );
}

manageSurveysCreate.PATH = '/v1/manage/editions/{edition_id}/surveys';
