/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Section } from '../../models/section';

export interface ManageEditionsPortalSectionsList$Params {
  edition_id: number;

/**
 * Quel champ utiliser pour classer les résultats.
 */
  ordering?: string;
}

export function manageEditionsPortalSectionsList(http: HttpClient, rootUrl: string, params: ManageEditionsPortalSectionsList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Section>>> {
  const rb = new RequestBuilder(rootUrl, manageEditionsPortalSectionsList.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.query('ordering', params.ordering, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Section>>;
    })
  );
}

manageEditionsPortalSectionsList.PATH = '/v1/manage/editions/{edition_id}/portal/sections';
