/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Page } from '../../models/page';
import { SectionRefRequest } from '../../models/section-ref-request';

export interface ManagePortalPagesAttach$Params {
  edition_id: number;
  item_id: number;
      body: SectionRefRequest
}

export function managePortalPagesAttach(http: HttpClient, rootUrl: string, params: ManagePortalPagesAttach$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, managePortalPagesAttach.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('item_id', params.item_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

managePortalPagesAttach.PATH = '/v1/manage/editions/{edition_id}/portal/pages/{item_id}/attach';
