/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentTemplate } from '../../models/document-template';
import { PatchedDocumentTemplateUpdateRequest } from '../../models/patched-document-template-update-request';

export interface ManageCertificateTemplateUpdate$Params {
  edition_id: number;
  nature: string;
      body?: PatchedDocumentTemplateUpdateRequest
}

export function manageCertificateTemplateUpdate(http: HttpClient, rootUrl: string, params: ManageCertificateTemplateUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentTemplate>> {
  const rb = new RequestBuilder(rootUrl, manageCertificateTemplateUpdate.PATH, 'patch');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('nature', params.nature, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentTemplate>;
    })
  );
}

manageCertificateTemplateUpdate.PATH = '/v1/manage/editions/{edition_id}/certificates/templates/{nature}';
