/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SponsorLevel } from '../../models/sponsor-level';

export interface ManageSponsorLevelsList$Params {
  edition_id: number;
}

export function manageSponsorLevelsList(http: HttpClient, rootUrl: string, params: ManageSponsorLevelsList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SponsorLevel>>> {
  const rb = new RequestBuilder(rootUrl, manageSponsorLevelsList.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SponsorLevel>>;
    })
  );
}

manageSponsorLevelsList.PATH = '/v1/manage/editions/{edition_id}/sponsor-levels';
