/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewSubmissionDetail } from '../../models/review-submission-detail';
import { ScreeningRequest } from '../../models/screening-request';

export interface ManageReviewSubmissionScreening$Params {
  edition_id: number;
  submission_id: number;
      body: ScreeningRequest
}

export function manageReviewSubmissionScreening(http: HttpClient, rootUrl: string, params: ManageReviewSubmissionScreening$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewSubmissionDetail>> {
  const rb = new RequestBuilder(rootUrl, manageReviewSubmissionScreening.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('submission_id', params.submission_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewSubmissionDetail>;
    })
  );
}

manageReviewSubmissionScreening.PATH = '/v1/manage/editions/{edition_id}/review-submissions/{submission_id}/screening';
