/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Question } from '../../models/question';
import { QuestionWriteRequest } from '../../models/question-write-request';

export interface ManageSurveysQuestionsCreate$Params {
  edition_id: number;
  survey_id: number;
      body?: QuestionWriteRequest
}

export function manageSurveysQuestionsCreate(http: HttpClient, rootUrl: string, params: ManageSurveysQuestionsCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Question>> {
  const rb = new RequestBuilder(rootUrl, manageSurveysQuestionsCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('survey_id', params.survey_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Question>;
    })
  );
}

manageSurveysQuestionsCreate.PATH = '/v1/manage/editions/{edition_id}/surveys/{survey_id}/questions';
