/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedProgramSettingsRequest } from '../../models/patched-program-settings-request';
import { ProgramSettings } from '../../models/program-settings';

export interface ManageProgramSettingsUpdate$Params {
  edition_id: number;
      body?: PatchedProgramSettingsRequest
}

export function manageProgramSettingsUpdate(http: HttpClient, rootUrl: string, params: ManageProgramSettingsUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ProgramSettings>> {
  const rb = new RequestBuilder(rootUrl, manageProgramSettingsUpdate.PATH, 'patch');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProgramSettings>;
    })
  );
}

manageProgramSettingsUpdate.PATH = '/v1/manage/editions/{edition_id}/program/settings';
