/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedManageRegistrationListList } from '../../models/paginated-manage-registration-list-list';

export interface ManageRegistrationsList$Params {

/**
 * Code de catégorie.
 */
  category?: string;
  edition_id: number;

/**
 * Moyen de paiement.
 */
  method?: string;

/**
 * Un numéro de page de l'ensemble des résultats.
 */
  page?: number;

/**
 * Nombre de résultats à retourner par page.
 */
  page_size?: number;

/**
 * Nom, adresse ou référence.
 */
  q?: string;

/**
 * Statut (en attente, confirmée…).
 */
  status?: string;
}

export function manageRegistrationsList(http: HttpClient, rootUrl: string, params: ManageRegistrationsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedManageRegistrationListList>> {
  const rb = new RequestBuilder(rootUrl, manageRegistrationsList.PATH, 'get');
  if (params) {
    rb.query('category', params.category, {});
    rb.path('edition_id', params.edition_id, {});
    rb.query('method', params.method, {});
    rb.query('page', params.page, {});
    rb.query('page_size', params.page_size, {});
    rb.query('q', params.q, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedManageRegistrationListList>;
    })
  );
}

manageRegistrationsList.PATH = '/v1/manage/editions/{edition_id}/registrations';
