/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Checkin } from '../../models/checkin';
import { ReasonRequest } from '../../models/reason-request';

export interface ManageCheckinCancel$Params {
  checkin_id: number;
  edition_id: number;
      body: ReasonRequest
}

export function manageCheckinCancel(http: HttpClient, rootUrl: string, params: ManageCheckinCancel$Params, context?: HttpContext): Observable<StrictHttpResponse<Checkin>> {
  const rb = new RequestBuilder(rootUrl, manageCheckinCancel.PATH, 'post');
  if (params) {
    rb.path('checkin_id', params.checkin_id, {});
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Checkin>;
    })
  );
}

manageCheckinCancel.PATH = '/v1/manage/editions/{edition_id}/checkin/{checkin_id}/cancel';
