/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ManageSurveysDestroy$Params {
  edition_id: number;
  survey_id: number;
}

export function manageSurveysDestroy(http: HttpClient, rootUrl: string, params: ManageSurveysDestroy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, manageSurveysDestroy.PATH, 'delete');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('survey_id', params.survey_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

manageSurveysDestroy.PATH = '/v1/manage/editions/{edition_id}/surveys/{survey_id}';
