/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Edition } from '../../models/edition';
import { PatchedEditionRequest } from '../../models/patched-edition-request';

export interface ManageEditionUpdate$Params {
  edition_id: number;
      body?: PatchedEditionRequest
}

export function manageEditionUpdate(http: HttpClient, rootUrl: string, params: ManageEditionUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Edition>> {
  const rb = new RequestBuilder(rootUrl, manageEditionUpdate.PATH, 'patch');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Edition>;
    })
  );
}

manageEditionUpdate.PATH = '/v1/manage/editions/{edition_id}';
