/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DaySession } from '../../models/day-session';
import { ReasonRequest } from '../../models/reason-request';

export interface ManageDayUnpresented$Params {
  edition_id: number;
  session_id: number;
  slot_id: number;
      body: ReasonRequest
}

export function manageDayUnpresented(http: HttpClient, rootUrl: string, params: ManageDayUnpresented$Params, context?: HttpContext): Observable<StrictHttpResponse<DaySession>> {
  const rb = new RequestBuilder(rootUrl, manageDayUnpresented.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('session_id', params.session_id, {});
    rb.path('slot_id', params.slot_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DaySession>;
    })
  );
}

manageDayUnpresented.PATH = '/v1/manage/editions/{edition_id}/day/sessions/{session_id}/slots/{slot_id}/unpresented';
