/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShiftBoard } from '../../models/shift-board';
import { ShiftWriteRequest } from '../../models/shift-write-request';

export interface ManageShiftsCreate$Params {
  edition_id: number;
      body?: ShiftWriteRequest
}

export function manageShiftsCreate(http: HttpClient, rootUrl: string, params: ManageShiftsCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ShiftBoard>> {
  const rb = new RequestBuilder(rootUrl, manageShiftsCreate.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShiftBoard>;
    })
  );
}

manageShiftsCreate.PATH = '/v1/manage/editions/{edition_id}/logistics/shifts';
