/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Track } from '../../models/track';

export interface ManageEditionsTracksRetrieve$Params {
  edition_id: number;
  item_id: number;
}

export function manageEditionsTracksRetrieve(http: HttpClient, rootUrl: string, params: ManageEditionsTracksRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Track>> {
  const rb = new RequestBuilder(rootUrl, manageEditionsTracksRetrieve.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('item_id', params.item_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Track>;
    })
  );
}

manageEditionsTracksRetrieve.PATH = '/v1/manage/editions/{edition_id}/tracks/{item_id}';
