/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CandidateList } from '../../models/candidate-list';

export interface ManageReviewSubmissionCandidates$Params {
  edition_id: number;
  submission_id: number;
}

export function manageReviewSubmissionCandidates(http: HttpClient, rootUrl: string, params: ManageReviewSubmissionCandidates$Params, context?: HttpContext): Observable<StrictHttpResponse<CandidateList>> {
  const rb = new RequestBuilder(rootUrl, manageReviewSubmissionCandidates.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('submission_id', params.submission_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CandidateList>;
    })
  );
}

manageReviewSubmissionCandidates.PATH = '/v1/manage/editions/{edition_id}/review-submissions/{submission_id}/candidates';
