/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CancelRequest } from '../../models/cancel-request';
import { ManageRegistration } from '../../models/manage-registration';

export interface ManageRegistrationsCancel$Params {
  edition_id: number;
  item_id: number;
      body: CancelRequest
}

export function manageRegistrationsCancel(http: HttpClient, rootUrl: string, params: ManageRegistrationsCancel$Params, context?: HttpContext): Observable<StrictHttpResponse<ManageRegistration>> {
  const rb = new RequestBuilder(rootUrl, manageRegistrationsCancel.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.path('item_id', params.item_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ManageRegistration>;
    })
  );
}

manageRegistrationsCancel.PATH = '/v1/manage/editions/{edition_id}/registrations/{item_id}/cancel';
