/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicFile } from '../../models/public-file';

export interface ManageEditionsPortalFilesList$Params {
  edition_id: number;
  kind?: 'document' | 'image';

/**
 * Quel champ utiliser pour classer les résultats.
 */
  ordering?: string;
}

export function manageEditionsPortalFilesList(http: HttpClient, rootUrl: string, params: ManageEditionsPortalFilesList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PublicFile>>> {
  const rb = new RequestBuilder(rootUrl, manageEditionsPortalFilesList.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.query('kind', params.kind, {});
    rb.query('ordering', params.ordering, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PublicFile>>;
    })
  );
}

manageEditionsPortalFilesList.PATH = '/v1/manage/editions/{edition_id}/portal/files';
