/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IssueRequestRequest } from '../../models/issue-request-request';
import { IssueResponse } from '../../models/issue-response';

export interface ManageCertificatesIssue$Params {
  edition_id: number;
      body: IssueRequestRequest
}

export function manageCertificatesIssue(http: HttpClient, rootUrl: string, params: ManageCertificatesIssue$Params, context?: HttpContext): Observable<StrictHttpResponse<IssueResponse>> {
  const rb = new RequestBuilder(rootUrl, manageCertificatesIssue.PATH, 'post');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IssueResponse>;
    })
  );
}

manageCertificatesIssue.PATH = '/v1/manage/editions/{edition_id}/certificates/issue';
