/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ManageDietaryExport$Params {
  edition_id: number;
  file_format?: 'csv' | 'xlsx';
}

export function manageDietaryExport(http: HttpClient, rootUrl: string, params: ManageDietaryExport$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, manageDietaryExport.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.query('file_format', params.file_format, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

manageDietaryExport.PATH = '/v1/manage/editions/{edition_id}/logistics/dietary/export';
