/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProgramSettings } from '../../models/program-settings';

export interface ManageProgramSettingsRetrieve$Params {
  edition_id: number;
}

export function manageProgramSettingsRetrieve(http: HttpClient, rootUrl: string, params: ManageProgramSettingsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<ProgramSettings>> {
  const rb = new RequestBuilder(rootUrl, manageProgramSettingsRetrieve.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProgramSettings>;
    })
  );
}

manageProgramSettingsRetrieve.PATH = '/v1/manage/editions/{edition_id}/program/settings';
