/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewerAssignmentDetail } from '../../models/reviewer-assignment-detail';

export interface ReviewerAssignmentRetrieve$Params {
  assignment_id: number;
  edition_id: number;
}

export function reviewerAssignmentRetrieve(http: HttpClient, rootUrl: string, params: ReviewerAssignmentRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewerAssignmentDetail>> {
  const rb = new RequestBuilder(rootUrl, reviewerAssignmentRetrieve.PATH, 'get');
  if (params) {
    rb.path('assignment_id', params.assignment_id, {});
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewerAssignmentDetail>;
    })
  );
}

reviewerAssignmentRetrieve.PATH = '/v1/manage/editions/{edition_id}/reviews/assignments/{assignment_id}';
