/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Expertise } from '../../models/expertise';
import { ExpertiseWriteRequest } from '../../models/expertise-write-request';

export interface ReviewerExpertiseUpdate$Params {
  edition_id: number;
      body: ExpertiseWriteRequest
}

export function reviewerExpertiseUpdate(http: HttpClient, rootUrl: string, params: ReviewerExpertiseUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Expertise>> {
  const rb = new RequestBuilder(rootUrl, reviewerExpertiseUpdate.PATH, 'put');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Expertise>;
    })
  );
}

reviewerExpertiseUpdate.PATH = '/v1/manage/editions/{edition_id}/reviews/expertise';
