# Generated by Django 5.2.17 on 2026-10-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CronHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="commande"
                    ),
                ),
                (
                    "last_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier démarrage"
                    ),
                ),
                (
                    "last_finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernière fin"
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier succès"
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("running", "en cours"),
                            ("ok", "réussi"),
                            ("error", "en erreur"),
                        ],
                        max_length=10,
                        verbose_name="dernier statut",
                    ),
                ),
                (
                    "last_duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="dernière durée (ms)"
                    ),
                ),
                (
                    "processed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="éléments traités"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", verbose_name="dernière erreur"
                    ),
                ),
            ],
            options={
                "verbose_name": "battement de cœur",
                "verbose_name_plural": "battements de cœur",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=64, verbose_name="type")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="données"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "en attente"),
                            ("running", "en cours"),
                            ("succeeded", "terminée"),
                            ("failed", "en échec"),
                            ("cancelled", "annulée"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(default=100, verbose_name="priorité"),
                ),
                ("run_at", models.DateTimeField(verbose_name="à exécuter à partir de")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="tentatives"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="tentatives maximales"
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="réservée le"
                    ),
                ),
                (
                    "locked_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="réservée par",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminée le"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", verbose_name="dernière erreur"
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="clé d'idempotence",
                    ),
                ),
            ],
            options={
                "verbose_name": "tâche",
                "verbose_name_plural": "tâches",
                "indexes": [
                    models.Index(
                        fields=["status", "priority", "run_at"], name="core_job_queue"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(db_index=True, verbose_name="date")),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[
                            ("user", "utilisateur"),
                            ("command", "commande"),
                            ("system", "système"),
                        ],
                        max_length=8,
                        verbose_name="type d'acteur",
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="libellé de l'acteur",
                    ),
                ),
                ("action", models.CharField(max_length=64, verbose_name="action")),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="type d'objet",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="identifiant d'objet",
                    ),
                ),
                (
                    "before",
                    models.JSONField(blank=True, null=True, verbose_name="avant"),
                ),
                (
                    "after",
                    models.JSONField(blank=True, null=True, verbose_name="après"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="motif"),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="identifiant de requête",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="navigateur",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée du journal d'audit",
                "verbose_name_plural": "journal d'audit",
                "ordering": ("-at", "-id"),
                "indexes": [
                    models.Index(fields=["actor", "at"], name="core_audit_actor_at"),
                    models.Index(
                        fields=["object_type", "object_id"], name="core_audit_object"
                    ),
                    models.Index(fields=["action", "at"], name="core_audit_action_at"),
                ],
            },
        ),
    ]
