# Generated by Django 5.2.17 on 2026-10-05 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0002_conference_current_edition"),
        ("core", "0002_edition_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        editable=False, unique=True, verbose_name="identifiant public"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("document", "document"),
                            ("image", "image"),
                            ("photo", "photo de profil"),
                        ],
                        max_length=10,
                        verbose_name="nature",
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="nom de stockage"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="nom d'origine"),
                ),
                ("extension", models.CharField(max_length=8, verbose_name="extension")),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="type de contenu"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="taille (octets)")),
                (
                    "sha256",
                    models.CharField(max_length=64, verbose_name="empreinte SHA-256"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="largeur"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="hauteur"
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="titre (FR)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="titre (EN)",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="publié"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "fichier public",
                "verbose_name_plural": "fichiers publics",
                "ordering": ("position", "id"),
                "indexes": [
                    models.Index(
                        fields=["edition", "kind", "position"], name="core_pubfile_kind"
                    )
                ],
            },
        ),
    ]
