# Generated by Django 5.2.17 on 2026-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_public_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(max_length=64, unique=True, verbose_name="portée"),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="dernière valeur"
                    ),
                ),
            ],
            options={
                "verbose_name": "compteur",
                "verbose_name_plural": "compteurs",
            },
        ),
    ]
