# Generated by Django 5.2.17 on 2026-10-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicfile",
            name="kind",
            field=models.CharField(
                choices=[
                    ("document", "document"),
                    ("image", "image"),
                    ("photo", "photo de profil"),
                    ("logo", "logo de partenaire"),
                ],
                max_length=10,
                verbose_name="nature",
            ),
        ),
    ]
