# Generated by Django 5.2.17 on 2026-10-06 16:44

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0006_program_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, verbose_name="code")),
                (
                    "label_fr",
                    models.CharField(max_length=150, verbose_name="libellé (FR)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="libellé (EN)",
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="description (FR)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="description (EN)"
                    ),
                ),
                (
                    "requires_proof",
                    models.BooleanField(
                        default=False, verbose_name="justificatif demandé"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registration_categories",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie d'inscription",
                "verbose_name_plural": "catégories d'inscription",
                "ordering": ("edition", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, verbose_name="code")),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "pourcentage"), ("amount", "montant")],
                        max_length=8,
                        verbose_name="type de remise",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="valeur"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("registration", "inscription seule"),
                            ("all", "inscription et options"),
                        ],
                        default="registration",
                        max_length=16,
                        verbose_name="portée",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="utilisations maximales"
                    ),
                ),
                (
                    "reserved_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="utilisations réservées"
                    ),
                ),
                (
                    "consumed_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="utilisations consommées"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="valable jusqu'au (UTC)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="promo_codes",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="registrations.registrationcategory",
                        verbose_name="catégories visées",
                    ),
                ),
            ],
            options={
                "verbose_name": "code promo",
                "verbose_name_plural": "codes promo",
                "ordering": ("edition", "code"),
            },
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("early", "préférentiel"),
                            ("regular", "normal"),
                            ("onsite", "sur place"),
                        ],
                        max_length=8,
                        verbose_name="période",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("local", "local"),
                            ("international", "international"),
                        ],
                        max_length=16,
                        verbose_name="zone",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="montant"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="fees",
                        to="registrations.registrationcategory",
                        verbose_name="catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarif",
                "verbose_name_plural": "tarifs",
            },
        ),
        migrations.CreateModel(
            name="RegistrationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, verbose_name="code")),
                (
                    "label_fr",
                    models.CharField(max_length=150, verbose_name="libellé (FR)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="libellé (EN)",
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="description (FR)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="description (EN)"
                    ),
                ),
                (
                    "price_local",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="prix (local)",
                    ),
                ),
                (
                    "price_international",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="prix (international)",
                    ),
                ),
                (
                    "quota",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="places"
                    ),
                ),
                (
                    "reserved",
                    models.PositiveIntegerField(
                        default=0, verbose_name="places réservées"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="registrations.registrationcategory",
                        verbose_name="catégories autorisées",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registration_options",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "option d'inscription",
                "verbose_name_plural": "options d'inscription",
                "ordering": ("edition", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "en attente de paiement"),
                            ("confirmed", "confirmée"),
                            ("cancelled", "annulée"),
                            ("expired", "expirée"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("early", "préférentiel"),
                            ("regular", "normal"),
                            ("onsite", "sur place"),
                        ],
                        max_length=8,
                        verbose_name="période",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("local", "local"),
                            ("international", "international"),
                        ],
                        max_length=16,
                        verbose_name="zone",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("online", "paiement en ligne"),
                            ("transfer", "virement (bon de commande)"),
                            ("onsite", "sur place"),
                            ("free", "aucun paiement (montant nul)"),
                            ("waiver", "gratuité accordée"),
                        ],
                        max_length=10,
                        verbose_name="moyen de paiement",
                    ),
                ),
                ("lines", models.JSONField(default=list, verbose_name="lignes")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="total"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XOF", "franc CFA (UEMOA)"),
                            ("XAF", "franc CFA (CEMAC)"),
                            ("EUR", "euro"),
                            ("USD", "dollar des États-Unis"),
                            ("GNF", "franc guinéen"),
                            ("CDF", "franc congolais"),
                        ],
                        max_length=3,
                        verbose_name="devise",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="échéance de paiement"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmée le"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="annulée ou expirée le"
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="nom de facturation",
                    ),
                ),
                (
                    "billing_organization",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="organisme de facturation",
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(
                        blank=True, default="", verbose_name="adresse de facturation"
                    ),
                ),
                (
                    "qr_token",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="jeton QR",
                    ),
                ),
                (
                    "active_key",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="clé d'unicité active",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registrations",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registrations",
                        to="registrations.promocode",
                        verbose_name="code promo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="participant",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registrations",
                        to="registrations.registrationcategory",
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        blank=True,
                        related_name="registrations",
                        to="registrations.registrationoption",
                        verbose_name="options",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscription",
                "verbose_name_plural": "inscriptions",
                "ordering": ("edition", "-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XOF", "franc CFA (UEMOA)"),
                            ("XAF", "franc CFA (CEMAC)"),
                            ("EUR", "euro"),
                            ("USD", "dollar des États-Unis"),
                            ("GNF", "franc guinéen"),
                            ("CDF", "franc congolais"),
                        ],
                        default="XOF",
                        max_length=3,
                        verbose_name="devise",
                    ),
                ),
                (
                    "local_countries",
                    models.JSONField(
                        blank=True, default=list, verbose_name="pays locaux"
                    ),
                ),
                (
                    "online_enabled",
                    models.BooleanField(
                        default=False, verbose_name="paiement en ligne proposé"
                    ),
                ),
                (
                    "transfer_enabled",
                    models.BooleanField(default=True, verbose_name="virement proposé"),
                ),
                (
                    "onsite_enabled",
                    models.BooleanField(
                        default=True, verbose_name="paiement sur place proposé"
                    ),
                ),
                (
                    "online_deadline_hours",
                    models.PositiveSmallIntegerField(
                        default=72,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(720),
                        ],
                        verbose_name="délai de paiement en ligne (heures)",
                    ),
                ),
                (
                    "transfer_deadline_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="délai de paiement par virement (jours)",
                    ),
                ),
                (
                    "cancellation_deadline",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="annulation par le participant jusqu'au (UTC)",
                    ),
                ),
                (
                    "refund_percent_before",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="part remboursée avant la date limite (%)",
                    ),
                ),
                (
                    "refund_percent_after",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="part remboursée après la date limite (%)",
                    ),
                ),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registration_settings",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "paramètres des inscriptions",
                "verbose_name_plural": "paramètres des inscriptions",
            },
        ),
        migrations.CreateModel(
            name="RegistrationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "en attente de paiement"),
                            ("confirmed", "confirmée"),
                            ("cancelled", "annulée"),
                            ("expired", "expirée"),
                        ],
                        max_length=10,
                        verbose_name="statut de départ",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending", "en attente de paiement"),
                            ("confirmed", "confirmée"),
                            ("cancelled", "annulée"),
                            ("expired", "expirée"),
                        ],
                        max_length=10,
                        verbose_name="statut d'arrivée",
                    ),
                ),
                ("at", models.DateTimeField(verbose_name="date du changement")),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="acteur (commande ou tâche)",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="motif"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur du changement",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="history",
                        to="registrations.registration",
                        verbose_name="inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "historique d'une inscription",
                "verbose_name_plural": "historiques des inscriptions",
                "ordering": ("registration", "at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="registrationcategory",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"), name="reg_category_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="promocode",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"), name="reg_promo_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="promocode",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gt", 0)), name="reg_promo_value_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="promocode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "percent"), _negated=True),
                    ("value__lte", 100),
                    _connector="OR",
                ),
                name="reg_promo_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="promocode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_uses__isnull", True),
                    (
                        "max_uses__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("reserved_uses"), "+", models.F("consumed_uses")
                        ),
                    ),
                    _connector="OR",
                ),
                name="reg_promo_uses",
            ),
        ),
        migrations.AddConstraint(
            model_name="fee",
            constraint=models.UniqueConstraint(
                fields=("category", "period", "zone"), name="reg_fee_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="fee",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="reg_fee_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationoption",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"), name="reg_option_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationoption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_international__gte", 0), ("price_local__gte", 0)
                ),
                name="reg_option_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationoption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quota__isnull", True),
                    ("reserved__lte", models.F("quota")),
                    _connector="OR",
                ),
                name="reg_option_quota",
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["edition", "status"], name="reg_registration_status"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["status", "due_at"], name="reg_registration_due"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)), name="reg_registration_total"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("active_key__isnull", False),
                        ("status__in", ("pending", "confirmed")),
                    ),
                    models.Q(
                        models.Q(
                            ("status__in", ("pending", "confirmed")), _negated=True
                        ),
                        ("active_key__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="reg_registration_active_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("qr_token__isnull", True), ("status", "confirmed"), _connector="OR"
                ),
                name="reg_registration_qr_confirmed",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("refund_percent_after__lte", 100),
                    ("refund_percent_before__lte", 100),
                ),
                name="reg_settings_refund_range",
            ),
        ),
    ]
