# Generated by Django 5.2.17 on 2026-10-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="proof_kind",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                verbose_name="type du justificatif",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="proof_original_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="nom du justificatif",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="proof_size",
            field=models.PositiveIntegerField(
                default=0, verbose_name="taille du justificatif"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="proof_storage_name",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="justificatif"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="proof_uploaded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="justificatif déposé le"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="refund_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="remboursement dû",
            ),
        ),
    ]
