# Generated by Django 5.2.17 on 2026-10-06 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_proof_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationcategory",
            name="badge_color",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$", "Couleur « #RRGGBB » attendue."
                    )
                ],
                verbose_name="couleur du badge",
            ),
        ),
        migrations.CreateModel(
            name="RetiredQrToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="empreinte du jeton"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("cancelled", "inscription annulée"),
                            ("replaced", "badge remplacé"),
                        ],
                        max_length=10,
                        verbose_name="motif",
                    ),
                ),
                ("retired_at", models.DateTimeField(verbose_name="retiré le")),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="retired_tokens",
                        to="registrations.registration",
                        verbose_name="inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "jeton QR retiré",
                "verbose_name_plural": "jetons QR retirés",
            },
        ),
    ]
