# Generated by Django 5.2.17 on 2026-10-06 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0006_program_settings"),
        ("program", "0001_initial"),
        ("registrations", "0002_proof_refund"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scanned_at",
                    models.DateTimeField(verbose_name="pointé le (appareil)"),
                ),
                ("received_at", models.DateTimeField(verbose_name="reçu le")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("scan", "lecture du QR"),
                            ("manual", "saisie manuelle"),
                        ],
                        max_length=8,
                        verbose_name="moyen",
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="appareil"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="clé d'idempotence"
                    ),
                ),
                (
                    "active_key",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="clé du pointage actif",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="annulé le"
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motif d'annulation",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="annulé par",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="checkins",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pointé par",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="checkins",
                        to="registrations.registration",
                        verbose_name="inscription",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="checkins",
                        to="program.session",
                        verbose_name="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "pointage",
                "db_table": "events_checkin",
                "indexes": [
                    models.Index(
                        fields=["edition", "received_at"],
                        name="events_checkin_received",
                    ),
                    models.Index(
                        fields=["registration", "session"], name="events_checkin_place"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="nom affiché",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="fonction (FR)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="fonction (EN)",
                    ),
                ),
                (
                    "image_storage_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="image (nom de stockage)",
                    ),
                ),
                (
                    "image_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="empreinte de l'image",
                    ),
                ),
                (
                    "image_width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="largeur (px)"
                    ),
                ),
                (
                    "image_height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="hauteur (px)"
                    ),
                ),
                (
                    "image_uploaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="image déposée le"
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="signatures",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="signatures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="signataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "signature",
                "db_table": "events_signature",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "user"), name="events_signature_unique"
                    )
                ],
            },
        ),
    ]
