# Generated by Django 5.2.17 on 2026-10-06 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0006_program_settings"),
        ("events", "0001_initial"),
        ("submissions", "0003_duplicates_reminders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signing_mode",
                    models.CharField(
                        choices=[
                            ("image", "image de la signature"),
                            ("pades", "signature électronique PAdES"),
                            ("provider", "prestataire de signature qualifiée"),
                        ],
                        default="image",
                        max_length=10,
                        verbose_name="signature",
                    ),
                ),
                (
                    "review_enabled",
                    models.BooleanField(
                        default=False, verbose_name="attestation d'évaluation"
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("signature_right", "signature à droite, QR à gauche"),
                            ("signature_left", "signature à gauche, QR à droite"),
                        ],
                        default="signature_right",
                        max_length=16,
                        verbose_name="disposition",
                    ),
                ),
                (
                    "header_storage_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="en-tête (nom de stockage)",
                    ),
                ),
                (
                    "header_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="empreinte de l'en-tête",
                    ),
                ),
                (
                    "header_width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="largeur de l'en-tête (px)"
                    ),
                ),
                (
                    "header_height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="hauteur de l'en-tête (px)"
                    ),
                ),
                (
                    "key_storage_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="certificat de signature (nom de stockage)",
                    ),
                ),
                (
                    "key_subject",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="titulaire du certificat",
                    ),
                ),
                (
                    "key_not_after",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="certificat valable jusqu'au",
                    ),
                ),
                (
                    "key_uploaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="certificat déposé le"
                    ),
                ),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="certificate_settings",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "paramètres des attestations",
                "db_table": "events_certificate_settings",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("participation", "attestation de participation"),
                            ("presentation", "attestation de communication"),
                            ("review", "attestation d'évaluation"),
                            ("letter", "lettre d'invitation"),
                        ],
                        max_length=16,
                        verbose_name="nature",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="nom")),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="institution",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="détails"),
                ),
                (
                    "verification_code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="code de vérification"
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(
                        max_length=64, verbose_name="PDF (nom de stockage)"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(max_length=64, verbose_name="empreinte du PDF"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="taille")),
                (
                    "signing_mode",
                    models.CharField(
                        choices=[
                            ("image", "image de la signature"),
                            ("pades", "signature électronique PAdES"),
                            ("provider", "prestataire de signature qualifiée"),
                        ],
                        max_length=10,
                        verbose_name="signature",
                    ),
                ),
                (
                    "signatory_name",
                    models.CharField(max_length=150, verbose_name="signataire"),
                ),
                (
                    "signatory_title_fr",
                    models.CharField(
                        max_length=200, verbose_name="fonction du signataire (FR)"
                    ),
                ),
                (
                    "signatory_title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="fonction du signataire (EN)",
                    ),
                ),
                (
                    "signature_sha256",
                    models.CharField(
                        max_length=64, verbose_name="empreinte de l'image de signature"
                    ),
                ),
                ("issued_at", models.DateTimeField(verbose_name="émise le")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="révoquée le"
                    ),
                ),
                (
                    "revoke_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motif de révocation",
                    ),
                ),
                (
                    "active_key",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="clé de l'attestation active",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="certificates",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="émise à la demande de",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="révoquée par",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="certificates",
                        to="submissions.submission",
                        verbose_name="communication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="titulaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "attestation",
                "db_table": "events_certificate",
                "indexes": [
                    models.Index(
                        fields=["edition", "nature"], name="events_certificate_nature"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("participation", "attestation de participation"),
                            ("presentation", "attestation de communication"),
                            ("review", "attestation d'évaluation"),
                            ("letter", "lettre d'invitation"),
                        ],
                        max_length=16,
                        verbose_name="nature",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="titre (FR)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="titre (EN)",
                    ),
                ),
                (
                    "body_fr",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=2000,
                        verbose_name="texte (FR)",
                    ),
                ),
                (
                    "body_en",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=2000,
                        verbose_name="texte (EN)",
                    ),
                ),
                (
                    "footer_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="pied de page (FR)",
                    ),
                ),
                (
                    "footer_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="pied de page (EN)",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="document_templates",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "signatory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="templates",
                        to="events.signature",
                        verbose_name="signataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "gabarit de pièce",
                "db_table": "events_document_template",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "nature"), name="events_template_unique"
                    )
                ],
            },
        ),
    ]
