# Generated by Django 5.2.17 on 2026-10-06 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0006_program_settings"),
        ("events", "0002_certificates"),
        ("registrations", "0003_badge_color_retired_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "passport_name",
                    models.CharField(max_length=200, verbose_name="nom (passeport)"),
                ),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="nationalité"),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="numéro de passeport",
                    ),
                ),
                (
                    "passport_erased_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="numéro effacé le"
                    ),
                ),
                ("stay_from", models.DateField(verbose_name="arrivée")),
                ("stay_to", models.DateField(verbose_name="départ")),
                (
                    "embassy",
                    models.CharField(
                        max_length=300, verbose_name="ambassade ou consulat"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "demandée"),
                            ("issued", "émise"),
                            ("refused", "refusée"),
                            ("revoked", "révoquée"),
                        ],
                        default="requested",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="instruite le"
                    ),
                ),
                (
                    "refuse_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motif du refus",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="code de vérification",
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="PDF (nom de stockage)",
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="empreinte du PDF",
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0, verbose_name="taille")),
                (
                    "signing_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("image", "image de la signature"),
                            ("pades", "signature électronique PAdES"),
                            ("provider", "prestataire de signature qualifiée"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="signature",
                    ),
                ),
                (
                    "signatory_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="signataire",
                    ),
                ),
                (
                    "signatory_title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="fonction du signataire (FR)",
                    ),
                ),
                (
                    "signatory_title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="fonction du signataire (EN)",
                    ),
                ),
                (
                    "signature_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="empreinte de l'image de signature",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="émise le"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="révoquée le"
                    ),
                ),
                (
                    "revoke_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motif de révocation",
                    ),
                ),
                (
                    "active_key",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="clé de la lettre active",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="instruite par",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invitation_letters",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invitation_letters",
                        to="registrations.registration",
                        verbose_name="inscription",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="révoquée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "lettre d'invitation",
                "db_table": "events_invitation_letter",
                "indexes": [
                    models.Index(
                        fields=["edition", "status"], name="events_letter_status"
                    )
                ],
            },
        ),
    ]
