/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MyDietary } from '../../models/my-dietary';

export interface MeDietaryRetrieve$Params {
  edition_id: number;
}

export function meDietaryRetrieve(http: HttpClient, rootUrl: string, params: MeDietaryRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<MyDietary>> {
  const rb = new RequestBuilder(rootUrl, meDietaryRetrieve.PATH, 'get');
  if (params) {
    rb.path('edition_id', params.edition_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MyDietary>;
    })
  );
}

meDietaryRetrieve.PATH = '/v1/me/editions/{edition_id}/dietary';
