/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationList } from '../../models/notification-list';

export interface MeNotifications$Params {
}

export function meNotifications(http: HttpClient, rootUrl: string, params?: MeNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationList>> {
  const rb = new RequestBuilder(rootUrl, meNotifications.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationList>;
    })
  );
}

meNotifications.PATH = '/v1/me/notifications';
