/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Profile } from '../../models/profile';

export interface MeProfile$Params {
}

export function meProfile(http: HttpClient, rootUrl: string, params?: MeProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<Profile>> {
  const rb = new RequestBuilder(rootUrl, meProfile.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Profile>;
    })
  );
}

meProfile.PATH = '/v1/me/profile';
