/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AnswerRequest } from '../../models/answer-request';
import { MySurvey } from '../../models/my-survey';

export interface MeSurveyAnswer$Params {
  survey_id: number;
      body: AnswerRequest
}

export function meSurveyAnswer(http: HttpClient, rootUrl: string, params: MeSurveyAnswer$Params, context?: HttpContext): Observable<StrictHttpResponse<MySurvey>> {
  const rb = new RequestBuilder(rootUrl, meSurveyAnswer.PATH, 'post');
  if (params) {
    rb.path('survey_id', params.survey_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MySurvey>;
    })
  );
}

meSurveyAnswer.PATH = '/v1/me/surveys/{survey_id}';
