/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TotpQr } from '../../models/totp-qr';

export interface MeTotpQr$Params {
}

export function meTotpQr(http: HttpClient, rootUrl: string, params?: MeTotpQr$Params, context?: HttpContext): Observable<StrictHttpResponse<TotpQr>> {
  const rb = new RequestBuilder(rootUrl, meTotpQr.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TotpQr>;
    })
  );
}

meTotpQr.PATH = '/v1/me/totp-qr';
