# Generated by Django 5.2.17 on 2026-10-07 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0006_program_settings"),
        ("core", "0005_alter_publicfile_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "website",
                    models.URLField(
                        blank=True, default="", max_length=300, verbose_name="site"
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="présentation (FR)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="présentation (EN)"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, verbose_name="publié sur le portail"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="contact"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="adresse du contact",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="téléphone du contact",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "prospect"),
                            ("agreed", "accord conclu"),
                            ("received", "contribution reçue"),
                            ("declined", "refus"),
                        ],
                        default="prospect",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "agreed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="contribution convenue",
                    ),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="montant reçu",
                    ),
                ),
                (
                    "received_on",
                    models.DateField(blank=True, null=True, verbose_name="reçu le"),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", verbose_name="note interne"
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sponsors",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="core.publicfile",
                        verbose_name="logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "partenaire",
                "verbose_name_plural": "partenaires",
                "ordering": ("edition", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="SponsorBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(max_length=200, verbose_name="contrepartie"),
                ),
                (
                    "delivered_on",
                    models.DateField(blank=True, null=True, verbose_name="livrée le"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="sponsors.sponsor",
                        verbose_name="partenaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrepartie",
                "verbose_name_plural": "contreparties",
                "ordering": ("sponsor", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="SponsorLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_fr", models.CharField(max_length=100, verbose_name="nom (FR)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="nom (EN)"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="montant indicatif",
                    ),
                ),
                (
                    "benefits_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="contreparties (FR)"
                    ),
                ),
                (
                    "benefits_en",
                    models.TextField(
                        blank=True, default="", verbose_name="contreparties (EN)"
                    ),
                ),
                (
                    "logo_size",
                    models.CharField(
                        choices=[
                            ("small", "petite"),
                            ("medium", "moyenne"),
                            ("large", "grande"),
                        ],
                        default="medium",
                        max_length=8,
                        verbose_name="taille du logo",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sponsor_levels",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "niveau de partenariat",
                "verbose_name_plural": "niveaux de partenariat",
                "ordering": ("edition", "position", "id"),
            },
        ),
        migrations.AddField(
            model_name="sponsor",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sponsors",
                to="sponsors.sponsorlevel",
                verbose_name="niveau",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsorlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__isnull", True), ("amount__gte", 0), _connector="OR"
                ),
                name="spo_level_amount_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("agreed_amount__isnull", True),
                    ("agreed_amount__gte", 0),
                    _connector="OR",
                ),
                name="spo_agreed_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("received_amount__isnull", True),
                    ("received_amount__gte", 0),
                    _connector="OR",
                ),
                name="spo_received_pos",
            ),
        ),
    ]
