/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Submission } from '../../models/submission';
import { SubmissionCreateRequest } from '../../models/submission-create-request';

export interface SubmissionsCreate$Params {
      body: SubmissionCreateRequest
}

export function submissionsCreate(http: HttpClient, rootUrl: string, params: SubmissionsCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Submission>> {
  const rb = new RequestBuilder(rootUrl, submissionsCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Submission>;
    })
  );
}

submissionsCreate.PATH = '/v1/submissions';
