/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FinalVersionUploadRequest } from '../../models/final-version-upload-request';
import { Submission } from '../../models/submission';

export interface SubmissionsFinalVersion$Params {
  submission_id: number;
      body: FinalVersionUploadRequest
}

export function submissionsFinalVersion(http: HttpClient, rootUrl: string, params: SubmissionsFinalVersion$Params, context?: HttpContext): Observable<StrictHttpResponse<Submission>> {
  const rb = new RequestBuilder(rootUrl, submissionsFinalVersion.PATH, 'post');
  if (params) {
    rb.path('submission_id', params.submission_id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Submission>;
    })
  );
}

submissionsFinalVersion.PATH = '/v1/submissions/{submission_id}/final-version';
