# Generated by Django 5.2.17 on 2026-10-05 16:09

import apps.accounts.validators
import apps.conferences.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=64, unique=True, verbose_name="identifiant"
                    ),
                ),
                ("name_fr", models.CharField(max_length=255, verbose_name="nom (FR)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="nom (EN)"
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="description (FR)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="description (EN)"
                    ),
                ),
            ],
            options={
                "verbose_name": "conférence",
                "verbose_name_plural": "conférences",
            },
        ),
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[apps.conferences.validators.validate_edition_code],
                        verbose_name="code",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, verbose_name="identifiant")),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="année",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=255, verbose_name="titre (FR)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="titre (EN)",
                    ),
                ),
                (
                    "theme_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="thème (FR)",
                    ),
                ),
                (
                    "theme_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="thème (EN)",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="début"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="fin"),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="lieu"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="ville"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=2,
                        validators=[apps.accounts.validators.validate_country],
                        verbose_name="pays",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Abidjan",
                        max_length=64,
                        validators=[apps.conferences.validators.validate_timezone],
                        verbose_name="fuseau horaire",
                    ),
                ),
                (
                    "double_blind",
                    models.BooleanField(default=True, verbose_name="double aveugle"),
                ),
                (
                    "reviewers_per_submission",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="relecteurs par soumission",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "brouillon"),
                            ("published", "publiée"),
                            ("archived", "archivée"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publiée le"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archivée le"
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="editions",
                        to="conferences.conference",
                        verbose_name="conférence",
                    ),
                ),
            ],
            options={
                "verbose_name": "édition",
                "verbose_name_plural": "éditions",
            },
        ),
        migrations.CreateModel(
            name="KeyDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, verbose_name="code")),
                ("at", models.DateTimeField(verbose_name="date (UTC)")),
                (
                    "label_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="libellé (FR)",
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="libellé (EN)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="publique"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="key_dates",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "date clé",
                "verbose_name_plural": "dates clés",
                "ordering": ("at", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="SubmissionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, verbose_name="code")),
                (
                    "label_fr",
                    models.CharField(max_length=255, verbose_name="libellé (FR)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="libellé (EN)",
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="description (FR)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="description (EN)"
                    ),
                ),
                (
                    "default_duration_min",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="durée par défaut (min)"
                    ),
                ),
                (
                    "abstract_max_words",
                    models.PositiveSmallIntegerField(
                        default=300,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(2000),
                        ],
                        verbose_name="mots maximum du résumé",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="submission_types",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "type de communication",
                "verbose_name_plural": "types de communication",
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, verbose_name="code")),
                ("name_fr", models.CharField(max_length=255, verbose_name="nom (FR)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="nom (EN)"
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="description (FR)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="description (EN)"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tracks",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "thématique",
                "verbose_name_plural": "thématiques",
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="edition",
            index=models.Index(
                fields=["conference", "status"], name="conf_edition_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.UniqueConstraint(
                fields=("conference", "slug"), name="conf_edition_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="conf_edition_dates_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reviewers_per_submission__gte", 1),
                    ("reviewers_per_submission__lte", 10),
                ),
                name="conf_edition_reviewers_range",
            ),
        ),
        migrations.AddIndex(
            model_name="keydate",
            index=models.Index(fields=["edition", "at"], name="conf_keydate_at"),
        ),
        migrations.AddConstraint(
            model_name="keydate",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"), name="conf_keydate_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissiontype",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"), name="conf_subtype_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissiontype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("abstract_max_words__gte", 50), ("abstract_max_words__lte", 2000)
                ),
                name="conf_subtype_words_range",
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["edition", "position"], name="conf_track_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"), name="conf_track_code"
            ),
        ),
    ]
