# Generated by Django 5.2.17 on 2026-10-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0002_conference_current_edition"),
        ("core", "0003_public_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="core.publicfile",
                verbose_name="affiche",
            ),
        ),
    ]
