# Generated by Django 5.2.17 on 2026-10-05 22:00

import apps.conferences.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0003_edition_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="submission_languages",
            field=models.JSONField(
                default=apps.conferences.models.default_submission_languages,
                verbose_name="langues des soumissions",
            ),
        ),
        migrations.AddField(
            model_name="submissiontype",
            name="file_policy",
            field=models.CharField(
                choices=[
                    ("none", "aucun fichier"),
                    ("optional", "facultatif"),
                    ("required", "obligatoire"),
                ],
                default="optional",
                max_length=8,
                verbose_name="fichier PDF",
            ),
        ),
        migrations.AddField(
            model_name="submissiontype",
            name="max_file_mb",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
                verbose_name="taille maximale du fichier (Mo)",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissiontype",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_file_mb__gte", 1), ("max_file_mb__lte", 50)),
                name="conf_subtype_file_mb_range",
            ),
        ),
    ]
