# Generated by Django 5.2.17 on 2026-10-06 00:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0004_submission_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="confidence_weighted_score",
            field=models.BooleanField(
                default=False, verbose_name="score final pondéré par la confiance"
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="divergence_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("30"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="seuil de divergence (points sur 100)",
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="max_reviews_per_reviewer",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="évaluations au plus par relecteur",
            ),
        ),
    ]
