# Generated by Django 5.2.17 on 2026-10-06 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0005_edition_confidence_weighted_score_and_more"),
        ("core", "0004_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="presenter_registration_required",
            field=models.BooleanField(
                default=False, verbose_name="présentateur inscrit exigé (RG-11)"
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="session_buffer_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(30)],
                verbose_name="tampon entre créneaux (minutes)",
            ),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.CheckConstraint(
                condition=models.Q(("session_buffer_minutes__lte", 30)),
                name="conf_edition_buffer_range",
            ),
        ),
    ]
