/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AcceptedRole } from '../../models/accepted-role';
import { AcceptRequest } from '../../models/accept-request';

export interface InvitationAccept$Params {
      body?: AcceptRequest
}

export function invitationAccept(http: HttpClient, rootUrl: string, params?: InvitationAccept$Params, context?: HttpContext): Observable<StrictHttpResponse<AcceptedRole>> {
  const rb = new RequestBuilder(rootUrl, invitationAccept.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AcceptedRole>;
    })
  );
}

invitationAccept.PATH = '/v1/invitations/accept';
