# Generated by Django 5.2.17 on 2026-10-05 14:47

import apps.accounts.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="anonymisé le"
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "aucun"),
                            ("dr", "Dr"),
                            ("pr", "Pr"),
                            ("mr", "M."),
                            ("ms", "Mme"),
                        ],
                        default="",
                        max_length=8,
                        verbose_name="titre",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="prénom"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="nom"
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="institution",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="département",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=2,
                        validators=[apps.accounts.validators.validate_country],
                        verbose_name="pays",
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=19,
                        validators=[apps.accounts.validators.validate_orcid],
                        verbose_name="ORCID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        default="",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                        verbose_name="biographie",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "verbose_name_plural": "profils",
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"], name="accounts_profile_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("privacy_notice", "notice d'information"),
                            ("directory_listing", "annuaire public"),
                        ],
                        max_length=32,
                        verbose_name="type",
                    ),
                ),
                ("granted", models.BooleanField(verbose_name="accordé")),
                (
                    "text_version",
                    models.CharField(max_length=32, verbose_name="version du texte"),
                ),
                ("recorded_at", models.DateTimeField(verbose_name="enregistré le")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("first_login", "première connexion"),
                            ("account", "espace compte"),
                            ("command", "commande"),
                        ],
                        max_length=16,
                        verbose_name="origine",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adresse IP"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "consentement",
                "verbose_name_plural": "consentements",
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "recorded_at"],
                        name="accounts_consent_state",
                    )
                ],
            },
        ),
    ]
