# Generated by Django 5.2.17 on 2026-10-05 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_anonymized_at_profile_consent"),
        ("conferences", "0002_conference_current_edition"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="adresse invitée"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "administrateur de l'édition"),
                            ("CHAIR", "président de la conférence"),
                            ("SC_CHAIR", "président du comité scientifique"),
                            ("OC_MEMBER", "membre du comité d'organisation"),
                            ("SC_MEMBER", "membre du comité scientifique"),
                        ],
                        max_length=16,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "oc_function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "aucune"),
                            ("finance", "finances"),
                            ("program", "programme"),
                            ("logistics", "logistique"),
                            ("communication", "communication"),
                            ("external_relations", "relations extérieures"),
                            ("volunteers", "bénévoles"),
                            ("secretariat", "secrétariat"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="fonction au CO",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="empreinte du jeton"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "en attente"),
                            ("accepted", "acceptée"),
                            ("declined", "refusée"),
                            ("cancelled", "annulée"),
                            ("expired", "expirée"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="statut",
                    ),
                ),
                (
                    "pending_key",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="clé d'unicité en attente",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expire le")),
                ("locale", models.CharField(max_length=8, verbose_name="langue")),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="message"),
                ),
                (
                    "send_count",
                    models.PositiveSmallIntegerField(default=1, verbose_name="envois"),
                ),
                ("last_sent_at", models.DateTimeField(verbose_name="dernier envoi")),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="répondu le"
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acceptée par",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invitations",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "administrateur de l'édition"),
                            ("CHAIR", "président de la conférence"),
                            ("OC_MEMBER", "membre du comité d'organisation"),
                            ("SC_CHAIR", "président du comité scientifique"),
                            ("SC_MEMBER", "membre du comité scientifique"),
                            ("AUTHOR", "auteur"),
                            ("SPEAKER", "intervenant"),
                            ("SESSION_CHAIR", "président de session"),
                            ("ATTENDEE", "participant"),
                            ("SPONSOR", "partenaire"),
                            ("VOLUNTEER", "bénévole"),
                        ],
                        max_length=16,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "oc_function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "aucune"),
                            ("finance", "finances"),
                            ("program", "programme"),
                            ("logistics", "logistique"),
                            ("communication", "communication"),
                            ("external_relations", "relations extérieures"),
                            ("volunteers", "bénévoles"),
                            ("secretariat", "secrétariat"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="fonction au CO",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "actif"), ("revoked", "révoqué")],
                        default="active",
                        max_length=8,
                        verbose_name="statut",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("invitation", "invitation"),
                            ("command", "commande"),
                            ("system", "système"),
                        ],
                        max_length=16,
                        verbose_name="origine",
                    ),
                ),
                ("granted_at", models.DateTimeField(verbose_name="attribué le")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="révoqué le"
                    ),
                ),
                (
                    "revoke_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="motif de révocation"
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="user_roles",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="attribué par",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="accounts.roleinvitation",
                        verbose_name="invitation",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="révoqué par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "rôle",
                "verbose_name_plural": "rôles",
            },
        ),
        migrations.AddIndex(
            model_name="roleinvitation",
            index=models.Index(
                fields=["edition", "status"], name="accounts_invitation_edition"
            ),
        ),
        migrations.AddIndex(
            model_name="roleinvitation",
            index=models.Index(
                fields=["email", "status"], name="accounts_invitation_email"
            ),
        ),
        migrations.AddIndex(
            model_name="roleinvitation",
            index=models.Index(
                fields=["invited_by", "created_at"], name="accounts_invitation_quota"
            ),
        ),
        migrations.AddConstraint(
            model_name="roleinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("oc_function__gt", ""), ("role", "OC_MEMBER")),
                    models.Q(
                        models.Q(("role", "OC_MEMBER"), _negated=True),
                        ("oc_function", ""),
                    ),
                    _connector="OR",
                ),
                name="accounts_invitation_oc_fn",
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["edition", "role", "status"], name="accounts_userrole_edition"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "status"], name="accounts_userrole_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("user", "edition", "role", "oc_function"),
                name="accounts_userrole_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("oc_function__gt", ""), ("role", "OC_MEMBER")),
                    models.Q(
                        models.Q(("role", "OC_MEMBER"), _negated=True),
                        ("oc_function", ""),
                    ),
                    _connector="OR",
                ),
                name="accounts_userrole_oc_fn",
            ),
        ),
    ]
