# Generated by Django 5.2.17 on 2026-10-05 19:03

import apps.accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userrole_roleinvitation"),
        ("core", "0003_public_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                validators=[apps.accounts.validators.validate_public_link],
                verbose_name="profil LinkedIn",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="core.publicfile",
                verbose_name="photo",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="scholar_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                validators=[apps.accounts.validators.validate_public_link],
                verbose_name="profil Google Scholar",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                validators=[apps.accounts.validators.validate_public_link],
                verbose_name="site web",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("privacy_notice", "notice d'information"),
                    ("directory_listing", "annuaire public"),
                    ("photo_publication", "publication de la photo"),
                ],
                max_length=32,
                verbose_name="type",
            ),
        ),
    ]
