# Generated by Django 5.2.17 on 2026-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_links_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "administrateur de l'édition"),
                    ("CHAIR", "président de la conférence"),
                    ("SC_CHAIR", "président du comité scientifique"),
                    ("OC_MEMBER", "membre du comité d'organisation"),
                    ("SC_MEMBER", "membre du comité scientifique"),
                    ("SPEAKER", "intervenant"),
                    ("SESSION_CHAIR", "président de session"),
                ],
                max_length=16,
                verbose_name="rôle",
            ),
        ),
    ]
