# Generated by Django 5.2.17 on 2026-10-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_invitable_speaker_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "administrateur de l'édition"),
                    ("CHAIR", "président de la conférence"),
                    ("SC_CHAIR", "président du comité scientifique"),
                    ("OC_MEMBER", "membre du comité d'organisation"),
                    ("SC_MEMBER", "membre du comité scientifique"),
                    ("SPEAKER", "intervenant"),
                    ("SESSION_CHAIR", "président de session"),
                    ("VOLUNTEER", "bénévole"),
                    ("SIGNATORY", "signataire"),
                ],
                max_length=16,
                verbose_name="rôle",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "administrateur de l'édition"),
                    ("CHAIR", "président de la conférence"),
                    ("OC_MEMBER", "membre du comité d'organisation"),
                    ("SC_CHAIR", "président du comité scientifique"),
                    ("SC_MEMBER", "membre du comité scientifique"),
                    ("AUTHOR", "auteur"),
                    ("SPEAKER", "intervenant"),
                    ("SESSION_CHAIR", "président de session"),
                    ("ATTENDEE", "participant"),
                    ("SPONSOR", "partenaire"),
                    ("VOLUNTEER", "bénévole"),
                    ("SIGNATORY", "signataire"),
                ],
                max_length=16,
                verbose_name="rôle",
            ),
        ),
    ]
