# Generated by Django 5.2.17 on 2026-10-05 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0002_conference_current_edition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(max_length=64, verbose_name="identifiant d'URL"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="page du site"
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=255, verbose_name="titre (FR)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="titre (EN)",
                    ),
                ),
                (
                    "description_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="description (FR)",
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="description (EN)",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="publiée"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "ordering": ("-is_system", "slug", "id"),
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(db_index=True, verbose_name="mis en ligne le"),
                ),
                (
                    "release",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="version"
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "mise en ligne du portail",
                "verbose_name_plural": "mises en ligne du portail",
                "ordering": ("-published_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, verbose_name="code")),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("rich_text", "texte riche"),
                            ("cta_banner", "bandeau d'appel à l'action"),
                            ("image_text", "image et texte"),
                            ("edition_hero", "en-tête de l'édition"),
                            ("key_dates", "dates clés"),
                            ("tracks", "thématiques"),
                            ("submission_types", "types de communication"),
                            ("documents", "documents"),
                            ("committee", "comité"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="titre (FR)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="titre (EN)",
                    ),
                ),
                (
                    "subtitle_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="sous-titre (FR)",
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="sous-titre (EN)",
                    ),
                ),
                (
                    "body_fr",
                    models.TextField(blank=True, default="", verbose_name="corps (FR)"),
                ),
                (
                    "body_en",
                    models.TextField(blank=True, default="", verbose_name="corps (EN)"),
                ),
                (
                    "cta_label_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="bouton 1 (FR)",
                    ),
                ),
                (
                    "cta_label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="bouton 1 (EN)",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="lien du bouton 1",
                    ),
                ),
                (
                    "cta2_label_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="bouton 2 (FR)",
                    ),
                ),
                (
                    "cta2_label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="bouton 2 (EN)",
                    ),
                ),
                (
                    "cta2_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="lien du bouton 2",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="configuration"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="publiée"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "section",
                "verbose_name_plural": "sections",
                "ordering": ("code", "id"),
            },
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(verbose_name="position")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="portal.page",
                        verbose_name="page",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="placements",
                        to="portal.section",
                        verbose_name="section",
                    ),
                ),
            ],
            options={
                "verbose_name": "section posée",
                "verbose_name_plural": "sections posées",
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddField(
            model_name="page",
            name="sections",
            field=models.ManyToManyField(
                related_name="pages",
                through="portal.PageSection",
                to="portal.section",
                verbose_name="sections",
            ),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.CharField(
                        choices=[("header", "en-tête"), ("footer", "pied de page")],
                        max_length=8,
                        verbose_name="emplacement",
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(max_length=120, verbose_name="libellé (FR)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="libellé (EN)",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="adresse"
                    ),
                ),
                (
                    "new_tab",
                    models.BooleanField(default=False, verbose_name="nouvel onglet"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="publiée"),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="menu_items",
                        to="portal.page",
                        verbose_name="page",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée de menu",
                "verbose_name_plural": "entrées de menu",
                "ordering": ("location", "position", "id"),
                "indexes": [
                    models.Index(
                        fields=["edition", "location", "position"],
                        name="portal_menu_pos",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("page__isnull", False), ("url", "")),
                            models.Q(
                                ("page__isnull", True),
                                models.Q(("url", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="portal_menu_page_xor_url",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"), name="portal_section_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagesection",
            constraint=models.UniqueConstraint(
                fields=("page", "section"), name="portal_placement_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagesection",
            constraint=models.UniqueConstraint(
                fields=("page", "position"), name="portal_placement_pos"
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                fields=("edition", "slug"), name="portal_page_slug"
            ),
        ),
    ]
