# Generated by Django 5.2.17 on 2026-10-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_public_file"),
        ("portal", "0002_seed_existing_editions"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="core.publicfile",
                verbose_name="image",
            ),
        ),
    ]
