# Generated by Django 5.2.17 on 2026-10-05 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0004_submission_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="référence",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, default="", max_length=2, verbose_name="langue"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="titre"
                    ),
                ),
                (
                    "abstract",
                    models.TextField(blank=True, default="", verbose_name="résumé"),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, verbose_name="mots-clés"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "brouillon"),
                            ("submitted", "soumise"),
                            ("screening", "vérification de recevabilité"),
                            ("under_review", "en cours d'évaluation"),
                            ("reviewed", "évaluée"),
                            ("accepted", "acceptée"),
                            ("accepted_minor", "acceptée sous réserve de corrections"),
                            ("waitlist", "liste d'attente"),
                            ("rejected", "rejetée"),
                            ("revision_requested", "corrections demandées"),
                            ("camera_ready_received", "version finale reçue"),
                            ("confirmed", "présentation confirmée"),
                            ("scheduled", "programmée"),
                            ("presented", "présentée"),
                            ("published", "publiée dans les actes"),
                            ("withdrawn", "retirée"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="statut",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="soumise le"
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="retirée le"
                    ),
                ),
                (
                    "withdraw_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="motif du retrait"
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=0, verbose_name="révision"),
                ),
                (
                    "declarations",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="déclarations"
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="submissions",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "submission_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="submissions",
                        to="conferences.submissiontype",
                        verbose_name="type de communication",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="soumissionnaire",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="submissions",
                        to="conferences.track",
                        verbose_name="thématique",
                    ),
                ),
            ],
            options={
                "verbose_name": "soumission",
                "verbose_name_plural": "soumissions",
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("draft", "brouillon"),
                            ("submitted", "soumise"),
                            ("screening", "vérification de recevabilité"),
                            ("under_review", "en cours d'évaluation"),
                            ("reviewed", "évaluée"),
                            ("accepted", "acceptée"),
                            ("accepted_minor", "acceptée sous réserve de corrections"),
                            ("waitlist", "liste d'attente"),
                            ("rejected", "rejetée"),
                            ("revision_requested", "corrections demandées"),
                            ("camera_ready_received", "version finale reçue"),
                            ("confirmed", "présentation confirmée"),
                            ("scheduled", "programmée"),
                            ("presented", "présentée"),
                            ("published", "publiée dans les actes"),
                            ("withdrawn", "retirée"),
                        ],
                        max_length=24,
                        verbose_name="statut précédent",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "brouillon"),
                            ("submitted", "soumise"),
                            ("screening", "vérification de recevabilité"),
                            ("under_review", "en cours d'évaluation"),
                            ("reviewed", "évaluée"),
                            ("accepted", "acceptée"),
                            ("accepted_minor", "acceptée sous réserve de corrections"),
                            ("waitlist", "liste d'attente"),
                            ("rejected", "rejetée"),
                            ("revision_requested", "corrections demandées"),
                            ("camera_ready_received", "version finale reçue"),
                            ("confirmed", "présentation confirmée"),
                            ("scheduled", "programmée"),
                            ("presented", "présentée"),
                            ("published", "publiée dans les actes"),
                            ("withdrawn", "retirée"),
                        ],
                        max_length=24,
                        verbose_name="nouveau statut",
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="libellé de l'acteur",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="motif"),
                ),
                ("at", models.DateTimeField(verbose_name="date")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acteur",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="status_history",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
            ],
            options={
                "verbose_name": "historique de statut",
                "verbose_name_plural": "historiques de statut",
                "ordering": ("at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SubmissionAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(verbose_name="ordre")),
                ("first_name", models.CharField(max_length=150, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="adresse e-mail"),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="institution",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=2, verbose_name="pays"
                    ),
                ),
                (
                    "is_corresponding",
                    models.BooleanField(
                        default=False, verbose_name="auteur correspondant"
                    ),
                ),
                (
                    "is_presenter",
                    models.BooleanField(
                        default=False, verbose_name="auteur présentateur"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="authorships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "auteur",
                "verbose_name_plural": "auteurs",
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="SubmissionExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("until", models.DateTimeField(verbose_name="échéance (UTC)")),
                ("reason", models.TextField(verbose_name="motif")),
                ("granted_at", models.DateTimeField(verbose_name="accordée le")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="révoquée le"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="accordée par",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="extensions",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
            ],
            options={
                "verbose_name": "dérogation",
                "verbose_name_plural": "dérogations",
                "ordering": ("-granted_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("main", "fichier principal"),
                            ("camera_ready", "version finale"),
                        ],
                        max_length=16,
                        verbose_name="nature",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(verbose_name="version")),
                (
                    "storage_name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="nom de stockage"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="nom d'origine"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="taille (octets)")),
                (
                    "sha256",
                    models.CharField(max_length=64, verbose_name="empreinte SHA-256"),
                ),
                ("pages", models.PositiveIntegerField(verbose_name="pages")),
                (
                    "metadata_removed",
                    models.BooleanField(
                        default=False, verbose_name="métadonnées retirées"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="courant"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="files",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="déposé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "fichier de soumission",
                "verbose_name_plural": "fichiers de soumission",
            },
        ),
        migrations.CreateModel(
            name="SubmissionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="numéro")),
                ("at", models.DateTimeField(verbose_name="date")),
                ("snapshot", models.JSONField(verbose_name="cliché")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acteur",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="revisions",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
            ],
            options={
                "verbose_name": "révision de soumission",
                "verbose_name_plural": "révisions de soumission",
                "ordering": ("number",),
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["edition", "status"], name="sub_edition_status"),
        ),
        migrations.AddConstraint(
            model_name="submissionauthor",
            constraint=models.UniqueConstraint(
                fields=("submission", "position"), name="sub_author_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionauthor",
            constraint=models.UniqueConstraint(
                fields=("submission", "email"), name="sub_author_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionextension",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="sub_extension_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionfile",
            constraint=models.UniqueConstraint(
                fields=("submission", "kind", "version"), name="sub_file_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionrevision",
            constraint=models.UniqueConstraint(
                fields=("submission", "number"), name="sub_revision_number"
            ),
        ),
    ]
