# Generated by Django 5.2.17 on 2026-10-05 23:30

import re
import unicodedata

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _title_key(title: str) -> str:
    """Copie figée de ``services.normalized_title`` (une migration ne dépend pas du code
    courant) : sans accents, en minuscules, ponctuation retirée, espaces réduits."""
    text = unicodedata.normalize("NFKD", title or "")
    text = "".join(char for char in text if not unicodedata.combining(char)).casefold()
    return " ".join(re.sub(r"[^\w]+", " ", text).split())[:300]


def fill_title_keys(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")
    for submission in Submission.objects.exclude(title="").only("pk", "title"):
        Submission.objects.filter(pk=submission.pk).update(title_key=_title_key(submission.title))


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0004_submission_settings"),
        ("submissions", "0002_reference_counters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("j7", "sept jours avant la clôture"),
                            ("j1", "la veille de la clôture"),
                        ],
                        max_length=4,
                        verbose_name="rappel",
                    ),
                ),
                ("sent_at", models.DateTimeField(verbose_name="envoyé le")),
            ],
            options={
                "verbose_name": "rappel de brouillon",
                "verbose_name_plural": "rappels de brouillon",
            },
        ),
        migrations.AddField(
            model_name="submission",
            name="title_key",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="titre normalisé"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["edition", "submitter", "title_key"], name="sub_title_key"
            ),
        ),
        migrations.AddField(
            model_name="draftreminder",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="submissions.submission",
                verbose_name="soumission",
            ),
        ),
        migrations.AddConstraint(
            model_name="draftreminder",
            constraint=models.UniqueConstraint(
                fields=("submission", "kind"), name="sub_reminder_once"
            ),
        ),
        migrations.RunPython(fill_title_keys, migrations.RunPython.noop),
    ]
