# Generated by Django 5.2.17 on 2026-10-06 00:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0005_edition_confidence_weighted_score_and_more"),
        ("submissions", "0003_duplicates_reminders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accepted", "acceptée"),
                            ("accepted_minor", "acceptée sous réserve de corrections"),
                            ("waitlist", "liste d'attente"),
                            ("rejected", "rejetée"),
                        ],
                        max_length=16,
                        verbose_name="issue",
                    ),
                ),
                (
                    "comment_to_authors",
                    models.TextField(
                        blank=True, default="", verbose_name="commentaire aux auteurs"
                    ),
                ),
                ("decided_at", models.DateTimeField(verbose_name="décidée le")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publiée le"
                    ),
                ),
                (
                    "assigned_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.submissiontype",
                        verbose_name="format attribué",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="décidée par",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="decision",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
            ],
            options={
                "verbose_name": "décision",
                "verbose_name_plural": "décisions",
            },
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_at", models.DateTimeField(verbose_name="ouverte le")),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ouverte par",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="discussion",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
            ],
            options={
                "verbose_name": "discussion",
                "verbose_name_plural": "discussions",
            },
        ),
        migrations.CreateModel(
            name="DiscussionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="message")),
                ("at", models.DateTimeField(verbose_name="date")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur du message",
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="messages",
                        to="reviews.discussion",
                        verbose_name="discussion",
                    ),
                ),
            ],
            options={
                "verbose_name": "message de discussion",
                "verbose_name_plural": "messages de discussion",
                "ordering": ("discussion", "at", "id"),
            },
        ),
        migrations.CreateModel(
            name="EvaluationGrid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, verbose_name="version"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "scale_min",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="note minimale"
                    ),
                ),
                (
                    "scale_max",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="note maximale",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verrouillée le"
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="clé d'unicité"
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="grids",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "submission_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.submissiontype",
                        verbose_name="type de communication",
                    ),
                ),
            ],
            options={
                "verbose_name": "grille d'évaluation",
                "verbose_name_plural": "grilles d'évaluation",
                "ordering": ("edition", "submission_type", "-version", "id"),
            },
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=32, verbose_name="code")),
                (
                    "label_fr",
                    models.CharField(max_length=255, verbose_name="libellé (FR)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="libellé (EN)",
                    ),
                ),
                (
                    "help_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="aide à la notation (FR)"
                    ),
                ),
                (
                    "help_en",
                    models.TextField(
                        blank=True, default="", verbose_name="aide à la notation (EN)"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="poids (%)",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="obligatoire"),
                ),
                (
                    "grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="reviews.evaluationgrid",
                        verbose_name="grille",
                    ),
                ),
            ],
            options={
                "verbose_name": "critère",
                "verbose_name_plural": "critères",
                "ordering": ("grid", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="FinalVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response_letter",
                    models.TextField(
                        blank=True, default="", verbose_name="lettre de réponse"
                    ),
                ),
                ("submitted_at", models.DateTimeField(verbose_name="déposée le")),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="submissions.submissionfile",
                        verbose_name="fichier",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="final_version",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
            ],
            options={
                "verbose_name": "version finale",
                "verbose_name_plural": "versions finales",
            },
        ),
        migrations.CreateModel(
            name="ReviewAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_at", models.DateTimeField(verbose_name="affectée le")),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="échéance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("declined", "déclinée"),
                            ("cancelled", "annulée"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="motif (refus ou annulation)",
                    ),
                ),
                (
                    "conflict_override_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="motif de la levée de conflit",
                    ),
                ),
                (
                    "reminders",
                    models.JSONField(
                        blank=True, default=list, verbose_name="relances envoyées"
                    ),
                ),
                (
                    "pseudonym_rank",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="rang du pseudonyme"
                    ),
                ),
                (
                    "active_key",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="clé d'unicité active",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="affectée par",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="review_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="relecteur",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="assignments",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
            ],
            options={
                "verbose_name": "affectation",
                "verbose_name_plural": "affectations",
                "ordering": ("submission", "pseudonym_rank", "id"),
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "brouillon"), ("submitted", "envoyée")],
                        default="draft",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept", "accepter"),
                            ("accept_minor", "accepter avec corrections"),
                            ("reject", "rejeter"),
                            ("discuss", "discuter"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="recommandation",
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="confiance",
                    ),
                ),
                (
                    "comment_to_authors",
                    models.TextField(
                        blank=True, default="", verbose_name="commentaire aux auteurs"
                    ),
                ),
                (
                    "comment_to_committee",
                    models.TextField(
                        blank=True, default="", verbose_name="commentaire au comité"
                    ),
                ),
                (
                    "ethics_flag",
                    models.BooleanField(
                        default=False, verbose_name="signalement d'éthique"
                    ),
                ),
                (
                    "plagiarism_flag",
                    models.BooleanField(default=False, verbose_name="plagiat présumé"),
                ),
                (
                    "weighted_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="note pondérée (sur 100)",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoyée le"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=0, verbose_name="version"),
                ),
                (
                    "grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="reviews.evaluationgrid",
                        verbose_name="grille",
                    ),
                ),
                (
                    "suggested_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.submissiontype",
                        verbose_name="format suggéré",
                    ),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="review",
                        to="reviews.reviewassignment",
                        verbose_name="affectation",
                    ),
                ),
            ],
            options={
                "verbose_name": "évaluation",
                "verbose_name_plural": "évaluations",
            },
        ),
        migrations.CreateModel(
            name="ReviewerTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="conferences.track",
                        verbose_name="thématique",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="relecteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "expertise",
                "verbose_name_plural": "expertises",
            },
        ),
        migrations.CreateModel(
            name="ReviewScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="note"
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="reviews.criterion",
                        verbose_name="critère",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="reviews.review",
                        verbose_name="évaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "note de critère",
                "verbose_name_plural": "notes de critère",
            },
        ),
        migrations.CreateModel(
            name="ReviewVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="version")),
                ("at", models.DateTimeField(verbose_name="date")),
                ("snapshot", models.JSONField(verbose_name="cliché")),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="versions",
                        to="reviews.review",
                        verbose_name="évaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "version d'évaluation",
                "verbose_name_plural": "versions d'évaluation",
                "ordering": ("review", "version"),
            },
        ),
        migrations.CreateModel(
            name="ConflictOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("reviewer", "déclaré par le relecteur"),
                            ("system", "détecté par le système"),
                            ("chair", "déclaré par le président"),
                        ],
                        max_length=10,
                        verbose_name="origine",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("author", "auteur de la soumission"),
                            ("institution", "même institution"),
                            ("declared", "déclaré"),
                        ],
                        max_length=12,
                        verbose_name="nature",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="motif"),
                ),
                (
                    "overridden_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="levé le"),
                ),
                (
                    "overridden_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="motif de la levée"
                    ),
                ),
                (
                    "declared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="déclaré par",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="levé par",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="relecteur",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="conflicts",
                        to="submissions.submission",
                        verbose_name="soumission",
                    ),
                ),
            ],
            options={
                "verbose_name": "conflit d'intérêts",
                "verbose_name_plural": "conflits d'intérêts",
                "ordering": ("submission", "reviewer", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "reviewer", "kind"),
                        name="rev_conflict_once",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="evaluationgrid",
            constraint=models.CheckConstraint(
                condition=models.Q(("scale_min__lt", models.F("scale_max"))),
                name="rev_grid_scale_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.UniqueConstraint(
                fields=("grid", "code"), name="rev_criterion_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gt", 0)), name="rev_criterion_weight"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["reviewer", "status"], name="rev_assignment_reviewer"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 1), ("confidence__lte", 5)),
                    _connector="OR",
                ),
                name="rev_review_confidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewertrack",
            constraint=models.UniqueConstraint(
                fields=("user", "edition", "track"), name="rev_reviewer_track"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewscore",
            constraint=models.UniqueConstraint(
                fields=("review", "criterion"), name="rev_score_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewversion",
            constraint=models.UniqueConstraint(
                fields=("review", "version"), name="rev_version_once"
            ),
        ),
    ]
