# Generated by Django 5.2.17 on 2026-10-06 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0006_program_settings"),
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="raison sociale",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="adresse"),
                ),
                (
                    "tax_identifiers",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="identifiants (registre, fiscal)",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="taux de TVA (%)",
                    ),
                ),
                (
                    "vat_note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="mention de TVA",
                    ),
                ),
                (
                    "footer",
                    models.TextField(
                        blank=True, default="", verbose_name="pied de page"
                    ),
                ),
                (
                    "bank_details",
                    models.TextField(
                        blank=True, default="", verbose_name="coordonnées bancaires"
                    ),
                ),
                (
                    "invoice_prefix",
                    models.CharField(
                        default="F", max_length=8, verbose_name="préfixe des factures"
                    ),
                ),
                (
                    "credit_note_prefix",
                    models.CharField(
                        default="AV", max_length=8, verbose_name="préfixe des avoirs"
                    ),
                ),
                (
                    "proforma_prefix",
                    models.CharField(
                        default="PF", max_length=8, verbose_name="préfixe des pro forma"
                    ),
                ),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="billing_profile",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "mentions de facturation",
                "verbose_name_plural": "mentions de facturation",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "paiement manuel"),
                            ("fake", "fournisseur factice"),
                            ("cinetpay", "CinetPay"),
                        ],
                        max_length=16,
                        verbose_name="fournisseur",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("online", "paiement en ligne"),
                            ("transfer", "virement (bon de commande)"),
                            ("onsite", "sur place"),
                            ("free", "aucun paiement (montant nul)"),
                            ("waiver", "gratuité accordée"),
                        ],
                        max_length=10,
                        verbose_name="moyen",
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=30, verbose_name="référence"),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="référence du fournisseur",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XOF", "franc CFA (UEMOA)"),
                            ("XAF", "franc CFA (CEMAC)"),
                            ("EUR", "euro"),
                            ("USD", "dollar des États-Unis"),
                            ("GNF", "franc guinéen"),
                            ("CDF", "franc congolais"),
                        ],
                        max_length=3,
                        verbose_name="devise",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "initié"),
                            ("pending", "en cours"),
                            ("succeeded", "réussi"),
                            ("failed", "échoué"),
                            ("cancelled", "abandonné"),
                        ],
                        default="initiated",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="dernier statut du fournisseur",
                    ),
                ),
                (
                    "notify_token_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="empreinte du jeton de notification",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminé le"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernière interrogation"
                    ),
                ),
                (
                    "received_on",
                    models.DateField(blank=True, null=True, verbose_name="reçu le"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="note"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validé par",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments",
                        to="registrations.registration",
                        verbose_name="inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "verbose_name_plural": "paiements",
                "ordering": ("registration", "-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="BillingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("invoice", "facture"),
                            ("credit_note", "avoir"),
                            ("proforma", "pro forma"),
                        ],
                        max_length=12,
                        verbose_name="nature",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="année")),
                (
                    "sequence",
                    models.PositiveIntegerField(verbose_name="rang dans la série"),
                ),
                ("number", models.CharField(max_length=32, verbose_name="numéro")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XOF", "franc CFA (UEMOA)"),
                            ("XAF", "franc CFA (CEMAC)"),
                            ("EUR", "euro"),
                            ("USD", "dollar des États-Unis"),
                            ("GNF", "franc guinéen"),
                            ("CDF", "franc congolais"),
                        ],
                        max_length=3,
                        verbose_name="devise",
                    ),
                ),
                ("lines", models.JSONField(default=list, verbose_name="lignes")),
                (
                    "issuer",
                    models.JSONField(
                        default=dict, verbose_name="émetteur (mentions figées)"
                    ),
                ),
                (
                    "customer",
                    models.JSONField(
                        default=dict, verbose_name="client (identité figée)"
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(max_length=64, verbose_name="fichier"),
                ),
                (
                    "sha256",
                    models.CharField(max_length=64, verbose_name="empreinte SHA-256"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="taille")),
                ("issued_at", models.DateTimeField(verbose_name="émise le")),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="billing_documents",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="émise par",
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="credit_notes",
                        to="payments.billingdocument",
                        verbose_name="facture d'origine",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="billing_documents",
                        to="registrations.registration",
                        verbose_name="inscription",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="billing_documents",
                        to="payments.payment",
                        verbose_name="paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "pièce de facturation",
                "verbose_name_plural": "pièces de facturation",
                "ordering": ("edition", "kind", "year", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="PaymentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "paiement manuel"),
                            ("fake", "fournisseur factice"),
                            ("cinetpay", "CinetPay"),
                        ],
                        max_length=16,
                        verbose_name="fournisseur",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="référence annoncée",
                    ),
                ),
                ("received_at", models.DateTimeField(verbose_name="reçue le")),
                (
                    "token_valid",
                    models.BooleanField(default=False, verbose_name="jeton valide"),
                ),
                ("outcome", models.CharField(max_length=32, verbose_name="issue")),
                ("body", models.JSONField(default=dict, verbose_name="champs reçus")),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notifications",
                        to="payments.payment",
                        verbose_name="paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification de paiement",
                "verbose_name_plural": "notifications de paiement",
                "ordering": ("-received_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XOF", "franc CFA (UEMOA)"),
                            ("XAF", "franc CFA (CEMAC)"),
                            ("EUR", "euro"),
                            ("USD", "dollar des États-Unis"),
                            ("GNF", "franc guinéen"),
                            ("CDF", "franc congolais"),
                        ],
                        max_length=3,
                        verbose_name="devise",
                    ),
                ),
                ("method", models.CharField(max_length=64, verbose_name="moyen")),
                (
                    "reference",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="référence"
                    ),
                ),
                ("refunded_on", models.DateField(verbose_name="remboursé le")),
                (
                    "credit_note",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="refund",
                        to="payments.billingdocument",
                        verbose_name="avoir",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="enregistré par",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="refunds",
                        to="registrations.registration",
                        verbose_name="inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "remboursement",
                "verbose_name_plural": "remboursements",
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "provider"], name="pay_status_provider"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("provider", "reference"), name="pay_reference"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="pay_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.UniqueConstraint(
                fields=("edition", "kind", "year", "sequence"),
                name="pay_document_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.UniqueConstraint(
                fields=("edition", "number"), name="pay_document_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="pay_document_amount"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "credit_note"), ("original__isnull", False)),
                    models.Q(
                        models.Q(("kind", "credit_note"), _negated=True),
                        ("original__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="pay_document_original",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentnotification",
            index=models.Index(
                fields=["provider", "reference"], name="pay_notification_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="pay_refund_amount"
            ),
        ),
    ]
