# Generated by Django 5.2.17 on 2026-10-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "to_email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="destinataire"
                    ),
                ),
                (
                    "template_code",
                    models.CharField(max_length=64, verbose_name="gabarit"),
                ),
                ("locale", models.CharField(max_length=8, verbose_name="langue")),
                ("subject", models.CharField(max_length=255, verbose_name="objet")),
                (
                    "body_text",
                    models.TextField(
                        blank=True, default="", verbose_name="corps (texte)"
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True, default="", verbose_name="corps (HTML)"
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False, verbose_name="contient un lien à jeton"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "en file"),
                            ("sending", "en cours d'envoi"),
                            ("sent", "envoyé"),
                            ("failed", "en échec"),
                            ("cancelled", "annulé"),
                        ],
                        default="queued",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="tentatives"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", verbose_name="dernière erreur"
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="programmé le")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoyé le"
                    ),
                ),
                (
                    "purged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="corps purgé le"
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="identifiant chez le fournisseur",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="clé d'idempotence",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="compte destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "e-mail envoyé",
                "verbose_name_plural": "e-mails envoyés",
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"], name="comm_outbox_status"
                    ),
                    models.Index(
                        fields=["to_user", "created_at"], name="comm_outbox_user"
                    ),
                ],
            },
        ),
    ]
