# Generated by Django 5.2.17 on 2026-10-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
        ("conferences", "0002_conference_current_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxemail",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="conferences.edition",
                verbose_name="édition",
            ),
        ),
    ]
