# Generated by Django 5.2.17 on 2026-10-05 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_outbox_edition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("submission_received", "soumission reçue"),
                            ("submission_withdrawn", "soumission retirée"),
                            ("coauthor_added", "déclaré co-auteur"),
                            ("extension_granted", "dérogation accordée"),
                            ("draft_reminder", "brouillon à soumettre"),
                        ],
                        max_length=32,
                        verbose_name="nature",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="données"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="lue le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"], name="comm_notification_unread"
                    )
                ],
            },
        ),
    ]
