# Generated by Django 5.2.17 on 2026-10-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0006_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("submission_received", "soumission reçue"),
                    ("submission_withdrawn", "soumission retirée"),
                    ("coauthor_added", "déclaré co-auteur"),
                    ("extension_granted", "dérogation accordée"),
                    ("draft_reminder", "brouillon à soumettre"),
                    ("screening_rejected", "soumission non recevable"),
                    ("decision_published", "décision publiée"),
                    ("final_version_received", "version finale reçue"),
                    ("task_assigned", "tâche confiée"),
                    ("shift_assigned", "poste de bénévolat confié"),
                    ("shift_removed", "poste de bénévolat retiré"),
                ],
                max_length=32,
                verbose_name="nature",
            ),
        ),
    ]
