# Generated by Django 5.2.17 on 2026-10-07 02:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0007_alter_notification_kind"),
        ("conferences", "0006_program_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxemail",
            name="is_bulk",
            field=models.BooleanField(default=False, verbose_name="envoi groupé"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("submission_received", "soumission reçue"),
                    ("submission_withdrawn", "soumission retirée"),
                    ("coauthor_added", "déclaré co-auteur"),
                    ("extension_granted", "dérogation accordée"),
                    ("draft_reminder", "brouillon à soumettre"),
                    ("screening_rejected", "soumission non recevable"),
                    ("decision_published", "décision publiée"),
                    ("final_version_received", "version finale reçue"),
                    ("task_assigned", "tâche confiée"),
                    ("shift_assigned", "poste de bénévolat confié"),
                    ("shift_removed", "poste de bénévolat retiré"),
                    ("announcement", "annonce"),
                ],
                max_length=32,
                verbose_name="nature",
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title_fr",
                    models.CharField(max_length=150, verbose_name="titre (FR)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="titre (EN)",
                    ),
                ),
                (
                    "body_fr",
                    models.TextField(blank=True, default="", verbose_name="texte (FR)"),
                ),
                (
                    "body_en",
                    models.TextField(blank=True, default="", verbose_name="texte (EN)"),
                ),
                (
                    "on_news",
                    models.BooleanField(default=False, verbose_name="actualités"),
                ),
                (
                    "on_banner",
                    models.BooleanField(default=False, verbose_name="bandeau"),
                ),
                ("on_bell", models.BooleanField(default=False, verbose_name="cloche")),
                ("by_email", models.BooleanField(default=False, verbose_name="e-mail")),
                (
                    "segment",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="segment"
                    ),
                ),
                (
                    "banner_message_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=280,
                        verbose_name="message du bandeau (FR)",
                    ),
                ),
                (
                    "banner_message_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=280,
                        verbose_name="message du bandeau (EN)",
                    ),
                ),
                (
                    "banner_starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="début du bandeau"
                    ),
                ),
                (
                    "banner_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fin du bandeau"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "brouillon"),
                            ("published", "publiée"),
                            ("withdrawn", "retirée"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publiée le"
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="retirée le"
                    ),
                ),
                (
                    "sending_status",
                    models.CharField(
                        choices=[
                            ("none", "aucun envoi"),
                            ("queuing", "mise en file"),
                            ("queued", "en file d'envoi"),
                            ("cancelled", "annulé"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="envoi",
                    ),
                ),
                (
                    "recipients_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="destinataires comptés"
                    ),
                ),
                (
                    "delivered_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="destinataires traités"
                    ),
                ),
                (
                    "emails_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="e-mails mis en file"
                    ),
                ),
                (
                    "fan_out_cursor",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="curseur de mise en file"
                    ),
                ),
                (
                    "sending_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoi commencé le"
                    ),
                ),
                (
                    "sending_finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoi arrêté le"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créée par",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="announcements",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
            ],
            options={
                "verbose_name": "annonce",
                "verbose_name_plural": "annonces",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AnnouncementDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emailed",
                    models.BooleanField(
                        default=False, verbose_name="e-mail mis en file"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="traité le"
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="deliveries",
                        to="communications.announcement",
                        verbose_name="annonce",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "destinataire d'une annonce",
                "verbose_name_plural": "destinataires des annonces",
            },
        ),
        migrations.CreateModel(
            name="AnnouncementOptOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="désabonné le"
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="conferences.edition",
                        verbose_name="édition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "désabonnement des annonces",
                "verbose_name_plural": "désabonnements des annonces",
            },
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["edition", "status"], name="comm_announcement_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("banner_starts_at__isnull", True),
                    ("banner_ends_at__isnull", True),
                    ("banner_ends_at__gt", models.F("banner_starts_at")),
                    _connector="OR",
                ),
                name="comm_announcement_banner_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementdelivery",
            constraint=models.UniqueConstraint(
                fields=("announcement", "user"), name="comm_delivery_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementoptout",
            constraint=models.UniqueConstraint(
                fields=("user", "edition"), name="comm_opt_out_unique"
            ),
        ),
    ]
