/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicSponsors } from '../../models/public-sponsors';

export interface PublicSponsors$Params {
}

export function publicSponsors(http: HttpClient, rootUrl: string, params?: PublicSponsors$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicSponsors>> {
  const rb = new RequestBuilder(rootUrl, publicSponsors.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicSponsors>;
    })
  );
}

publicSponsors.PATH = '/v1/public/sponsors';
