/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicMenuItem } from '../../models/public-menu-item';

export interface PublicPortalMenu$Params {
  location: 'footer' | 'header';
}

export function publicPortalMenu(http: HttpClient, rootUrl: string, params: PublicPortalMenu$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PublicMenuItem>>> {
  const rb = new RequestBuilder(rootUrl, publicPortalMenu.PATH, 'get');
  if (params) {
    rb.query('location', params.location, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PublicMenuItem>>;
    })
  );
}

publicPortalMenu.PATH = '/v1/public/portal/menu';
