/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicSite } from '../../models/public-site';

export interface PublicPortalSite$Params {
}

export function publicPortalSite(http: HttpClient, rootUrl: string, params?: PublicPortalSite$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicSite>> {
  const rb = new RequestBuilder(rootUrl, publicPortalSite.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicSite>;
    })
  );
}

publicPortalSite.PATH = '/v1/public/portal/site';
