/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicProgramDay } from '../../models/public-program-day';

export interface PublicProgramDay$Params {
  day: string;
}

export function publicProgramDay(http: HttpClient, rootUrl: string, params: PublicProgramDay$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicProgramDay>> {
  const rb = new RequestBuilder(rootUrl, publicProgramDay.PATH, 'get');
  if (params) {
    rb.path('day', params.day, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicProgramDay>;
    })
  );
}

publicProgramDay.PATH = '/v1/public/program/days/{day}';
