/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicRoutes } from '../../models/public-routes';

export interface PublicPortalRoutes$Params {
}

export function publicPortalRoutes(http: HttpClient, rootUrl: string, params?: PublicPortalRoutes$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicRoutes>> {
  const rb = new RequestBuilder(rootUrl, publicPortalRoutes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicRoutes>;
    })
  );
}

publicPortalRoutes.PATH = '/v1/public/portal/routes';
