/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Unsubscribed } from '../../models/unsubscribed';
import { UnsubscribeRequest } from '../../models/unsubscribe-request';

export interface PublicAnnouncementsUnsubscribe$Params {
      body: UnsubscribeRequest
}

export function publicAnnouncementsUnsubscribe(http: HttpClient, rootUrl: string, params: PublicAnnouncementsUnsubscribe$Params, context?: HttpContext): Observable<StrictHttpResponse<Unsubscribed>> {
  const rb = new RequestBuilder(rootUrl, publicAnnouncementsUnsubscribe.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Unsubscribed>;
    })
  );
}

publicAnnouncementsUnsubscribe.PATH = '/v1/public/announcements/unsubscribe';
